### ISSUE TITLE
@mentions

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1048]
- [x] 1. Use @someone mention in HTML enabled editors
- [x] 2. Send notification when someone is mentioned, make a notification like this -  "you was mentioned", with link to `http://example.com/searchKeyword.php?type=mention&keyword={profile_id}`. Use alert in `BxDolMetatags::_metaAdd`, modify alert call if needed.

**Comment by AlexTr** [comment]
@AntonLV point 2 is for you

**Comment by AntonLV** [comment]
Point №2 was done.
