### ISSUE TITLE
Convert all field from utf8 to utf8mb4

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1054]
We need to do it to support native emoji, now when native emoji is entered part of content is lost(after emoji symbol) and may cause some PHP errors

For Db:

```sql
ALTER DATABASE db_name_here CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
```

For each table:

```sql
ALTER TABLE table_name_here CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

For each field (change type accordingly):

```sql
ALTER TABLE table_name_here CHANGE field_name_here field_name_here field_type_here(X) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

- [x]  **Change `upgrade/classes/BxDolUpgradeDb.php` file, after update is applied**
- [ ]  **Apply conversion to Jot Messenger with next update**

**Comment by AntonLV** [comment]
The actions should be performed during the upgrade.
