### ISSUE TITLE
Empty space at the bottom of the block when paginate isn't displayed.

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1065]
![image 1](https://user-images.githubusercontent.com/3324866/34946795-6e3e6e38-fa32-11e7-9ae3-3326159b09e8.png)

![image](https://user-images.githubusercontent.com/3324866/34946801-70f13ffc-fa32-11e7-8406-603949de13f9.png)

**Comment by romanlesnikov** [comment]
without pagination
![001](https://user-images.githubusercontent.com/12896257/34950478-53d4b268-fa24-11e7-8f01-170473841a3c.jpg)

with pagination
![002](https://user-images.githubusercontent.com/12896257/34950509-69f2b824-fa24-11e7-8962-a173c2695e82.jpg)
