### ISSUE TITLE
Replace logo image wrapper with H1 tag for better SEO

### ISSUE THREAD

**Issue by yanivz** [unacms/UNA#1087]
https://stackoverflow.com/questions/665037/replacing-h1-text-with-a-logo-image-best-method-for-seo-and-accessibility

**Comment by AlexTr** [comment]
It's some sort of hack which will not work for all sites, so it's better to implement it as custom modification of as custom template. You can to override logo in custom template in `BxTemplFunctions::getMainLogo`  method.
