### ISSUE TITLE
Speaking URLs

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#1095]
The possibility to allow speaking urls would be great.
UNA has much potential to be used as a CMS for regular websites (just hide login) like company websites. But other CMS are better in some fields, like SEO.

If I run a community site, your solution #1091 sounds great. But if you use UNA for a personal blog (blog module), you should be able to enable more optimization features for posts, like speaking urls and additional SEO.

**Comment by AlexTr** [comment]
We'll try to make an option in https://github.com/unaio/una/issues/1091 to make speaking urls.
