### ISSUE TITLE
Wrong work of pagination in "Discussions"...

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#1106]
...during "search" action. If number of search results is less than 12 then link to switch next page is still active but after jump it shows "Empty" message. And "next" paginate button is still active. Examples: in una.io need to enter to search field in "Discussions" works like "recaptcha" or "header.inc.php".

**Comment by AlexTr** [comment]
It has been fixed in https://github.com/unaio/una/issues/1098
