### ISSUE TITLE
Timeline: promoted posts

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1118]
We need a feature for admin and moderators to promote some posts in Timeline/Outline. 
Admin/moderator should have "promote" button/link for any post in any timeline. After post is promoted it should be shown in all subscription timelines/outlines in natural order by date. 

For example if user A is subscribed to user B and C. Then he sees posts from user B and C in his subscription timeline. When admin promotes a post from user X, then user A will see a single post from user X between other posts from users B and C.

**Comment by AntonLV** [comment]
Add 'Follow' button for Promoted posts.
