### ISSUE TITLE
BxDolStudioToolsAudit.php file_get_contents() to php.net can hang forever

### ISSUE THREAD

**Issue by timreeves** [unacms/UNA#1125]
In "protected function requirementsPHP()" there is this line:
file_get_contents("https://secure.php.net/releases/index.php?serialize=1");

This is fine in itself BUT...
Currently the php.net website has an IPv6 assigned which is not reachable. Most systems revert to IPv4 which works, as expected. But PHP (all versions) on Debian 8 hangs forever, the installation of UNA is not possible on Debian 8.
See: https://bugs.php.net/bug.php?id=75974

However, it would be prudent to protect your call with a timeout and error message.

I implemented a workaround using Curl, here the code:
`function http_get_contents($url, $opts = [])
{
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_TIMEOUT, 5);
  curl_setopt($ch, CURLOPT_USERAGENT, "{$_SERVER['SERVER_NAME']}");
  curl_setopt($ch, CURLOPT_URL, $url);
  if(is_array($opts) && $opts) {
    foreach($opts as $key => $val) {
      curl_setopt($ch, $key, $val);
    }
  }
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  if(FALSE === ($retval = curl_exec($ch))) {
    error_log(curl_error($ch));
  } else {
    return $retval;
  }
}

$curlopts = [
	CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4
];
$s = http_get_contents('http://www.php.net/releases/index.php?serialize=1', $curlopts);
`
Perhaps it could be useful to incorporate the "http_get_contents" function into UNA core utilities and use it, perhaps in other places where users might be able to have contents inserted from a URI into their web pages for example (it does'nt always have to be an iframe...). And Curl seems more robust or at least better configurable then PHP streams.

Cheers, Tim

**Comment by AlexTr** [comment]
Thank you @timreeves 
Actually we have `bx_file_get_contents` function in inc/utils.inc.php which is using `curl` by default.

**Comment by timreeves** [comment]
Thanks @AlexTr - I have modified my patch as follows:

`
$aParams = array();
$aHeaders = array();
$sHttpCode = null;
$aBasicAuth = array();
$curlopts = [ CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4 ];
$s = bx_file_get_contents('http://www.php.net/releases/index.php?serialize=1', $aParams, 'get', $aHeaders, $sHttpCode, $aBasicAuth, 20, $curlopts);
`
This works for me - thanks for the tip!

**Comment by timreeves** [comment]
See update to [bug notice](https://bugs.php.net/bug.php?id=75974&thanks=2) at php.net.
Since only www.php.net has an IPv6 address, but not php.net (without www.) it would solve the problem just to remove the "www." from the URL.

**Comment by AlexTr** [comment]
Thank you @timreeves
