### ISSUE TITLE
Installation fails with fatal PHP-Error with PHP 7.2.2

### ISSUE THREAD

**Issue by timreeves** [unacms/UNA#1126]
This is the message in the PHP log:

[16-Feb-2018 23:04:27] WARNING: [pool {hidden}.net] child 22258 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Declaration of BxDolModuleQuery::getInstance() must be compatible with BxDolDb::getInstance($aDbConf = false, &$s Error = NULL) in /var/www/vhosts/{hidden}.net/httpdocs/inc/classes/BxDolModuleQuery.php on line 10"

**Comment by timreeves** [comment]
Thanks @AlexTr for taking this up. I have made a rough and ready fix to get our UNA running - at line 31 of BxDolModuleQuery.php I have simply copied in the previous function definition from BxDolDb:

public static function getInstance($aDbConf = false, &$sError = null)

I'm a bit rusty on PHP so don't know if this might cause problems, but at least UNA now runs - and I must say, the guided tour through the UNA Studio really impressed me. Thanks for this great software!

**Comment by timreeves** [comment]
Hm after successful installation and all running on PHP 7.0 I tried switching back to PHP 7.2. Sadly it does not work, the same problem as noted above, and my amateur hack does not fix it. Sorry )-:

**Comment by timreeves** [comment]
One more question: In PHP 7.0 I have apc compatibility and apcu modules. In PHP 7.2 I only have apcu, not the compatibility module - is it required?

**Comment by timreeves** [comment]
BTW the requirements state short_open_tag = On, but I had it off, worked anyway. Is it really needed or are those outdated requirements?

**Comment by AlexTr** [comment]
@timreeves it maybe some problems with 3rd-party apps when this option is off.

**Comment by AlexTr** [comment]
Fixed in another issue - https://github.com/unaio/una/issues/1141

**Comment by AlexTr** [comment]
> One more question: In PHP 7.0 I have apc compatibility and apcu modules. In PHP 7.2 I only have apcu, not the compatibility module - is it required?

@timreeves I've missed your question somehow, you can use different PHP opcode caches, it just your preference.
