### ISSUE TITLE
Notifications popup

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1128]
Display only unread notifications.  
Make a setting for the number of max unread notifications to show in popup.  

![screen shot 2018-02-19 at 3 59 38 pm](https://user-images.githubusercontent.com/3324866/36371125-c5512252-1593-11e8-9b84-041d312af446.png)

**Comment by andreyasko** [comment]
**Update needed.** When Notifications page is visited, the notifications in Notifications popup get cleared. Instead, they should always remain there, with in-popup infinite scroll, with 20 notifications preloaded at a time and extra 20 loading via Ajax call on the down scroll. New notifications should be highlighted in popup with background.
