### ISSUE TITLE
Sign up with Google -> Mailchimp Newsletter subscription bug

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#1144]
Only Site Updates on = subscribed
Also Newsletter on = unsubscribed
-----
And why is "Site Updates" used for Newsletter and not the "Newsletter" toggle itself.
For me "site updates" are simple notifications, while Newsletter are actual newsletter.

**Comment by AlexTr** [comment]
Users are added to Mailchimp as "subscribed" only when user has "Receive Newsletters" ON. However user can unsubscribe later via Mailchimp interface.
