### ISSUE TITLE
Discussions: "Number of items on site home page" has no effect

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#1146]
I added a "New Discussions" block on my home page, but it only uses the "items per page" and not the "items on site home page" settings.

**Comment by AntonLV** [comment]
Cannot reproduce the issue. I did the following:
1. Activated the default "New Discussions" block on homepage.
2. Go to Studio->Discussions and changed 'Number of items on site home page' from 6 to 3.
3. Checked site's home page and it shows 3 items in "New Discussions" block.
