### ISSUE TITLE
System emoji js lib

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1154]

**Comment by AlexeyUna** [comment]
# How to use it:
If you like to attache emoji to some **contenteditable** area, you should add this attribute  **data-emojiable="true"**  into it or you may use any other jquery valid selector as marker for attaching.
Example: **`<div data-emojiable="true"></div>`**

If you don't define any additional options then icon to show popup menu with emojis will be added to the right top corner and as icon will be used **`<i class="sys-icon smile-o"></i>`** which is wrapped to
**`<a class="smiles"></a>`**

## How to initialize emoji:
```js
var oEmojiConf =
{
    emojiable_selector: '[data-emojiable=true]',  /* selector for element to which to attache emoji */
    convert_to_emoji: 0, /* allow to convert members manually typed symbols to unicode smiles, like :) */
    menu_wrapper: 'a.smils', /* selector for element into which to add emoji popup menu icon */
    menu_icon:'<i class="sys-icon smile-o"></i>',  /* emoji popup menu icon */
}
new EmojiPicker(oEmojiConf ).discover();  /* call init emoji function */

/* Another way to init emoji */
var oEmoji = new EmojiPicker(oEmojiConf);
 oEmoji.discover();
```

**Comment by AlexTr** [comment]
Use `bx_editor_get_htmleditable(sEditorSelector)` js function to pass HTML editable area as `emojiable_selector` parameter
