### ISSUE TITLE
Templates: Right side is cutt off when page size greater than 1024px

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#1217]
1024px is the size of Desktop view.

**Comment by AlexTr** [comment]
Тут прикол в том что если мы меняем Page Width в темплейте, то возникает расхождение с CSS размерами из media-tablet.css и media-desktop.css Они статично регламентируют переход между Таблетом и Десктопом при 1024пх. Поэтому если Page Width становится 1400, то если у окна расширение между 1024 и 1400 то часть правая будет закрыта. Появляется скрол, но от скролит только контент, а Статики и Абсолюты остаются на месте. Самая большая проблема с нашим тулбаром - он статик и получается что до аккаунт меню вообще невозможно дотянуться.
В идеале, надо при смене Page Width менять и значения в media-tablet.css и media-desktop.css - тогда все ОК. Но как это сделать не совсем понятно. Переводить все файлы что используют респонсив переход через "Page Width" на ЛИСС. У меня другого варианта нет, а этот уж очень грамостский (особенно в кастомных темплейтах типа Каноникла, где куча интеграций, которые сами настраивают эти переходы в куче мест)

**Comment by AlexTr** [comment]
Because of the changes in this ticket close icon appeared in all popups, because of the following:
В template/css/media-desktop.css файле.
Было 
```css
.bx-def-media-desktop-hide {
```
а стало
```css
.bx-media-desktop .bx-def-media-desktop-hide {
```
И поэтому, крестик из popup_trans.html, имеющий класс `bx-popup-close-wrapper bx-def-padding bx-def-media-desktop-hide bx-def-media-tablet-hide` стал видим.

**Comment by AlexTr** [comment]
Changes in Lucid - https://github.com/unaio/lucid/commit/22b5373311b98aeec5e9d71959c57bc10aa75176
