### ISSUE TITLE
Forms: dynamic loading of form's datepicker

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1307]
`addWebForms()` is called before `jquery-ui-timepicker-addon.min.js` is loaded. I think we need to move call of `bx_get_scripts` to `jquery.webForms.js` and initialize datepicker after ensure that `jquery-ui-timepicker-addon.min.js` is loaded.

**Remove the following records from `sys_preloader` upon update which were added as temporary fix:**

```
INSERT INTO `sys_preloader` (`id`, `module`, `type`, `content`, `active`) VALUES
(49, 'system', 'js_system', 'jquery-ui/jquery-ui.custom.min.js', 1),
(50, 'system', 'js_system', 'timepicker-addon/jquery-ui-sliderAccess.js', 1),
(51, 'system', 'js_system', 'timepicker-addon/jquery-ui-timepicker-addon.min.js', 1);
```

**Comment by romanlesnikov** [comment]
last 2 commit related to #1130
