### ISSUE TITLE
On page notification popup isn't looking good on mobile screen size

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1323]
![screen shot 2018-06-08 at 8 17 28 pm](https://user-images.githubusercontent.com/3324866/41153310-b2a58514-6b59-11e8-9c3b-79b03be4890c.png)

**Comment by AlexTr** [comment]
https://github.com/unaio/una/issues/1622

**Comment by AlexTr** [comment]
@AntonLV it has to be reverted because this fix made all mobile popups not full screen with close link, some more tailored solution is needed just for the notification popups

**Comment by AlexTr** [comment]
@AntonLV it's still not looking good in mobile view:
![image](https://user-images.githubusercontent.com/3324866/46451369-3e308d00-c7d9-11e8-89d6-827aff410068.png)

**Comment by AntonLV** [comment]
This isn't 'on page notification popup'. But it was fixed too.
