### ISSUE TITLE
Add ability to set discussion visibility from URL parameters

### ISSUE THREAD

**Issue by joeyberkovitz** [unacms/UNA#1332]
I would like to be able to add a new discussion from within the /page/discussions-context route.
The new-discussion block doesn't seem to have an option for contextual awareness. As a basic solution, I added the feature in JS in my fork: https://github.com/joeyberkovitz/una/commit/bfb92681d242c4b6a255d83d50ccd60b372c9744, but it's probably not in the best place. I would appreciate guidance as to where the feature should be.

**Comment by joeyberkovitz** [comment]
also would be nice if the same thing could be done for albums

**Comment by AlexTr** [comment]
@joeyberkovitz we're adding the following feature - https://github.com/unaio/una/issues/1347 which should solve this task using alternative way - it adds block with content posting to context page (profile/group) where privacy fields is already set to the appropriate context and hidden, so content is always posted to the particular group/profile/etc
