### ISSUE TITLE
Timeline: allow profile owner and group/event/space admin to pin items in their timelines

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1388]

**Comment by AntonLV** [comment]
1. Only site admins/moderators control what is pinned to other peoples “NEWS FEED” or “PUBLIC FEED”. This way, if something is interesting or they want to promote their own announcement post they can pin their post, by going to PUBLIC FEED or NEWS FEED and pinning it there.
2. Normal users can only pin posts that appear inside their profile TIMELINEs and they will only be pinned inside of the timelines. They don’t get pinned insite NEWS FEED or PUBLIC FEED - not for anyone, not even for themselves. It’s only to show certain posts first inside their profiles.
3. Same as with profiles group-admins can pin posts inside groups, and they behave same as in №2.
4. If I (admin) pin your post to “NEWS FEED” and “PUBLIC FEED” it doesn’t mean that inside your profile it should also be pinned. Inside your profile it should only be pinned if YOU pinned it there. If admin pinned a post inside own profile - it should only be pinned inside his profile.
5. It would be good to separate the names of these actions: 
  For posts inside timelines (users action) callt it: “Pin” and “Unpin”
  For posts in Public and News feeds (admin action) call it “Stick” and “Unstick”
