### ISSUE TITLE
Timeline: smiles popup needs to be attached to the button, not to the area

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1421]
![image](https://user-images.githubusercontent.com/3324866/42612162-1fca69a0-85dd-11e8-8773-5bf88956c005.png)

**Comment by AntonLV** [comment]
Fixed in Ticket #1477, commit https://github.com/unaio/una/commit/c44e38113ceb5e6851fcc8ae42958fe0e90773a7
