### ISSUE TITLE
Albums: some spacing on left and right of the photo in attachments block

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1422]
![image](https://user-images.githubusercontent.com/3324866/42612485-ea7c208e-85de-11e8-9ecc-ff06697c1a8d.png)

**Comment by andreyasko** [comment]
Let's have consistent margins around the image within the card, and make sure it stretches width if needed.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/22210428/43716279-feef92b6-99c6-11e8-9fc8-7fb9e6876eb0.png">
