### ISSUE TITLE
Mature-audience content filter (PG, PG13, R)

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#1430]
t.20611432

**Better approach would be:**

- [x] Add field with PG, PG13, R, X options in every content (this list must be customizable). In profile user can select which profile type should be shown to him/her. If profile less that some curtain age, then lock some options and don't allow to select them, so as soon as person get older, more options is allowed to be chosen
- [x] In all content browsing and content page views don't show content which user selected to now show. Add ability to filter by content type in manage grids. Also we need an option to not show X rated content at all.
- [x] if someone intentionally post something that is mature or R and selects PG then they get a Strike when A Moderator flags it or if a members reports it, if they continue to do so their account will be Set to Mature post only for a probation period, they can still post but they will only see it and anyone of appropriate age level
- [x] similar system is needed for comments too
- [ ] (optional) it would be great to do something in messenger too

---

**Old approach:**
According to this suggestion - https://una.io/page/view-discussion?id=1091 - add a "checkbox" field to content modules marking content as "Mature audience only" when published.

In profiles add a setting for "show mature audience content" filter and apply it to display or hide any items marked as "mature...".

**Comment by AntonLV** [comment]
PHP error after content creation
```
Fatal error: Uncaught ArithmeticError: Bit shift by negative number in /[path_to_una]/inc/classes/BxDolContentFilter.php:139
```
Issue appears if author's profile has an empty birthday.
