### ISSUE TITLE
Lucid template : Spaces picture rendering error

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#1446]
To reproduce: create a space, upload a picture into the space while creating, go to View Space page.
Result:

Lucid (wrong):
![screenshot_7](https://user-images.githubusercontent.com/8243165/42812714-63f5ac0a-89e0-11e8-8075-b83585e10912.jpg)

Decorous (correct):
![screenshot_8](https://user-images.githubusercontent.com/8243165/42812820-ac1452a2-89e0-11e8-8f87-cc746d91adbe.jpg)

**Comment by AntonLV** [comment]
The issue was fixed in private Licud repository.
