### ISSUE TITLE
Timeline: "pin" renaming ane enhancements

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1463]
Change:  
"Pin" to "Pin to this feed”  (or "Pin here")
"Stick" to “Pin to all feeds” (or "Pin for all")

Also don't display "Pin here”  action for admin when the is no context - in public and subscription feeds

**Comment by andreyasko** [comment]
Additionally, ensure that only the Admins or Owners of the context can pin a post to the context timeline. So that group members couldn't simply pin their posts to a group.

**Comment by andreyasko** [comment]
Add "pinned" icon to the Feed posts pinned for all by admin.
