### ISSUE TITLE
Troubles in changing the type of the fields "date" and "datetime"

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#1464]
The example - if admin tries to change the type of the field "Birthday" in the "Persons" app ("Add person" form) from the "date" to the available "date time" and press "Save" button - he will be redirected to the URL like 
[UNA's URL]grid.php?o=sys_studio_forms_fields&a=edit&object=bx_person&display=bx_person_add&di_id=67
The same way is watched with the attempt to change "date time" type on "date"

**Comment by AlexTr** [comment]
it maybe the following ticker is related to this issue https://github.com/unaio/una/issues/1411
