### ISSUE TITLE
Delayed Video publishing, Live-transcoding

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#1465]
In current implementation when Video is uploaded it posts to timeline and everyone can see the card with unprocessed video. It can take up to an hour to process some videos, so this is unacceptable.

You can use different terminology in accordance with the current implementation of delayed posting, for example instead of `processing`, `awaiting` status can be used.

- [x] add alert when transcoding is completed
- [x] add `processing` and `failed` options to `status` field
- [x]  If video/audio is attached, set `status` value to `processing` and call alert - `{module} - deferred` instead of `{module} - added`
- [x] As soon as transcoding is done (catch alert - `{transcoder_object} - transcoded` for 480p resolution) set `status` value to `active` or `failed` (if no more videos are pending processing for given content) and call alert about added content - `{module} - added` (if `publish at` field is in past, and `status` is `active`)
- [x] don't allow to change `status` field if it's `processing` or `failed`  (or `awaiting`) in manage grid for regular user
- [x]  don't change status during post editing
- [x] if post with `failed` status is edited, then change status to `active` (it's supposed that author deleted or did something with failed video)

**Comment by AntonLV** [comment]
> If video/audio is attached, set status value to processing and call alert - {module} - deferred instead of {module} - added

**awaiting** status with **scheduled** alert are used instead of  **processing** and **deferred** because they were already used in Posts module previously.

**Comment by AntonLV** [comment]
> catch alert - {transcoder_object} - transcoded for 480p resolution

Both alerts (for  480p and 720p resolutions) are caching now. If it's critical the last one can be disabled.

**Comment by AntonLV** [comment]
**scheduled** alert was changed to **deferred** one because it fits better.
