### ISSUE TITLE
Payments: subscriptions page enhancements

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1469]
page - `page/payment-sbs-list-all`

- [x] 1) add ability to search for user's email on "all subscriptions" page
- [x] 2) display expiration date in subscription info popup for admin and for user
- [x] 3) it's not clear what is `Date` field in the grid, please rename it to make it more clear for admin and for user

**Comment by AntonLV** [comment]
RE point №2: Subscription doesn't have 'expiration date'. Currently we have License expiration date in Market module or Membership Level expiration date in Paid Levels module. Subscription itself will be active until it's canceled.

**Comment by AntonLV** [comment]
RE point №2: Link 'Order ID' from 'View Subscription' popup to the License(s) in associated module.
