### ISSUE TITLE
Timeline: switching to "update" tab in united post form breaks it

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1477]
With the following error:

```
Uncaught ReferenceError: BxTimelinePost is not defined
```

It happens when there is no Timeline/Outline on the page.

**Comment by AlexTr** [comment]
Similar to this but with polls - https://una.io/page/view-discussion?id=1127

**Comment by AntonLV** [comment]
The issue with Polls module was fixed here: https://github.com/unaio/una/commit/4bfade8110657cd3e453449030374acc5bb90a3f
