### ISSUE TITLE
Invitations: when submitting invitation form, timeline post update form is submitted

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1509]
https://una.io/page.php?i=item&id=3493

**Comment by AntonLV** [comment]
Note: The same issue appears if "invitation form" is added on any Create Content page like Create a Post from Posts module. It appears because 'do_submit' is a standard name for Submit button in the most part of forms in UNA engine.

**Comment by AntonLV** [comment]
The same fix (changes) should be applied to Invitations: Invite form and Contact: Contact Us form because they can be used on complex pages with another form(s) with a high probability.
