### ISSUE TITLE
Copyright popup is showing not translated lang key on homepage.

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1564]
Messenger overwrites aDolLang JS variable.

https://una.io/page/view-discussion?id=1036

![image](https://user-images.githubusercontent.com/3324866/45259508-fe60ca80-b411-11e8-8f57-96d77b4d0d12.png)

**Comment by AlexeyUna** [comment]
Fixed https://github.com/unaio/jot-client-una/commit/4738d1a7c1a18a2fd9163fb21bdd1aa0f7150ce2
