### ISSUE TITLE
Actions buttons problems

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1621]
- [x] buttons are overlapping on mobiles
![51454profile](https://user-images.githubusercontent.com/3324866/46110715-e964a380-c227-11e8-8063-640b8b64aedc.png)

- [x] when "more" item is clicked it should display buttons as vertical list of actions with names
![screen shot 2018-09-27 at 7 38 11 am](https://user-images.githubusercontent.com/3324866/46111033-d9998f00-c228-11e8-9532-c5fea05b8893.png)

- [x] on mobile only "more" icon should be always displayed

**Comment by AntonLV** [comment]
I think, task №3 isn't needed when buttons' titles are displayed as before and controlled via standard Navigation builder.
