### ISSUE TITLE
Posts: allow to post any type of content (similar to post to Timeline)

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1630]
T.9485860
T.10561963
T.10116016
T.10367827
T.10903523

Along with standard buttons fir image, video, audio, link, we need basic poll functionality as well.

**Comment by AntonLV** [comment]
Timeline: Combine photos and videos into one swipe frame. Also if multiple polls combine them into their own one swipe frame.

**Comment by AntonLV** [comment]
Add possibility to atach Files.

**Comment by romanlesnikov** [comment]
Also fix arrows
![image](https://user-images.githubusercontent.com/12896257/54201767-8918a400-44df-11e9-9061-a35e6b5b6e19.png)

**Comment by AntonLV** [comment]
Do the following in the next update script:
1. Execute MySQL query:
```
RENAME TABLE  `bx_posts_files` TO  `bx_posts_covers`;

UPDATE `sys_objects_storage` SET `object`='bx_posts_covers', `table_files`='bx_posts_covers' WHERE `object`='bx_posts_files';
UPDATE `sys_storage_deletions` SET `object`='bx_posts_covers' WHERE `object`='bx_posts_files';
UPDATE `sys_storage_ghosts` SET `object`='bx_posts_covers' WHERE `object`='bx_posts_files';

UPDATE `sys_objects_transcoder` SET `source_params`='a:1:{s:6:"object";s:15:"bx_posts_covers";}' WHERE `object`='bx_posts_preview';
UPDATE `sys_objects_transcoder` SET `source_params`='a:1:{s:6:"object";s:15:"bx_posts_covers";}' WHERE `object`='bx_posts_gallery';
UPDATE `sys_objects_transcoder` SET `source_params`='a:1:{s:6:"object";s:15:"bx_posts_covers";}' WHERE `object`='bx_posts_cover';
```

2. There are special alerts for storage, so we need to remove old alerts and add new, this alerts are registered during module install or enable, using info in install/config.php file.

3. Rename **storage/bx_posts_files** folder to **storage/bx_posts_covers** , make sure that remote storage folder is renamed correctly as well.

**Comment by AntonLV** [comment]
RE: Update instructions.
Point №1 was added in update script.

**Comment by AntonLV** [comment]
RE: Update instructions.
Points №2 and №3  were added too.
