### ISSUE TITLE
UNA: Posts & Discussions

### ISSUE THREAD

**Issue by launch3** [unacms/UNA#1654]
Latest UNA release candidate: downloaded & installed **Posts** (9.0.10) & **Discussions** (9.0.9). Looks like a language file is missing for both apps/modules. Attached image...
![una-posts-discussions](https://user-images.githubusercontent.com/13964338/46383901-cea78a00-c680-11e8-8e30-9d6d2550a0e0.jpg)

**Comment by AlexTr** [comment]
It looks like English language module wasn't updated to the latest version.
