### ISSUE TITLE
Views: count impressions as well (including impressions in Timeline)

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1658]
T.10363587
M.600388

Extend 'views' functionality to count impressions - each time page is refreshed or item appears in timeline, impression must be increased, no need for unique checking, etc.

**Comment by AntonLV** [comment]
To disable so called `unique checking` the `period` parameter in Views object (record in **sys_objects_view** table) should be set to 0. In this case every item loading will be calculated as new **view**.
