### ISSUE TITLE
Email/push queue: duplicate items

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1664]
Now after all emails are sent, then these emails are deleted, as the result next cron is run while first one is still in works, as the result if email sending take 9  minutes, 9 crons are run (every minute) and users will receive 9 emails.
I think that 2 measures needed to make sure it will no happen in the future:

- [x] make sure that email is deleted from queue right after email is sent
- [x] don't allow next mass mail (or push) cron to run while previous is still in works

**Comment by Elshara** [comment]
Or, allow email Queue to be handled via Kurl.

**Comment by Elshara** [comment]
On some hosts, Cron times out. Curl would better implement a job
queueing system especially where Mailings are concerned.
I've had better luck with mailing jobs processed via Curl on the same
server they were being processed with Cron. Wget is also an option as
is javascript.
Socket and Fork are available also.
Here's proof they work.
https://demo.socialengine.com/admin/tasks/settings
