### ISSUE TITLE
Don't use AJAX search results on extended search results pages

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1737]
Make sure that other functionality isn't affected.

https://una.io/page/view-discussion?id=1103

**Comment by AlexTr** [comment]
@AntonLV please enable regular paginate for the main blocks on the pages like these:
```
page/persons-active
page/persons-online
```

**Comment by AntonLV** [comment]
The changes should be applied to all Profile based modules, including Group based.

**Comment by AntonLV** [comment]
Core changes were enough to update Top Events/Groups/Spaces.
