### ISSUE TITLE
Polls: incorrect blocks on poll view page

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1813]
"Answers" block - works ok
"Description" block - for some reason it displays description + answers
--------
- [x] "Description" block must display description only 
- [x] if combined block (description + answer) is needed then it should be named "poll" and also it must have menu to switch to results (if allowed) similar to "Answers" block

**Comment by AntonLV** [comment]
Yes, we needed combined content: description + answers. Therefore "Description" block was updated.
