### ISSUE TITLE
ACL: `QuotaSize` and `QuotaMaxFileSize` accept only values not more than 2Gb

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1820]
https://una.io/cmts.php?sys=bx_forum&id=1790&cmt_id=7384

- [x] Fix size field for Messenger tables

1. bx_messenger_files
2. bx_messenger_photos_resized
3. bx_messenger_videos_processed
4. bx_messenger_mp3_processed

**Comment by AlexeyUna** [comment]
https://github.com/unaio/jot-client-una/commit/a109ef44d2f55436cdaeda10442ef48de58774b5
