### ISSUE TITLE
Remove encoding to .webm format

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1852]
Remove encoding to .webm format, instead add one more size for mp4 - 720p, how we have 480p only.

https://una.io/cmts.php?sys=bx_forum&id=1627&cmt_id=7615

**Make sure that .webm files are deleted during update. Add to deletion queue. **

**Comment by TsGenesis** [comment]
This is important.

**Comment by andreyasko** [comment]
Remove webm completely.

**Comment by AlexTr** [comment]
it's better leave it open to not forget to delete .webm files during update - add to deletion queue.
