### ISSUE TITLE
Timeline: edit timeline post isn't working

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1895]
https://una.io/page/view-discussion?id=2064
It can be reproduced on una.io

**Comment by AntonLV** [comment]
The problem appears only when both Timeline and Outline blocks are available on the same page, like we have it on UNA.IO now.
![default](https://user-images.githubusercontent.com/3894360/50724291-17496600-10fc-11e9-8bac-03479b34593b.png)
