### ISSUE TITLE
Relationship functionality

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1907]
T.11545032

Make it possible to point relationship with any profile on the site (like husband, wife, mother). It should be one way relationship with confirmation, so for example I point my wife's profile as wife, she confirm this relationship and she is shown in my profile as my wife, but I don't appear on her profile as husband, she has to make separate request and point me as her husband and after I confirm this relationship, I will be shown in her profile as husband.

Allow to change list of possible relationships in Studio, since different sites can use it for different purposes, for example to list co-workers instead of family members. 

It would be great to set list as pair of values to autosuggest back relationship, example of pair: wife - husband

**Comment by AntonLV** [comment]
Account Notifications menu for logged in Person profile may have Relations (Friends) link associated with Organizations profile. It causes 'Page was not found' error.
