### ISSUE TITLE
Events (and maybe other Group based modules) improvements

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1908]
T. 11578285

- [x] consider removing avatar and leave only cover image - https://una.io/page/view-discussion?id=2119

**Comment by andreyasko** [comment]
Update designs for cards and pages for Events and groups. Remove avatars, use member/attendants lists instead.

**Comment by andreyasko** [comment]
On display don't show avatar in **cards** and **profile** if an avatar is not uploaded.
By default make avatar field disabled on Events/Groups/Spaces/Channels, but enabled on People/Orgs. (discuss details)

**Comment by AntonLV** [comment]
Don't update Picture field in the next update scripts because it may be already customized by site owners.

**Comment by AntonLV** [comment]
Picture field wasn't changed in update scripts.
