### ISSUE TITLE
Timeline: repost into different context

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1931]
It would be great to have some way to repost post into one or more group/event/etc . 

https://una.io/page/item?id=5827

https://una.io/page/view-discussion?id=6579

m. 802153

**Comment by Rigal777** [comment]
Hello guys what can we do to speed up the process on having this feature? It's been two years. I would like for my members to share videos, news articles, and photos within una platform by just using the share button off the feed like Facebook. If I need to pay to have it sooner that later please give me a quote my site is truvoiz.com a social media network like Facebook.

**Comment by Rigal777** [comment]
@AntonLV

**Comment by AlexTr** [comment]
@Rigal777 could you please contact us https://una.io/page/contact, add link to this ticket in the message and specify that you want to sponsor this development.
