### ISSUE TITLE
Splash page: Looks broken on IOS, there is no login/join part at the bottom

### ISSUE THREAD

**Issue by AlexeyUna** [unacms/UNA#1944]

**Comment by kreativmind** [comment]
There are also large gaps of whitespace between slide images and doesn't function smoothly like desktop version.

**Comment by timburleigh** [comment]
Any updates on this?

**Comment by timburleigh** [comment]
It doesn’t seem to be fixed.

**Comment by andreyasko** [comment]
@timburleigh did you check on https://ci.una.io/test ?

**Comment by timburleigh** [comment]
I just checked. The splash page isn’t activated on that site so I can’t check. So the fix is not in an update yet?

**Comment by andreyasko** [comment]
Ouch! My mistake - mixed this up with homepage cover. Splash issues are simple HTML/CSS updates, but still need attention from @AlexTr
