### ISSUE TITLE
wrong db_pass  value for select via bilder

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#1951]
When create field as on image
![image](https://user-images.githubusercontent.com/12896257/52327922-e4e29f80-29fe-11e9-8492-d38989ec3eb6.png)
db_pass  value = `set ` instead of `xss`
and errors given
Notice: Array to string conversion in /var/www/unaio_al.me/template/scripts/BxBaseFormView.php on line 1234
in

```
function _isSelected ($sValue, $sCurValue)
    {
        return ((string)$sValue === (string)$sCurValue);
    }
```

**Comment by AntonLV** [comment]
Cannot reproduce on current version.
Checked in common Studio builder and builder in Developer app.
