### ISSUE TITLE
Profile switch doesn't work when permalinks are off

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#1975]
https://una.io/page/view-discussion?id=2340

**Comment by cbagdatli** [comment]
As this is a basic functionality it will be very nice if you may publish the fix here without waiting a new version.

**Comment by AlexTr** [comment]
@cbagdatli fixed in another issue - https://github.com/unaio/una/issues/2032

**Comment by cbagdatli** [comment]
@AlexTr  Yes but I guess this fix is related to the permalinks on status.
It is already updated in our file BxDolPermalinks.php and only works when permalinks are ON.
when permalinks are off still it is not adding the parameters to the end of the link.

**Comment by AlexTr** [comment]
@cbagdatli maybe fix wasn't correctly applied, I've tested profiles switching when permalinks are off and it works just fine now.

**Comment by cbagdatli** [comment]
yes it was not applied :)
Now it works properly thanks a lot
@AlexTr

**Comment by cbagdatli** [comment]
yes it was not applied :)
Now it works properly thanks a lot
@al
