### ISSUE TITLE
Question. PostToFeed. Are those 2 error messages ok when link is not provided?

### ISSUE THREAD

**Issue by av2012** [unacms/UNA#1987]
Hi,

I just was doing a UI negative automation test in Post To Feed form and when I have not specified the link url, pressed the "Add" button and received 2 error messages

![image](https://user-images.githubusercontent.com/34913405/53608546-546f3780-3c17-11e9-9026-3645e121934f.png)

It seems to me the second one looks strange and it seems it is better to remove it.

**Comment by AlexTr** [comment]
Second message is ok, usually it's useful in long forms only, but since forms are universal it's showed in such forms as well.
