### ISSUE TITLE
INSTALLATION DECISION

### ISSUE THREAD

**Issue by lucipherM** [unacms/UNA#1989]
Please i want to start a social network community but I don't have the funds to acquire  the una or the boonex dolphin pro platform and i really need the core features, what should  i do?

**Comment by AlexTr** [comment]
@lucipherM UNA core is free and many most important modules are free as well, you can use it as long as you need. You need to may for additional paid modules only.
It's better to ask questions in forum:
https://una.io/page/discussions-home
