### ISSUE TITLE
Facebook Connect: make facebook connect to be blue button since it's required by their requirements

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2008]
https://una.io/page/view-discussion?id=2412

- [x] Add class attribute generated from `Name` field from `sys_objects_auths` table to the button element.
- [x] Add `style` field to `sys_objects_auths` table with serialized array of CSS styles, use `BxDolTemplate::addCssStyle` to add the styles when buttons are generated (use class defined in previous step).
- [x] update existing social logins to change buttons background color and icon if needed (refer to Andrew's screenshot for the sample look of how it should look like)
- [x]  change button text from "XXX Connect" to "Login with XXX" as on Andrew's screenshot, and remove uppercase css style.

**Comment by andreyasko** [comment]
![image](https://user-images.githubusercontent.com/22210428/58772125-e9a91000-85fa-11e9-8ab3-cc8889ddeb79.png)
Use this style for all social logins.
