### ISSUE TITLE
RSS feeds aren't checked for privacy

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2014]
https://una.io/page/view-discussion?id=2481

**Comment by andreyasko** [comment]
Only enable RSS for public content.

**Comment by andreyasko** [comment]
Check each item for privacy in RSS

**Comment by AntonLV** [comment]
1. RSS feeds in content modules check privacy:
http://your_domain.com/m/posts/rss/popular
http://your_domain.com/m/photos/rss/popular
etc

**Comment by AntonLV** [comment]
2. Fixed in Timeline.
