### ISSUE TITLE
Notifications: fine tuning

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2041]
- [x] 1. disable notifications when actions is added programatically and not as direct user action. for example upon friend request we perform auto-follow - don't send notifications for auto-follow
- [x] 2. when you accept friend request, then just after accepting friend request you receives notification about new friend - this isn't needed (but user on other side should receive notification that their request is accepted)
- [x] 3. add notification about friend request (if it doesn't exists)
- [x] 4. when user is online or in messenger and receive onsite notification, then don't send push & email notification, to realise I would suggest to add 2 minute delay for notifications queue, so if user read site notification within 2 minutes then delete this notification from queue.
- [x] 5. there are still empty on site notification sometimes, when popup with username and colon appears - "User:"

**Comment by AntonLV** [comment]
Point №5 will be done in Ticket #2059
