### ISSUE TITLE
Strange screen after password change

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2052]
![image](https://user-images.githubusercontent.com/3324866/55680707-82efd900-5960-11e9-81b8-68109fa1118c.png)

It happens on una.io only, in bx_market_api module:

```php

    protected function _processAccountLogin($oAlert)
    {
        bx_require_authentication(); // most probably because of this line

```

**Comment by AntonLV** [comment]
Commits: 59abd1b1 and 521df15

**Comment by AntonLV** [comment]
Additional commit in Market API repository.
