### ISSUE TITLE
Convos: conversation deletion problem

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2055]
https://una.io/page/view-discussion?id=2664

When author of the conversation deletes conversation, then he is removed from the list of participants, but author is still shown as conversation's author. 

Possible solutions to consider are in comments.
Please vote for your preferred solution via reaction.

Also consider different behaviour based on some option.

**Comment by AlexTr** [comment]
1) if author deletes conversation, then we need to unset author for conversation, as the result author will be shown as Anonymous for other participants in the conversation

**Comment by AlexTr** [comment]
2) if author deletes conversation, then delete it for everyone else

**Comment by AlexTr** [comment]
3) if some reply is added to the conversation, add author back to participants list and display it in their inbox, as it wasn't deleted

**Comment by Baloo7super** [comment]
It seems to me that an answer must ALWAYS be possible in all cases and if I understand correctly, only the solution 3 allows it.

**Comment by AlexTr** [comment]
Option 3 was implemented
