### ISSUE TITLE
About security: shell execution

### ISSUE THREAD

**Issue by DefinitlyEvil** [unacms/UNA#2083]
Hello community,
I'm new to UNA and I'd love to install it for my community. But it requires several high-risk functions (eg. executing shell commands), so is it possible to disable those features and not not allow command executions?

Thanks,
Tobias.

**Comment by pdporemba** [comment]
I have a feeling you know this but...

To disable a function, use a text editor to modify the disable_functions directive in the php.ini file. This directive takes a comma-delimited list. For example, to disable the exec and system functions, use the following directive:

disable_functions = "exec, system"

Could you provide more information on what you have found?

**Comment by AlexTr** [comment]
@DefinitlyEvil without shell commands executing enabled some functions will not work properly, for example video conversion.

**Comment by AlexTr** [comment]
@DefinitlyEvil please post questions in forum next time: https://una.io/page/discussions-home

**Comment by DefinitlyEvil** [comment]
Ah I'm so sorry that I didn't notice there's a forum... but thanks! :D

**Comment by DefinitlyEvil** [comment]
@pdporemba I know but I don't want to allow these dangerous functions... xD
