### ISSUE TITLE
Ads module

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2103]

**Comment by AntonLV** [comment]
Related commits: 319a917, b8bd169

**Comment by AntonLV** [comment]
Changes added is a5da154 commit:
1) If ad add form has error in some mandatory field then Category field become empty and you can't change it
2) Add price into snippet meta info menu, if price field is zero or empty then display "Free", if possible display it in green colour
3) Category and price should be displayed in Timeline as well
4) Categories page (/page/ads-categories) should display all adds when no category is selected
5) Add pruning setting, default is 30 days, after 30 days, ad should become inactive and shouldn't displayed anywhere except for the author on some special, however user should be able to activate it again, or active it automatically upon ad edit. I think user's status field can be used for this.
6) For other users it should be "I'm interested" button which will send email with details of buyer to seller.
