### ISSUE TITLE
Dev app error

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2118]
When open the email field in the create account form  for editing and save it, (even without any changes), the value of the checker_func field becomes equal to empty string.
Surely this is repeated with other fields where there is a custom check present in checker_func .

![image](https://user-images.githubusercontent.com/12896257/58018554-d3378a80-7b0b-11e9-8540-765332db8bc1.png)

**Comment by AntonLV** [comment]
The same issue appears in default Studio Forms builder.
