### ISSUE TITLE
Online.me Links Page/... always 404 error

### ISSUE THREAD

**Issue by AmineBAIK1** [unacms/UNA#2143]
Hello, 
I've recently installed Una on AWS EC2 Server.. Installation went fine but when i try to acces the links on the site, i got 404 error every time with folder page/***.php. Why? this folder is not even in my Webserver after the installation.

**Comment by AlexTr** [comment]
Hello,
It's because URL rewrite rules aren't working, you can enable mod_rewrite in your Apache and check if .htaccess exists in UNA root folder.
Also you can disable URL rewrite completely by going to your site Studio (/studio/) 👉 Settings 👉 Permalinks 👉  Uncheck all checkboxes there and then Save.

Please post questions in forum next time:
https://una.io/page/discussions-home

**Comment by AmineBAIK1** [comment]
![Capture d’écran de 2019-06-14 18-18-56](https://user-images.githubusercontent.com/46829598/59524016-139fe380-8ed3-11e9-9311-a6f3832d47ad.jpg)
![Capture d’écran de 2019-06-14 18-19-05](https://user-images.githubusercontent.com/46829598/59524020-18649780-8ed3-11e9-8a64-cdbd774b50a1.jpg)
![Capture d’écran de 2019-06-14 18-19-48](https://user-images.githubusercontent.com/46829598/59524027-1ac6f180-8ed3-11e9-9dd5-a5afd98e6782.jpg)
![Capture d’écran de 2019-06-14 18-20-14](https://user-images.githubusercontent.com/46829598/59524030-1ef30f00-8ed3-11e9-9f1a-61879f9fba43.jpg)
![Capture d’écran de 2019-06-14 18-20-22](https://user-images.githubusercontent.com/46829598/59524039-24e8f000-8ed3-11e9-9464-5c9f944725ce.jpg)
It still not working !!!

**Comment by AlexTr** [comment]
You have incorrect .htaccess file, default is
```

Options -MultiViews -Indexes

<IfModule mod_php5.c>
    php_flag allow_url_include Off
    php_flag register_globals Off
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^m/(.*)$  modules/index.php?r=$1 [QSA,L]
    RewriteRule ^page/(.*)$  page.php?i=$1 [QSA,L]
    RewriteRule ^s/([a-zA-Z0-9_]+)/([a-zA-Z0-9\.]+)  storage.php?o=$1&f=$2   [QSA,L]
</IfModule>

AddType image/svg+xml svg

```

**Comment by AlexTr** [comment]
Please post questions in forum next time:
https://una.io/page/discussions-home
