### ISSUE TITLE
Notify author when post is published in case of video transcoding

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2148]
Send notification (via Notifications module) to author when post is published if post publishing is delayed for more than 1 hour because video transcoding.

**Comment by AntonLV** [comment]
During the next update the following modules should update relations with Notifications module:
1. Ads;
2. Posts;
3. Timeline;
4. Videos.

In 'install' parameter should be set:
```
'update_relations' => 1,
```
The following section should be added
```
    'relations' => array(
    	'bx_notifications'
    )
```
