### ISSUE TITLE
CSS not found

### ISSUE THREAD

**Issue by flth** [unacms/UNA#2151]
after confirmin email this popped up (Protean template)

Warning: file_get_contents(//view.css): failed to open stream: No such file or directory in /var/www/vhosts/tld.com/httpdocs/inc/classes/BxDolTemplate.php on line 1882

Edit: happens in all profiles

**Comment by AlexTr** [comment]
@flth could you please specify UNA version you are using ?

**Comment by flth** [comment]
@AlexTr sorry, sure. Current checkout from Git, it shows 9.0.0-DEV19 in Studio, but it's the current branch

**Comment by AntonLV** [comment]
Hello @flth, we cannot reproduce the issue on our fresh demo installation (https://ci.una.io/test) which has the most resent version from Git. Could you please try to reproduce it there or describe step by step what you did on your own site to get the problem. Is it still reprodusable on your site? If so, we can try to investigate it there if you provide us with the access info.

**Comment by flth** [comment]
So a bit further testing... it seems to happen when Cache is enabled, without cache I don't see a message. If cache is enabled it shows it directly after cache is cleared and profile page (view-persons-profile?id=xxx) is reloaded. Strangely it only shows it in Chrome but not in Firefox. 

Caches are disable at the moment, can provide you access in private message

**Comment by AlexTr** [comment]
@flth thank you for testing, could you please provide access in private message on una.io, my profile there:
https://una.io/page/view-persons-profile?id=2

**Comment by flth** [comment]
sorry for late reply, I've installed B1 again and it seems gone now. So issue closed

**Comment by AlexTr** [comment]
thank you @flth for letting know
