### ISSUE TITLE
UNA.io

### ISSUE THREAD

**Issue by AmineBAIK1** [unacms/UNA#2158]
Hello,
In your site una.io when we choose lucid skin ! the signup button layout is broken.

**Comment by lucipherM** [comment]
That error occurs on the una.io site only but other sites have the error fixed, so it would not likely affect the una10 update.

**Comment by joblux** [comment]
when is the UNA 10 stable for ?

**Comment by joblux** [comment]
you mean you let the error occur on una.io ? without fixing it ?

**Comment by AlexTr** [comment]
@Amine Could you please provide screenshot of the broken layout if the issue is still in place ?
