### ISSUE TITLE
Email link to comment 

### ISSUE THREAD

**Issue by joblux** [unacms/UNA#2162]
When i receive an email of a reply to a comment, why its taking to a page where the comment is isolated from the rest of the conversation ...removing it out if its context ...when it should take to the whole feed and target the section where the comment is ... thats definitely a navigation user enhancement to take in consideration ...

**Comment by AlexTr** [comment]
Please post bug reports only here, if you need to discuss something please post in forum:
https://una.io/page/discussions-home
