### ISSUE TITLE
update failed? module install from appstore fail to install

### ISSUE THREAD

**Issue by jmrenquist** [unacms/UNA#2165]
Just installed Una 9.0.0 via softaculous on linux selfhosted server TMDhosting. Then applied Una.io key and secret.
Downloaded core modules. Then attempt to install modules and fail saying version mismatch.
Went to Dashboard and saw version update to beta 10. Clicked on update, said will update in one minute but doesnt appear to update.
This worked on una installs until about 24-48 hrs ago no problem then once beta 10 put in dashboard as available, modules from app store will not install on verions 9.0.0 or 9.0.1

What is the fix for this? This is an urgent issue. for ANY and ALL new users.
Is this also happening for UNA CLOUD hosting customers?
Help!

**Comment by AlexTr** [comment]
Please follow manual instructions on how to upgrade to UNA v.10 in this post:
https://una.io/page/view-post?id=241
