### ISSUE TITLE
Files copying failed

### ISSUE THREAD

**Issue by zamtime** [unacms/UNA#2177]
--------- 2019-07-01T01:21:03+00:00
9.0.0-9.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed

--------- 2019-07-01T01:22:01+00:00
9.0.0-9.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed

--------- 2019-07-01T01:25:04+00:00
9.0.0-9.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed

--------- 2019-07-01T01:30:04+00:00
9.0.0-9.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed

--------- 2019-07-01T02:37:02+00:00
9.0.0-9.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed

--------- 2019-07-01T02:44:02+00:00
9.0.0-9.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed

--------- 2019-07-01T03:01:16+00:00
9.0.0-9.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed

**Comment by AlexTr** [comment]
@zamtime could you please specify your OS and the directory your site is located in ?

**Comment by zamtime** [comment]
I figured out what this was, the auto installer i used through cpanel added can extra / to the path. Which was causing the updater to fail.

eg.

/public_html/network//test/

It wasn't a una bug, but perhaps you can add a check for this and include it in the error? It was such a simple thing, but it took me ages to work out what was going on...

**Comment by AlexTr** [comment]
Thank you for the feedback, could you please specify where double slash was added ? is it in inc/header.inc.php file ?

**Comment by zamtime** [comment]
Yes, it was in all the path related variables in header.inc.php

**Comment by AlexTr** [comment]
Thank you for letting us know
