### ISSUE TITLE
Missing language translations in modules for English lang

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2196]
If Russian language is added in the beginning as default and later English language is installed then all modules language keys aren't translated to English
https://una.io/page/view-discussion?id=3255

**Comment by AntonLV** [comment]
The issue isn't only with auto-generated keys, but with all keys related to modules. I think it's not a bug. Current version of English App contains system language file only while modules' languages are in the modules themselves. It's the reason of the problem. When English language is installed as second language, it installs everything it has - system language file only. So, we have to ways:
1. Create English app the same as Russian, that it has all language files: system + modules.
2. Develop a mechanism which will search for appropriate language files in modules during Language App installation.

**Comment by AlexTr** [comment]
@AntonLV I think we need to implement option 2 - Develop a mechanism which will search for appropriate language files in modules if it's missing in module during Language App installation.
