### ISSUE TITLE
Issue with BxDolModuleProxy and Js/Css inclusion.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#2204]
addJsCss doesn't work correctly via aMethodsToCallAddJsCss array. Issue appears in dynamic calls. To reproduce the issue do the following:
1. Add photo via Photos module.
2. Log out.
3. Go to Photos Home page.
4. Click with photo to see the preview popup.
5. Check author's thumbnail in Author block.
![изображение](https://user-images.githubusercontent.com/3894360/60861256-7c545480-a222-11e9-8efa-3157075238f5.png)

**Comment by AlexTr** [comment]
https://github.com/unaio/una/issues/2207
