### ISSUE TITLE
AWS S3 

### ISSUE THREAD

**Issue by AmineBAIK1** [unacms/UNA#2237]
Hello, 
In Studio -> Settings -> Storage
I've added my S3 With my Id and secretkey and s3 bucket and with and without aws custom domain i put the url of my cloudfront. 
When i add a picture in still pointing to local storage when it supposed to point to my mycloufrond and s3 bucket.. 
I used the same settings id key and other with an other site in the admin and it works. 
Can you explain to me please how it works? and whats exactly the aws custom domain ?

**Comment by AlexTr** [comment]
Please refer to this FAQ:
https://github.com/unaio/una/wiki/FAQ#12-how-configure-amazon-s3-storage-
