### ISSUE TITLE
Studio Polyglot just searches in current language

### ISSUE THREAD

**Issue by flth** [unacms/UNA#2242]
Not sure if it's intended for performance sake or something, but polygot app in Studio just searches in strings of the current site language.
Example: having a bi-lingual site with englisch (default) and german. If I am searching for something that just is inside the german translation (e.g. had a typo in german like "E-Maiks" instead "E-Mails") the search doesn't return a result if site language is set to english. Have to leave Studio, go to frontend, switch site language to german, return to Studio, return to polyglott, typing in again the same search term and something is found.

Maybe search all languages or make searched languages available in polyglott app?

**Comment by AlexTr** [comment]
It can search search in current language only, but we'll add switch language link in Studio, so it will be much easier to switch to another language and search:
https://github.com/unaio/una/issues/2244
