### ISSUE TITLE
Profile based modules: add new privacy field "Who can contact me"

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2252]
Add appropriate method `allowContact` as well, then use this fields in the following modules:

- [ ] messenger
- [x] conversations

**Comment by AntonLV** [comment]
The last 2 commits were added in this ticket by mistake. Changes related to Ticket #2410.

**Comment by AlexTr** [comment]
@AntonLV some fix is needed:
![Sélection_423](https://user-images.githubusercontent.com/3324866/73406780-5f60a980-434b-11ea-9184-61dd51a1db5b.png)
