### ISSUE TITLE
Messenger Permissions - receiving

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#2255]
Add an action to the Messenger permissions like "Send messages to Friends" which would be turned on by default and the action "Send messages to anyone" would be only available for admins and moderators by default. 

Also, we will add a setting for users to be able to  "Receive messages from: anyone / friends only / relationship-group X..." - https://github.com/unaio/una/issues/2252

https://una.io/page/view-discussion?id=3476

---------

I think it would be better to add "Who can contact me" privacy to Persons and Orgs modules, this will affect Messenger, Convos and maybe some 3rd-party modules - https://github.com/unaio/una/issues/2252

**Comment by GarySicard** [comment]
Keeps getting better
