### ISSUE TITLE
Wrong css  styles in Ocean template 

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2266]
1. 

/page/edit-persons-profile?id=3
![image](https://user-images.githubusercontent.com/12896257/62190144-503b7780-b379-11e9-9bac-a385866e491b.png)

2. 

![image](https://user-images.githubusercontent.com/12896257/62351738-143a1b00-b50f-11e9-920b-58f783cd4917.png)
![image](https://user-images.githubusercontent.com/12896257/62351767-23b96400-b50f-11e9-9148-60f5c1e36165.png)
![image](https://user-images.githubusercontent.com/12896257/62351783-3469da00-b50f-11e9-8346-e629bbda9b0c.png)

**Comment by AlexTr** [comment]
related issue https://github.com/unaio/una/issues/2274

**Comment by AntonLV** [comment]
Issue №1 was fixed in Ticket #2274

**Comment by AntonLV** [comment]
Issue №2 isn't a bug. Ocean template has partially transparent header. So, when the page is fully scrolled up and header is in its default position and it looks as it should. But when the page is scrolled down a bit, background (images, texts, etc) can be seen through the header.
