### ISSUE TITLE
Wiki Module App

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#2268]
Develop a content-type app for knowledge-base, documentation, FAQs, APIs reference, etc. with collaborative editing, media attachments, multi-level navigation, version history, comments and local search.

1. Content item name: **Article** 
2. Editing with **Markdown** - https://commonmark.org/
3. Comments to each article show on a separate sub-page named **Talk**
4. Subpages on each page are: Article / Talk / Source / History / Insights / Manage
5. **Insights** subpage shows basic article analytics KPIs - views over time, backlinks/shares/reposts, edit requests, reports.

Wiki app is similar to MediaWiki, GitHub Wiki in purpose and general architecture. It must support UNA core categories, hashtags/labels, post-to-context, and must "embeds". 

Display examples: https://docs.gitbook.com/ and https://stripe.com/docs

**Comment by AlexTr** [comment]
https://github.com/unaio/una/issues/2304
