### ISSUE TITLE
Fast search don't work on Android 

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2273]
on win
![image](https://user-images.githubusercontent.com/12896257/62352050-e1dced80-b50f-11e9-82d8-cdf380f1c0d2.png)
on android
![002](https://user-images.githubusercontent.com/12896257/62352086-f91bdb00-b50f-11e9-98be-7585083b9a48.jpg)

**Comment by AntonLV** [comment]
As I see keypress event is depricated. It's recommended to use keydown instead.
https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event
