### ISSUE TITLE
Notifications for actions with comments.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#2291]
When a user likes some comment he receives Email and Push notifications about his  own actions.

**Comment by AntonLV** [comment]
Cannot reproduce the issue on fresh installed UNA script.

**Comment by AntonLV** [comment]
UNA.IO wasn't fully updated. It caused the issue. 
'sys_cmts' record in 'sys_objects_vote' table should get a value = 'author_id' in 'TriggerFieldAuthor' field.

**Comment by AlexTr** [comment]
Add in next update:
```sql
UPDATE  `sys_objects_vote` SET  `TriggerFieldAuthor` =  'author_id' WHERE `Name` = 'sys_cmts';
```
