### ISSUE TITLE
Suggested friends privacy option isn't working sometimes

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2307]
- [ ] Because of JS error, however clearing UNA cache fixes this problem:

![image](https://user-images.githubusercontent.com/3324866/63071661-8a08a280-bf63-11e9-878e-46208f8e4210.png)

- [x] In "Create Post (Public)" block, because of JS Error:

![image](https://user-images.githubusercontent.com/3324866/63080476-833e5780-bf84-11e9-9789-e84d52ca02d4.png)

**Comment by AntonLV** [comment]
The first issue cannot be reproduced after the second one was fixed.
