### ISSUE TITLE
Interactive Links menu style is broken

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#2348]
![image](https://user-images.githubusercontent.com/22210428/64143938-aa869700-ce55-11e9-969d-61dd50936e14.png)
comes out as:
![image](https://user-images.githubusercontent.com/22210428/64143950-ba9e7680-ce55-11e9-80af-c7e9a9297d1d.png)

**Comment by AntonLV** [comment]
'Interactive Horizontal/Vertical Links' menu styles are system styles which require additional JavaScript code and therefore they cannot be used in simple menus created via Builder.
