### ISSUE TITLE
Timeline post on separate page has incorrect description

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2350]
TO reproduce make a post with link, then open post on separate page, see source:
![Screen Shot 2019-09-04 at 7 45 21 am](https://user-images.githubusercontent.com/3324866/64210971-0dc10980-cee8-11e9-90d4-a8a9b7f59169.png)

**Comment by lubaj** [comment]
Alex, the problem is not solved. I still have the same issue.

**Comment by AlexTr** [comment]
@lubaj it will be fixed in the official update in a few days
