### ISSUE TITLE
Guest / Nonauthenticated Reactions

### ISSUE THREAD

**Issue by launch3** [unacms/UNA#2364]
When guests (unauthenticated users) reaction permissions are enabled for more visitor interactions, on mouse-over you see:
"Haha" by
instead of "Haha" by guest.
Attached pic from homepage timeline.
![guests-react](https://user-images.githubusercontent.com/13964338/64622267-0a7cc080-d3b5-11e9-8087-adb7136a7ddf.jpg)
Same for Posts app.
"Like" by
instead of "Like" by guest(s).
![guests-react-post](https://user-images.githubusercontent.com/13964338/64622574-8a0a8f80-d3b5-11e9-8ca5-4e986a1115a2.jpg)

**Comment by AntonLV** [comment]
It's not an issue. This title means that by clicking the link you'll see a list of uses who reacted with 'Like', 'Haha', etc. reaction and it doesn't matter who a viewer is: a studio operator, a common member or a guest with extended rights. 
User, logged in as operator, see the same:
![изображение](https://user-images.githubusercontent.com/3894360/65010662-3817bb80-d919-11e9-892b-5b000f403198.png)
