### ISSUE TITLE
Google connect does not meet Google branding style and will be rejected on API request

### ISSUE THREAD

**Issue by punyauk** [unacms/UNA#2373]
Relates to "Google connect: use "google" icon instead of "google plus" icon #2343"

Just to re-iterate, the Google connect module is still broken and does not meet Google branding so new users will find they can not get authorization for it. This is the email Google sent me:

Dear Developer,

Thank you for submitting an OAuth App Verification request. To proceed with the verification process, please update your project queersociallogin-1xx7396x18x7 to comply with our requirements.

Please update the Google sign-in button on your project’s homepage URL so that it complies with the Google sign-in branding guidelines. Once your project is updated to reflect these requirements, please reply to this email to confirm your compliance. If you have additional questions, you can review the OAuth Application Verification FAQ or respond to this email.

**Comment by AlexTr** [comment]
Thank you, but there is already an open ticket for this:
https://github.com/unaio/una/issues/2347
