### ISSUE TITLE
polls.css not gizzepd and duplicated 

### ISSUE THREAD

**Issue by yanivz** [unacms/UNA#2376]
on timeline i have 2 posts with polls when i saw html i saw 2 files of css loaded....
<link href="https://www.sample.com/modules/boonex/posts/template/css/polls.css" rel="stylesheet" type="text/css" /><iframe class="bx-base-text-poll-embed"

**Comment by AlexTr** [comment]
Since the Timeline item with polls can be loaded after page is opened, then we need to load it each time item with poll is shown. This file should be cached and subsequent calls shouldn't slow down page load. It isn't gzipped because it's already very tiny - 56 bytes.
