### ISSUE TITLE
Group invite functionality improvement

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2379]
https://una.io/page/view-discussion?id=3905&skin=protean&mix=12

There needs to be a way to automatically add someone to a Group after they have been invited.

**Currently the process is this:**
Invite User
User receives email for invite
User clicks on link in email and goes to Group
User has to click Join Group
Admin of group has to approve User

**The process should be something like this:**
Invite User
User receives email and notification for invite
User clicks on link in email and a popup asks if they want to become a member with Yes/No.
If Yes, automatically added to Group

Also it should be a block with invited members, which haven't joined yet.

**Comment by andreyasko** [comment]
Additionally, we need to show the list of invited participants inside the group and a sepate tab for My Groups I’m Groups browsing submenu to access joined groups including secret ones.
