### ISSUE TITLE
Feature/Unfeature action should change state.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#2386]
https://una.io/page/view-discussion?id=3880

**Comment by AntonLV** [comment]
Making a further testing I found out that the problem can be reproduced only when Font Awesome Pro app is installed and enabled,  Light or Doutone icon style is selected.

**Comment by AlexTr** [comment]
When site is switched to light or duotone icons, then all icons are converted to one style, as the result some difference between solid and normal icons disappear, it's side effect of using light or duotone icons everywhere.
