### ISSUE TITLE
"Gallery view" is broken when page without header and footer is used

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2389]
With header and footer:
![image](https://user-images.githubusercontent.com/3324866/65292234-f47fb480-db99-11e9-9095-27f4d349312e.png)

Without header and footer:
![image](https://user-images.githubusercontent.com/3324866/65292259-06615780-db9a-11e9-8266-23e77109770d.png)

**Comment by AntonLV** [comment]
Looks like JS date auto converter doesn't work too.

**Comment by AntonLV** [comment]
The issue can be reproduced in UNA 9.0.0 only.
