### ISSUE TITLE
Timeline: Optimisations for Feeds and Sharing logic

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#2401]
- [x] 1. In privacy/visibility selector change “Share with...” to “Share to...”

- [x] 2. Allow sharing to only one privacy group (context/community) and strictly adhere to the rule of ONLY showing this content within the selected community, and ONLY pushing it to HOME-feeds of users that follow that specific community.

- [ ] 3. Full list of possible “Share to...” options:
**My Profile** 
Public
Friends
Only me
X,Y,Z Members
**Relationships...**
**Specific friends...**
**Groups** and other communities (spaces, events, etc.)

- [x] 4. When user A posts to their profile (public), post should appear on their profile feed and in Home feeds of people that Follow user A.

- [x] 5. When User A posts to a Group X, post should appear on the feed of the Group X. Users that follow Group X should receive this post in their Home feeds. The post should NOT appear on User A profile feed. The post should NOT appear on Home feeds of users that follow User A, unless they also follow Group X. Same applies for Spaces/Events.

- [x] 6. As with groups, if User A posts to profile feed of User B, only people who follow User B receive this post in their Home feed. 

- [ ] 7. One post can only be posted to one community. It is possible to repost to another destination (own profile, another group, etc), which would create a new timeline update (repost) with own comments and reactions, referencing original post.

- [x] 8. Separate Channel posts from the Home/News feeds and create a new feed that shows only posts from channels followed by the user. This feed can be called “News”.

Ultimately there should be 4 discovery feeds:
1. News(this is new feed which need to be added) - posts from Channels I follow
2. Home(current dashboard feed) - posts from people/orgs/groups/events/spaces (except channels) I follow and allowed to see (public, friends-only and I’m a friend, relationships and I’m a relationship, membership matches mine, my own).
3. Latest(current homepage feed) - all posts I’m allowed to see, regardless of following (except channels). All public posts for unauthenticated. 
4. Popular(current Hot feed, change sorting algo) - all posts I’m allowed to see sorted by popularity score: Reactions+Upvotes-Downvotes/time-since-first-published. 

And context specific feeds showing inside of the context (profile feeds, group feeds, etc).

### Displaying feeds

Implement ‘infinite scroll’ with max 100 updates, loaded in groups of 10 on scroll-down. Once 100 is reached, offer a “load more” button, as usual. Initial load only calls for 10 updates, next 10 loaded as soon as page-scroll down is detected (before button of the page is reached).

**Comment by antaratma** [comment]
Duvet


D
Fav
V
Gf
Do
F
F
Fi

V
Go

F
F
F
F
F
F
F
F
F
G
G
F
G
G
Gg
F
F
G
G

**Comment by AntonLV** [comment]
Replace "Jump To" with Date Picker. It will allow to select a date which posts should be loaded from.

**Comment by AntonLV** [comment]
'Empty' is shown in the timeline in the same time with items in it.
![изображение](https://user-images.githubusercontent.com/3894360/67834573-cd04fb80-faf8-11e9-9164-61efcc19caac.png)

**Comment by AntonLV** [comment]
I cannot reproduce the issue with 'Empty' message anymore neither on Dev installation nor on CI.UNA.IO site.

**Comment by AntonLV** [comment]
Points №3 and №7 were moved on the next versaion.

**Comment by AntonLV** [comment]
A part of the fix for 'Connection between Post and View blocks' is here 938755e.
