### ISSUE TITLE
Hidden discussion is still visible in the feed

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#2429]
If the initial posts marked as "hidden" by admin / moderator it is left as visible in the Timeline's feed. The guests get the "Not found" error while their attempts to click the title of this "hidden" thread. The original request is here:

https://una.io/page/view-discussion?id=3951

**Comment by AntonLV** [comment]
Note. The issue appears only when **Item Cache** is enabled in Timeline.
