### ISSUE TITLE
Timeline cards update

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#2430]
Timeline cards designs, layout and functionality update as per attached image.

1. Separate reactions stats and actions links into separate menus/lines. When there is no available actions (ie for unauthenticated user), don’t’ show actions menu and don’t’ show separating line..
2. Reactions counter shows only reactions icons that have been used. if only, say, 😀 has been used, only hose that.
3. Comments counter shows comments icons in circle and avatars of the latest 5 commenters.
4. All icons wrapped in circles for better tap-target visualisation.
5. Actions show action text along with the icon.
6. When reactions counter is clicked, show pop up listing all users and their reactions, separated into tabs: All / r1 / r2 / ...

![Cards](https://user-images.githubusercontent.com/22210428/67361389-3befcb00-f5b4-11e9-8de5-db57a560b051.png)

**Comment by AntonLV** [comment]
1. Comment and Comment counter in card should do the same (load comments).
2. The whole Reactions counter should be a link (not only a number).
3. Margin between lines (actions, counter, dividers, etc.) in card should be 1rem (now 0.5rem is used)
4. Do reaction popup: icons should have 2.0rem size.
