### ISSUE TITLE
Timeline: posts disappear sometimes

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2441]
https://una.io/page/view-discussion?id=4279

Steps to replicate:

1. log in as a normal user
2. Create a post at the public timeline
3. Visit the user profile and create a post at the profile timeline
4. Refresh the page after creation of the post at the profile feed
5. Post that was made in the public timeline should disappear from the user profile feed

**Comment by AntonLV** [comment]
Looks like the problem appears when 'Feed Cache' is enabled.
