### ISSUE TITLE
Ads: db error when Category field is searchable

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2444]
When category fields is searchable:
<img width="317" alt="Screen Shot 2019-11-07 at 9 39 20 am" src="https://user-images.githubusercontent.com/3324866/68347446-b424c780-0142-11ea-86a0-f3f85f4763a6.png">
Then db error occurred during search:
```
Unknown column 'bx_ads_entries.category_view' in 'where clause'
```

**Comment by AntonLV** [comment]
Category (`category_view`) cannot be used in common and extended searches because there is no such field in main DB table at all. It's just a field in Form.
