### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2458]
![Screenshot_6](https://user-images.githubusercontent.com/7164280/68881882-a3fa8280-0716-11ea-9aa1-b309ef9bf77b.png)
Если зайти в админку (студию)
If you go to the admin panel (studio):

Перейти в Страницы/Лента/общая хроника новостей :
Go to Pages / Timeline/Public Feed:
studio/builder_page.php?type=bx_timeline&page=bx_timeline_view_home
and fix unit block - "Public Feed" , now turn Off  block - "Public Feed" , now turn On  block - "Public Feed(Timeline)" , after all, return back and go to the main(home) site page, publication will not be displayed!
But there they were...
![Screenshot_5](https://user-images.githubusercontent.com/7164280/68881278-8547bc00-0715-11ea-99cb-ce6ffc2f7f40.png)
disappear publication, if you touch the unit on or off for example, or anything else to do with it

**Comment by AntonLV** [comment]
Hello.
I cannot reproduce the issue. I followed your instructions step by step but Timeline block with 
events didn't disappear. 
**Note**. As I see you are modifying "Public Feed" (http://unaio_site.com/page/timeline-view-home) page  but checking the results on Site Home (http://unaio_site.com/index.php) page. Blocks on one page cannot affect the behaviour of another page itself or a list of its blocks.

**Comment by lsnull** [comment]
На русском говорите ? Вас же Антон Звать ? 
У меня эта проблема как на локальном, так и на хостинге.
Сделал видео запись

https://youtu.be/geSTaS1O2nI

**Comment by lsnull** [comment]
> Hello.
> I cannot reproduce the issue. I followed your instructions step by step but Timeline block with
> events didn't disappear.
> **Note**. As I see you are modifying "Public Feed" (http://unaio_site.com/page/timeline-view-home) page but checking the results on Site Home (http://unaio_site.com/index.php) page. Blocks on one page cannot affect the behaviour of another page itself or a list of its blocks.

После того, как я скачал день назад в github Una-master этой проблемы уже нет. Я не заметил... хотя версия стаяла та же самая, видимо вы уже где то исправили проблему.

**Comment by AlexTr** [comment]
Thank you for letting us know that issue has been fixed
