### ISSUE TITLE
View Comments to guests on the site  (просмотр комментариев гостям на сайте)

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2467]
Нет возможности просматривать комментарии для гостей
There is no possibility for guests to view comments

Может я ошибаюсь и не заметил где это настраивается ?
Maybe I'm wrong, and did not see where this is configured?

![Screenshot_11](https://user-images.githubusercontent.com/7164280/69143003-a96a1b00-0ad0-11ea-9538-fbd3eaa286cf.png)

**Comment by AlexTr** [comment]
It looks like it's general question, could you please post it in forum:
https://una.io/page/discussions-home
