### ISSUE TITLE
No way to delete image from comment via edit form

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2472]
m.686623

![image](https://user-images.githubusercontent.com/12896257/69346624-2689c180-0c84-11ea-9d31-65d07b51f8e4.png)

**Comment by AntonLV** [comment]
Comment edit form doesn't allow to edit attachments. As you can see on the screen the attached image is out of the edit form (under Post button). It's displayed in attachment section of the comment itself.
