### ISSUE TITLE
Show post Timeline(feeds) add function (menu) for hidden publications from the Timeline(feeds)

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2483]
-Возможно я не заметил эту возможность в cms
-Maybe I did not see this feature in cms

-Идея в том, если скрыть публикацию из ленты событий, тогда я не могу ее вернуть обратно.
-Добавить функцию в панели пользователя со списком скрытых публикаций, для того, чтобы можно было обратно показать в ленте событий.

-The idea in that, if you hide the publication from the Timeline (event feed), then I can not get it back back.
-Add feature in user panel listing hidden posts for that could be shown back in the Timeline (event feed)
![show-post-feeds](https://user-images.githubusercontent.com/7164280/69618881-50a40080-1043-11ea-947a-ddb276b85a95.png)
![menu_hide_posts](https://user-images.githubusercontent.com/7164280/69619171-d627b080-1043-11ea-95c7-9b02bf76105a.png)

**Comment by AlexTr** [comment]
Actually post is deleted, we named it "hide" because it deletes just a reference to the post from feed, but actual post still remains in the module
