### ISSUE TITLE
install una-master 26.11.2019

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2484]
Чистая установка вызвала после перехода на сайт данную ошибку:
Clean installation caused after going to the site this error :
![null-install-una](https://user-images.githubusercontent.com/7164280/69638591-a5f00a00-1063-11ea-9caf-1fbc7a83268f.png)

Apache 7
PHP 7.2
MySQL 5.6

**Comment by AlexTr** [comment]
Thank you for the report, but it maybe intermediate issue, it shouldn't be related to UNA
