### ISSUE TITLE
new Warning! (install to release UNA-10.1.0) + modules of una-master 26.11.2019

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2485]
![1](https://user-images.githubusercontent.com/7164280/69643533-2155b980-106c-11ea-9d95-abe06369e649.png)
![2](https://user-images.githubusercontent.com/7164280/69643535-21ee5000-106c-11ea-9c0e-2cfec49e45e7.png)

-Если отключить Timeline то Предупреждения не будет 
-If you disable the Timeline Warnings will not

**Comment by lsnull** [comment]
in the \template\scripts\BxBaseMenuInteractive.php

public function getCode ()
    {
        $sCode = parent::getCode();
        **if($sCode !== false)**
            $sCode = $this->_oTemplate->parseHtmlByContent($sCode, array(
                'id' => $this->_aObject['menu_id']
            ));

        return $sCode;
    }

**Comment by AntonLV** [comment]
1. It's a bad idea to install old (even if it's the last released) version of main script and the newest DEV versions of modules.
2. Could you please test issus (bugs) on ci.una.io/test before creating an issue here.

**Comment by AntonLV** [comment]
Current version of main script already has necessary check in constructor of `BxBaseMenuInteractive` class:
```
if(empty($this->_aObject['menu_id']))
    $this->_aObject['menu_id'] = $this->_sObject;
```
