### ISSUE TITLE
One String - see more - why ?

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2487]
![one_string](https://user-images.githubusercontent.com/7164280/69664878-e6667c80-1091-11ea-9cb6-1138680c7b8a.png)
-когда пост содержит 1 или несколько строк, все равно видно кнопку see more
-when the post contains one or more rows, all the same seen button "see more"

**Comment by AntonLV** [comment]
Related ticket #2308. Unfortunately, I cannot reproduce the issue. 
![изображение](https://user-images.githubusercontent.com/3894360/69959425-31f8aa80-1518-11ea-91f4-24efeb6c54d8.png)
Could you please provide more info about how it can be reproduced? What OS and browser do you use, etc?

**Comment by testing-nerd** [comment]
I'm also seeing it on the Microsoft Edge browser.
Screen size is 24'' 1080p.
HTH.

**Comment by AlexTr** [comment]
@testing3-apps thank you for the report, but I can't reproduce this issue in latest Edge browser using Windows 10

![Screen Shot 2019-12-28 at 12 48 58](https://user-images.githubusercontent.com/3324866/71537490-1f379100-2971-11ea-968b-efc825653a91.png)
