### ISSUE TITLE
Upgrade Timeline

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2488]
![Upgrade](https://user-images.githubusercontent.com/7164280/69665600-604b3580-1093-11ea-948b-a5f7327c6eda.png)

Сильно много свободного места
Much a lot of space

Пустые места в Timeline(feed), можно заполнить поумному
Empty seats in the Timeline(feed), you can fill in smarter

И не разбрасываться пустым пространством на сайте а заполнить его контентом
And do not throw away the empty space on the site and fill it with content

**Comment by AlexTr** [comment]
You can use Outline block, then all spaces will be filled
