### ISSUE TITLE
Notifications: fixes

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2495]
- [x] 1. add possibility in Notifications module to modify message from integrated module
- [ ] 2. change this text to “xxx sent a message” no “send message”
- [ ] 3. ideally it should have “Message from XXX” in notification title and just the text of the message in the notification itself

![1659332A-4855-486D-AE1D-421BFB8D9AAB](https://user-images.githubusercontent.com/3324866/69780151-1f1f6680-11f6-11ea-8d2c-1457a0e0e214.jpeg)

**Comment by AntonLV** [comment]
1. The other changes should be made in Messenger module.
2. Take a look at BxBaseModGeneralModule::serviceGetNotificationsPost method. It has a description of how default message template, subject, content of Email/Puch notifications can be changed.
