### ISSUE TITLE
Comments glitches 

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2518]
- [x]  1. The reply should firstly appear just in place where it was posted. In another words, it should replace the Form it was created with. It should work this way in all modes (threaded, flat). Then after page reloading it may be placed in necessary position in accordance with current display mode.
https://una.io/page/view-discussion?id=4605

- [x]  2. Try to find solution to show the structured Comment + Sub comments on View Comment page.

**Comment by AntonLV** [comment]
Currently the realized mechanism is used on View Comment page only. But theoretically it can be used for all comments lists. But it should be tested first.
