### ISSUE TITLE
Notifications privacy issue

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2525]
It looks like privacy isn't checked before sending notifications.

How to reproduce:   
user A is subscribed to user B, user B makes a post with "me only" privacy and post comment there, user A receives PUSH notification about this action and upon clicking on the notification "Access denied. This is private content." appears. Actually notification shouldn't be sent if user has no rights to view it. 

Should be done:
1. Reorganize Alert registration in BxNtfsResponse::response method. Email and Push notifications shouldn't be processed immediately when Add Alert was received. New cron task should be added. Last processed notification should be saved. 
2. When notification is preparing to send, the list of recipients should be collected first and then a notification should be check in accordance with each recipient. In this case Privacy can be checked correctly.
3. Before sending a Email\Push notification it should be checked in bx_notifications_events2users table. If user already viewed the notification on Site, then Email/Push notifications aren't needed.

**Comment by AntonLV** [comment]
**Note**. During the next update the newly added '**bx_notifications_processed_event**' setting should be initialized with the last Event ID to avoid repeated notifications for all events in the '**bx_notifications_events**' table.
