### ISSUE TITLE
Keys truncated in notifications

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2535]
t.15830964
![image](https://user-images.githubusercontent.com/12896257/71957833-ccc36380-31ff-11ea-9a1d-adabe1a1028e.png)

in bx_notifications_events..content:
a:7:{s:12:"entry_sample";s:23:"_bx_timeline_txt_sample";s:9:"entry_url";s:47:"https://winci.community/page.php?i=item&id=5921";s:13:"entry_caption";s:35:"_bx_timeline_txt_sample_with_ima...";s:12:"entry_author";s:1:"0";s:15:"subentry_sample";s:39:"_bx_timeline_txt_sample_reaction_single";s:22:"subentry_sample_params";a:1:{i:0;s:34:"_sys_pre_lists_vote_reactions_like";}s:8:"lang_key";s:0:"";}

**s:35:"_bx_timeline_txt_sample_with_ima..."**

**Comment by AntonLV** [comment]
Was fixed in Ticket #2340
