### ISSUE TITLE
Timeline: comments stats visible to owner of discussion only

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2569]
![Sélection_414](https://user-images.githubusercontent.com/3324866/73131011-a43cc580-4057-11ea-8748-ea3f9746195c.png)

![Sélection_415](https://user-images.githubusercontent.com/3324866/73131012-aacb3d00-4057-11ea-844c-78464ba72cc4.png)

**Comment by AntonLV** [comment]
Issue appears because of Ticket #2539. After the changes were applied only friends can post to somebody's profile. 
Right now All comments on Timeline are checked with "Who can post to my profile" privacy setting, but only Timeline Updates should be checked.
