### ISSUE TITLE
Studio: domain isn't decoded from IDN format when displaying domain in Studio 

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2571]
Use `idn_to_utf8` php function to convert domain to readable format. Check other places too where domain is displayed. Also check if domain checking for licenses is correct for such domains.
![nice_url](https://user-images.githubusercontent.com/3324866/73132125-bd9b3d00-406a-11ea-9ea8-6bbb464b5a4b.jpg)

**Comment by dantien** [comment]
Kind of a workaround was to use the www.xn--ndelignett-05a.no url to generate the UNA key and secret.
