### ISSUE TITLE
ЧТо это ? What's this? 

### ISSUE THREAD

**Issue by lsnull** [unacms/UNA#2577]
настройки моего сервера:
my server settings:
![image](https://user-images.githubusercontent.com/7164280/73597636-9c3cc400-4536-11ea-82ea-d536505d95b0.png)

Вчера вечером скачал из github , только что решил установить и вот что получил после установки...

Yesterday evening downloaded from github, just decided to set up and that's what happened after the installation of ...

![image](https://user-images.githubusercontent.com/7164280/73597502-487dab00-4535-11ea-8b07-c2ffab3d87b9.png)

![image](https://user-images.githubusercontent.com/7164280/73597612-53850b00-4536-11ea-8ceb-734d4d57845c.png)

![image](https://user-images.githubusercontent.com/7164280/73597616-68fa3500-4536-11ea-9c49-11bb35579b03.png)

**Comment by AlexTr** [comment]
It looks like something is wrong with your MySQL server, you need to investigate your mysql server error log to find out what is the problem.
