### ISSUE TITLE
"Auto-more" menu issues

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2610]
- [x] 1. in "Add new..." block it's very difficult to click on 3 dots, it's need to be bigger clickable area

- [x] 2. sometimes there is space in header, but still some menu items are still in more menu:
![Screen Shot 2020-02-19 at 13 53 46](https://user-images.githubusercontent.com/3324866/74797501-55651180-531f-11ea-9278-daf5134c9aad.png)
https://una.io/page/view-discussion?id=4896 - "Timeline Post" paragraph

**Comment by AntonLV** [comment]
Point №1 was fixed in ticket #2618 - point №3.
