### ISSUE TITLE
Events: missing lang keys in previous update 

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2617]
It looks like all lang keys after `_bx_events_page_block_title_fans_invites` wasn't added during update:

![Screen Shot 2020-02-19 at 19 29 05](https://user-images.githubusercontent.com/3324866/74815911-35007b80-534e-11ea-9fe4-7439c1517ccf.png)

**Comment by AntonLV** [comment]
**_bx_events_page_block_title_fans_invites** and **_bx_events_page_block_title_system_invites** language keys should be updated in Russian language too because they got English translations by mistake.
