### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2618]
- [x] 1. https://una.io/page/view-discussion?id=4906
- [x] 2. https://una.io/page/view-discussion?id=4944
- [x] 3. See comment from Andrew

**Comment by andreyasko** [comment]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/22210428/75132956-f93e2b00-572c-11ea-88c9-83bf294139c1.png">

**Comment by AntonLV** [comment]
Point №2 isn't a bug. **Views** counter can be easily activated via Studio -> Navigation -> Timeline -> Item Counters -> View.
