### ISSUE TITLE
DATE FORMAT (custom field)

### ISSUE THREAD

**Issue by bouhlal** [unacms/UNA#2620]
the custom field for a date does not change format from Polyglot it show always YYYY-MM-DD even when we change it to DD-MM-YYYY we have always 2020-02-20

![75123437-a9695080-56a7-11ea-87a6-54d0372baed8](https://user-images.githubusercontent.com/3324866/75212206-4a582880-57da-11ea-9a7b-08c8c1fa8eb8.png)

**Comment by AlexTr** [comment]
Could you please specify where exactly you want to change date format ?

**Comment by bouhlal** [comment]
Hello
please find attached screenshot that explaine the problem
Best Regards
![Screenshot_20200224-014706](https://user-images.githubusercontent.com/804127/75123431-a706f680-56a7-11ea-8774-44d1d4cea6f1.png)
![Screenshot_20200224-014703](https://user-images.githubusercontent.com/804127/75123433-a8382380-56a7-11ea-9232-942ab5742fb9.png)
![Screenshot_20200224-014701](https://user-images.githubusercontent.com/804127/75123435-a8d0ba00-56a7-11ea-8f4e-a538098e6022.png)
![Screenshot_20200224-014658](https://user-images.githubusercontent.com/804127/75123437-a9695080-56a7-11ea-87a6-54d0372baed8.png)

**Comment by AlexTr** [comment]
Thank you for the screenshots, actually in the input field it can't be changed, but upon display (last screenshot) it should be changed according to the settings. 
Could you please provide screenshot of the Date Of Birth field from Studio > Forms builder ?

**Comment by bouhlal** [comment]
Hello 
here is the screenshot from the Form Builder and from developper app : 
![3](https://user-images.githubusercontent.com/804127/75617547-df537c80-5b60-11ea-9324-b13adb8327ea.png)
![4](https://user-images.githubusercontent.com/804127/75617549-e4b0c700-5b60-11ea-9bc8-6b6d5c2da7c6.png)

![1](https://user-images.githubusercontent.com/804127/75617515-6f44f680-5b60-11ea-9cad-bd3938669aed.png)
![2](https://user-images.githubusercontent.com/804127/75617517-73711400-5b60-11ea-8c78-a4dc5547a37f.png)

**Comment by AlexTr** [comment]
@bouhlal thank you fo the screenshots, we can fix displaying date format when added page is displayed, when page is editing it can't be changed for now.

**Comment by bouhlal** [comment]
there is no problem if stay like this in-page editing the important is the page displaying
thank you

**Comment by AlexTr** [comment]
It looks like this problem is already fixed since it can't be reproduced anymore
