### ISSUE TITLE
Blocks outside of page layout cells should be visible somewhere

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2626]
Since it could be situations when blocks are in 3rd cell, but page layout is 2 cell, so block in 3rd cell isn't available.
https://una.io/page/cmts-view?sys=bx_forum&id=4900&cmt_id=22422

**Comment by AntonLV** [comment]
Blocks which cannot be seen (because of unsuitable cell number to currently selected layout) should be moved in the last available layout's cell and deactivated.
