### ISSUE TITLE
Comments: duplicate error message

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2627]
https://una.io/page/view-discussion?id=4940

It maybe it's related to the following issue - https://github.com/unaio/una/issues/2523 - then I think we need special exception for guest, so for **guests** **old** MsgBox will be shown, but if **logged-in** user can't post - then standard message is shown, like in **new** MsgBox

**Comment by AntonLV** [comment]
Note. The problem appears for not logged in viewers (guests) when there is no comments in a list.
