### ISSUE TITLE
Logo size isn't changing

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2677]
https://una.io/page/view-discussion?id=5140

Options:

1. It looks like global width&height settings for logo are never used, instead always template specific parameters are used. I think that if logo in some template isn't uploaded then sizes from this template shouldn't be used too.
2. Set default width&height in templates to 0, where sizes matches global parameters, so global parameters will be used by default in most cases
3. Remove global parameters at all, since they almost not used now.

Related ticket - https://github.com/unaio/una/issues/2680

**Comment by AntonLV** [comment]
The option №1 was used.
