### ISSUE TITLE
Privacy control improvements

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2713]
- [ ] Allow to specify which context modules are allowed to be posted in regular modules (however allow special condition for events to be allowed to be posted in groups and spaces)

https://una.io/page/view-discussion?id=5286

More improvements are moved to the next major update - https://github.com/unaio/una/issues/2890

**Comment by romanlesnikov** [comment]
duplicate by https://github.com/unaio/una/issues/2713

**Comment by AntonLV** [comment]
1. Timeline -> Privacy field -> addSpaces shouldn't be called in "Post to Public" and "Post to Profile" forms.
2. Move previous commits in 11.0.3

**Comment by AlexTr** [comment]
@AntonLV  It looks like something is wrong on this line, it happens when trying to create some content entry:
```
<b>Notice</b>:  Undefined index: object in <b>/.../modules/base/general/classes/BxBaseModGeneralFormEntry.php</b> on line <b>506</b><br />

```

**Comment by AlexTr** [comment]
@romanlesnikov it should be possible to post Event to Spaces context, but Spaces don't show in Event's visibility privacy field, only posting Events to Groups is allowed.
