### ISSUE TITLE
Posts (maybe other modules too): change uploader from html5 to simple break uploader

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2721]
![Screen Shot 2020-04-12 at 22 08 16](https://user-images.githubusercontent.com/3324866/79068461-5bb5af80-7d0a-11ea-94b7-1f5be44a122a.png)

если на Posts Add форме поменять у файлов или еще каких вложений тип загрузчика с Html на Simple, то он перестает открываться с ошибкой:

```
Uncaught SyntaxError: Unexpected token '.'
```

**Comment by AntonLV** [comment]
Attachments is a menu which has separate items for all uploaders. So, when uploader was changed in Forms builder, the related menu items should be activated/deactivated in Menu builder.
![изображение](https://user-images.githubusercontent.com/3894360/79102281-17aac500-7d73-11ea-8168-11c0ec74dc28.png)
