### ISSUE TITLE
Messenger doesn't work when I add One Signal Code to Injectors Header

### ISSUE THREAD

**Issue by gobigweb** [unacms/UNA#2725]
Trying to add push notifications to my web browser.

When I turn on ONE SIGNAL in STUDIO with key and api and I also add this code from one signal to the DESIGNER > INJECTIONS (HEAD) section, the messenger app no longer works on the website. BUT one signal does work.

![image](https://user-images.githubusercontent.com/13974623/79194441-61ca8f80-7de1-11ea-8584-6ec0b6035d15.png)

**Comment by AlexTr** [comment]
You don't need to put this code in Injections, all necessary code is already added, all you need is to inseert your OneSignal App Id in Messenger Settings or Site settings and setup your OneSignal account correctly.

Please post such think in forum: https://una.io/page/discussions-home

**Comment by gobigweb** [comment]
Thanks Alex for the update.  The  OneSignal App doesn't appear to work on
my website unless I add that code.  I do some more testing.


Thanks,
Derek Cahill
949-285-9424

The information contained in this electronic mail message is confidential
and intended for the sole use of the intended recipient(s) and may be
privileged. The information herein may also be protected by the Electronic
Communications Privacy Act, 18 UCS Sections 2510-2521. Any unauthorized
review, use, disclosure or distribution is prohibited. If you have received
this communication in error, please immediately notify us by telephone
(949-288-3340) and by reply email and destroy all copies of the original
message.  Thank you.
