### ISSUE TITLE
Group based modules: don't show thumbnail when thumb isn't uploaded

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2741]
Actually it was working before (https://github.com/unaio/una/issues/1908) but stopped working recently.

**Comment by AntonLV** [comment]
It worked correctly after #1908 too but stopped working after a01763b commit. Looks like the default value for BxBaseModGroupsTemplate::_bLetterAvatar field was changed by mistake or for test purposes and wasn't returned back.
