### ISSUE TITLE
Timeline: PHP error with 'edit any entry' action

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#2743]
atal error: Unknown action: 'edit any entry' in module 'bx_events'<br /> related code in <b>/var/path_to_una/modules/base/general/classes/BxBaseModGeneralModule.php</b> on line <b>1930</b> <br /> in /path_to_una/inc/utils.inc.php on line 1568
To reproduce:
1. Create Post in context of some Event.
2. Go to Timeline and open related item in new tab (http://my_una.me/page.php?i=item&id=xxxx).
3. Go to Studio and disable Events module.
4. Refresh the tab with Timeline item. 
5. The error should appear. If not, you need to switch to some other profile of yours and refresh again.

**Comment by yanivz** [comment]
i've installed channels, made some from timeline then uninstall channels. error happens on timeline for non-registers users

**Comment by AntonLV** [comment]
The issue was fixed here #2808
