### ISSUE TITLE
Moderator notes. 

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#2764]
1. Integrate comments into the reports. A separate comment object should be used with reports.
2. A report should appear as a comment and moderators should be able to post their notes (comments) related to this reported content.
3. View Reports should be represented as a list of comments where moderators can post their notes (comments), reply to existed notes.
m664378 (2224073)

**Comment by AntonLV** [comment]
1. There's no close (X button) on the notes window
2. If you click the "Camera icon" and then close that upload window in any way (either the close or upload button), it closes the whole note window, rather than just the upload window.
3. Clicking "Edit" on any note closes the whole note window
4. No way to cancel editing if you change your mind.
5. Multiple parts of the froala editor are clipped by the edit window, preventing use (ie. add a link, insert image, etc)

The last 2 issues can be reproduced in common comments too.

**Comment by AntonLV** [comment]
Screenshot for point 5:
![изображение](https://user-images.githubusercontent.com/3894360/83479850-71418d00-a4a2-11ea-9729-79a464bf652b.png)

**Comment by AlexTr** [comment]
@AntonLV re:5
As I see there is TinyMCE editor now instead of Froala which don't have such issue.
