### ISSUE TITLE
Add API services

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2776]
t.1470968
t.17478168
t.17478334

- [x] Add Timeline Update (including Attachments)
- [x] Edit Timeline Update (including Attachments)
- [x] Get Timeline Updates (including Attachments)
- [x] Edit as analogue entity_add in General

**Comment by AntonLV** [comment]
Note. The current version of Timeline doesn't allow to Edit update's attachments at all.

**Comment by AntonLV** [comment]
The possibility to edit attachments was added in Ticket #701.
