### ISSUE TITLE
UNA 11.0.1 Database Error occurs after upgrade to 11.0.1

### ISSUE THREAD

**Issue by EducatedSingles** [unacms/UNA#2789]
Dear UNA Team,

I get this message daily after my system autoupgraded to 11.0.1.

I will be very grateful for your help

All the best
Finn Majlergaard

Database error in Educated Singles Club - For Elite Academic Singles Exclusively

Query:
SELECT `sys_profiles`.* FROM `sys_profiles` INNER JOIN `sys_acl_levels_members` AS `tlm` ON `sys_profiles`.`id`=`tlm`.`IDMember` WHERE 1 AND `tlm`.`IDLevel` IN (7,8) AND (`tlm`.`DateStarts` IS NULL OR `tlm`.`DateStarts` <= NOW()) AND (`tlm`.`DateExpires` IS NULL OR `tlm`.`DateExpires` > NOW()) AND `sys_accounts`.`email_confirmed` != 0

Mysql error:
Unknown column 'sys_accounts.email_confirmed' in 'where clause'

Location:
The error was found in getAll function in the file /home/educated/public_html/inc/classes/BxDolAclQuery.php at line 444.

**Comment by AlexTr** [comment]
Thank you for the report, this error has been fixed in 11.0.2
https://github.com/unaio/una/issues/2770

**Comment by AlexTr** [comment]
@EducatedSingles also please be careful with posting debug info it may contain some sensitive data.
