### ISSUE TITLE
"Add New" form has the endless loading if there is no available app in menu

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#2802]
If the "Add Content" menu will have only apps which don't take part there (Groups, Events, Spaces) then form takes the endless loading by clicking the caption "What's happening, {username}". Like it has happened here:
https://una.io/page/view-discussion?id=5654
In this case, only Spaces were available in "Add Content" menu

**Comment by AntonLV** [comment]
Also the following PHP error appears when 'Create Post Menu' menu is disabled.

Fatal error: Uncaught Error: Call to a member function getMenuItems() on bool in /[path_to_una]/template/scripts/BxBaseServices.php on line 191
