### ISSUE TITLE
minor SEO fixes

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2815]
- [x] 1. remove`type="text/javascript"` for all scripts for automatic generated scripts (for v.12 everywhere)

- [x] 2. remove this code 
![image](https://user-images.githubusercontent.com/3324866/83717400-f630d000-a675-11ea-8576-561320a6f230.png)

- [x] 3. remove empty target attribute - `target=""` in menu templates for menus which appear for guests
![image](https://user-images.githubusercontent.com/3324866/83717503-3bed9880-a676-11ea-9ad7-934b55c5b0cf.png)

- [x] 4. Add ability in page builder to add custom code in `<head>` section and before closing `<body>` tag. This code shouldn't overwrite system injections, but add own code. This is for **v.12**

- [x] 5. [@AlexTr ] consider to make permanent redirect for pages like `https://example.com/page/about/` to `https://example.com/page/about` in UNA

**Comment by AntonLV** [comment]
Related changes in Ticket #2833
