### ISSUE TITLE
Comments: php warning

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2830]
There is PHP warning on this page:
https://una.io/page/cmts-view?sys=bx_forum&id=5860&cmt_id=27047

I think such situation happened when I tried to reply to some comments, but while I was typing the text, the author deleted his comments, but I didn't know about it and posted comment for deleted comment, as the result such problem has place.

**Comment by AntonLV** [comment]
The situation was confirmed. But also the following PHP error was returned in post responce:
Notice: Undefined index: cmt_level in /[path_to_una]/template/scripts/BxBaseCmts.php on line 997
