### ISSUE TITLE
optimize notification query

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2845]
- [ ] optimize  notification query  its' slow(2s) for ~1M records
- [x] autotruncate data in bx_notifications_events

`(SELECT COUNT(DISTINCT `bx_notifications_events`.`id`) FROM `bx_notifications_events` LEFT JOIN `bx_notifications_handlers` ON `bx_notifications_events`.`type`=`bx_notifications_handlers`.`alert_unit` AND `bx_notifications_events`.`action`=`bx_notifications_handlers`.`alert_action` INNER JOIN `bx_notifications_settings` ON `bx_notifications_handlers`.`id`=`bx_notifications_settings`.`handler_id` AND `bx_notifications_settings`.`delivery`='site' AND `bx_notifications_settings`.`active`='1' AND `bx_notifications_settings`.`type`='personal' LEFT JOIN `bx_notifications_settings2users` ON `bx_notifications_settings`.`id`=`bx_notifications_settings2users`.`setting_id` AND `bx_notifications_settings2users`.`user_id`=73 AND (ISNULL(`bx_notifications_settings2users`.`active`) OR `bx_notifications_settings2users`.`active`='1') WHERE 1 AND `bx_notifications_events`.`active`=1 AND `bx_notifications_events`.`id`&gt;839533 AND `bx_notifications_events`.`owner_id`&lt;&gt;`bx_notifications_events`.`object_owner_id` AND ((`bx_notifications_events`.`owner_id`=73 AND `bx_notifications_events`.`object_privacy_view`&lt;0 AND `bx_notifications_events`.`owner_id`=ABS(`bx_notifications_events`.`object_privacy_view`)) OR `bx_notifications_events`.`object_owner_id`=73) ) UNION (SELECT COUNT(DISTINCT `bx_notifications_events`.`id`) FROM `bx_notifications_events` LEFT JOIN `bx_notifications_handlers` ON `bx_notifications_events`.`type`=`bx_notifications_handlers`.`alert_unit` AND `bx_notifications_events`.`action`=`bx_notifications_handlers`.`alert_action` LEFT JOIN `sys_profiles` AS `tsp` ON `bx_notifications_events`.`owner_id`=`tsp`.`id` INNER JOIN `sys_profiles_conn_subscriptions` AS `c` ON (`c`.`content` = `bx_notifications_events`.`owner_id` AND `c`.`initiator` = 73) INNER JOIN `bx_notifications_settings` ON `bx_notifications_handlers`.`id`=`bx_notifications_settings`.`handler_id` AND `bx_notifications_settings`.`delivery`='site' AND `bx_notifications_settings`.`active`='1' AND ((`bx_notifications_settings`.`type`='follow_member' AND `tsp`.`type` IN ('bx_persons')) || (`bx_notifications_settings`.`type`='follow_context' AND `tsp`.`type` IN ('bx_channels','bx_groups','bx_spaces'))) LEFT JOIN `bx_notifications_settings2users` ON `bx_notifications_settings`.`id`=`bx_notifications_settings2users`.`setting_id` AND `bx_notifications_settings2users`.`user_id`=73 AND (ISNULL(`bx_notifications_settings2users`.`active`) OR `bx_notifications_settings2users`.`active`='1') WHERE 1 AND `bx_notifications_events`.`active`=1 AND `bx_notifications_events`.`id`&gt;839533 AND `bx_notifications_events`.`date` &gt; `c`.`added`)`

**Comment by AntonLV** [comment]
Point №2 was added in Ticket #2876
