### ISSUE TITLE
Timeline comments are available in the keyword search

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#2846]
...even if the original timeline post has a strict level of visibility. No-friends may see what comments has the "friends only" post. Original request:
https://una.io/page/view-discussion?id=5905

**Comment by AntonLV** [comment]
Comment can be found in Site Search and it's OK. We have the same behaviour in all apps. 
The only issue that Timeline comment can be Viewed while in another modules viewer receives '**Access denied. This is private content.**' on view comment page in similar circumstances.
