### ISSUE TITLE
fatal error lessphp during installation

### ISSUE THREAD

**Issue by charligoose** [unacms/UNA#2858]
Hello - first of all, many thanks for the amazing product. 
I had this set up before and it was all good. However, I am trying to set it up with a new hosting company, Domainracer, and got the following errors.
Can someone take a look? Many thanks!

08-Jul-2020 00:22:32 UTC] PHP Notice:  Undefined index: sCurrentLanguage in /home2/heymofas/public_html/inc/classes/BxDolLanguages.php on line 195
[08-Jul-2020 00:22:33 UTC] PHP Notice:  Undefined index: sCurrentLanguage in /home2/heymofas/public_html/inc/classes/BxDolLanguages.php on line 195
[08-Jul-2020 00:22:44 UTC] PHP Fatal error:  Uncaught Less_Exception_Compiler: error evaluating function `rgba` color functions take numbers as parameters index: 4102 in /home2/heymofas/public_html/plugins/lessphp/Less.php:4797
Stack trace:
#0 /home2/heymofas/public_html/plugins/lessphp/Less.php(5692): Less_Tree_Call->compile(Object(Less_Environment))
#1 /home2/heymofas/public_html/plugins/lessphp/Less.php(7915): Less_Tree_Expression->compile(Object(Less_Environment))
#2 /home2/heymofas/public_html/plugins/lessphp/Less.php(6725): Less_Tree_Value->compile(Object(Less_Environment))
#3 /home2/heymofas/public_html/plugins/lessphp/Less.php(6859): Less_Tree_Rule->compile(Object(Less_Environment))
#4 /home2/heymofas/public_html/plugins/lessphp/Less.php(198): Less_Tree_Ruleset->compile(Object(Less_Environment))
#5 /home2/heymofas/public_html/plugins/lessphp/Cache.php(170): Less_Parser->getCss()
#6 /home2/heymofas/public_html/plugins/lessphp/Cache.php(106): Less_Cache::Cache(Array, Array)
#7 /home2/heymofas/public_html/inc/classes/BxDolTemplate.php(2022): Less_C in /home2/heymofas/public_html/plugins/lessphp/Less.php on line 4797

**Comment by AlexTr** [comment]
Please could you specify your PHP version and UNA version ?

**Comment by charligoose** [comment]
UNA latest direct download from your website
php version = 7.3.11
I am very confused too. 
![Screen Shot 2020-07-08 at 8 24 57 AM](https://user-images.githubusercontent.com/46832397/86918388-a15cfb00-c0f4-11ea-9510-2aa8ddbca47c.png)

**Comment by AlexTr** [comment]
It maybe you are using some Template Mix with incorrect values, please try to switch to other UNA template and/or Una template mix.

**Comment by charligoose** [comment]
Hi Alex,

It's the installation pack I downloaded from your website. I didn't change anything in it.

**Comment by AlexTr** [comment]
I don't think it's related, but I think it's better to try, if it's possible could you please remove all disabled functions, as I see it isn't detected correctly and there are some functions in your list of disabled functions which are actually used, I've created an issued for this:
https://github.com/unaio/una/issues/2862

**Comment by charligoose** [comment]
hey turns out that the opcache needed to be enabled to make the installation go thru! this hosting companies didn't have it on by default and that was the cause

thank you Alex!

**Comment by AlexTr** [comment]
Thank you for letting us know.

**Comment by premolar** [comment]
Unsubscribe

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Alex Trofimov <notifications@github.com>
Gönderildi: Monday, July 27, 2020 3:47:09 AM
Kime: unaio/una <una@noreply.github.com>
Bilgi: Subscribed <subscribed@noreply.github.com>
Konu: Re: [unaio/una] fatal error lessphp during installation (#2858)


Closed #2858<https://github.com/unaio/una/issues/2858>.

**Comment by AlexTr** [comment]
@premolar You are subscribed to this repository by yourself, so you need to
unsubscribe manually as well, we can't unsubscribe you.
