### ISSUE TITLE
Pagination in search form, contained location radius

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#2882]
after "next page button"  click url = ?object=bx_spaces&show_empty=1&cond=a%3A2%3A%7Bs%3A10%3A"space_name"%3Bs%3A1%3A"a"%3Bs%3A8%3A"location"%3Ba%3A2%3A%7Bs%3A6%3A"string"%3Bs%3A0%3A""%3Bs%3A5%3A"array"%3Ba%3A9%3A%7Bi%3A0%3Bs%3A0%3A""%3Bi%3A1%3Bs%3A0%3A""%3Bi%3A2%3Bs%3A0%3A""%3Bi%3A3%3Bs%3A0%3A""%3Bi%3A4%3Bs%3A0%3A""%3Bi%3A5%3Bs%3A0%3A""%3Bi%3A6%3Bs%3A0%3A""%3Bi%3A7%3Bs%3A0%3A""%3Bi%3A8%3Bi%3A0%3B%7D%7D%7D&start=10&per_page=10

wrong array serialization

need check also price filed (contaned 2 fields as well)

**Comment by AntonLV** [comment]
PHP notice when trying to edit 'Location Radius' field in Search builder:
Notice: Undefined index: location_radius in /[path_to_una]/studio/template/scripts/BxBaseStudioFormsSearchFields.php on line 120

**Comment by AntonLV** [comment]
Note. Error appears even if search by radius wasn't used.
