### ISSUE TITLE
timeline module fatal error 

### ISSUE THREAD

**Issue by charligoose** [unacms/UNA#2885]
I opened an issue on the forum as well - but it's really too busy there
i have this timeline error and it will send my site into intermittent DB query error/offline status (didn't know it was caused by timeline module until yesterday...)

message will be slightly different but mainly like the ones below -

`Fatal error: Uncaught Error: Call to a member function getContentByGroupAsSQLPart() on bool in /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineDb.php:742 Stack trace: #0 /var/www/vhosts/heymofas.com/httpdocs/modules/base/notifications/classes/BxBaseModNotificationsDb.php(462): BxTimelineDb->_getSqlPartsEventsList(Array) #1 /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineDb.php(635): BxBaseModNotificationsDb->_getSqlPartsEvents(Array) #2 /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineDb.php(475): BxTimelineDb->_getSqlPartsEvents(Array) #3 /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineTemplate.php(1354): BxTimelineDb->getEvents(Array) #4 /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineTemplate.php(489): BxTimelineTemplate->_getPosts(Array) #5 /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineTemplate.php(189): BxTimelineTemplate->getP in /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineDb.php on line 742`

`Notice: Undefined index: values in /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineFormPost.php on line 259

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineFormPost.php on line 259

Fatal error: Uncaught Error: Call to a member function addMarkers() on bool in /var/www/vhosts/heymofas.com/httpdocs/modules/base/text/classes/BxBaseModTextUploaderHTML5Attach.php:27 Stack trace: #0 /var/www/vhosts/heymofas.com/httpdocs/modules/boonex/timeline/classes/BxTimelineUploaderHTML5Attach.php(18): BxBaseModTextUploaderHTML5Attach->__construct(Array, 'bx_timeline_pho...', 'Mkc7AWUn', Object(BxDolModuleProxy)) #1 /var/www/vhosts/heymofas.com/httpdocs/inc/classes/BxDolUploader.php(151): BxTimelineUploaderHTML5Attach->__construct(Array, 'bx_timeline_pho...', 'Mkc7AWUn', Object(BxDolModuleProxy)) #2 /var/www/vhosts/heymofas.com/httpdocs/template/scripts/BxBaseFormView.php(1055): BxDolUploader::getObjectInstance('bx_timeline_htm...', 'bx_timeline_pho...', 'Mkc7AWUn', Object(BxDolModuleProxy)) #3 /var/www/vhosts/heymofas.com/httpdocs/template/scripts/BxBaseFormView.php(625): BxBaseFormView->genInputFiles(Array, '', '`

I never changed any code in the module. Do you know what's going on here?

**Comment by AlexTr** [comment]
Please refer to reply in forum - https://una.io/page/view-discussion?id=6028
