### ISSUE TITLE
Cache isn't cleared after membership level data is changed, such as max file size

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2886]

**Comment by premolar** [comment]
Unsubscribe

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Alex Trofimov <notifications@github.com>
Gönderildi: Sunday, July 26, 2020 5:53:39 AM
Kime: unaio/una <una@noreply.github.com>
Bilgi: Subscribed <subscribed@noreply.github.com>
Konu: [unaio/una] Cache isn (#2886)
