### ISSUE TITLE
How to debug when UNA fails upgrade process?

### ISSUE THREAD

**Issue by vittore** [unacms/UNA#2895]
Hi,

I have Version: 11.0.0 Installed, so I try to upgrade to 11.0.2, then I click the "Update" button.
But system don't upgrade and in logs/upgrade.logs there are some messages:

```
11.0.0-11.0.1 upgrade will be applied
Files permissions are ok and can be overwritten
ERROR:Files copying failed
```

Is there a method to debug where upgrade process fails?

Thanks in advance.

**Comment by AlexTr** [comment]
Please check if you have **real** path to UNA files in inc/header.inc.php. Sometimes www root folder is a symlink to some other folder, in this case make sure that path is specified without symlinks.
