### ISSUE TITLE
How to add a new post manually...?

### ISSUE THREAD

**Issue by KLA6** [unacms/UNA#2912]
First of all, I really appreciate for all the contributors who is making this great code...!

I just a have basic question, because of my lack of abilities.

I'm intending to add posts by my own DB to UNA.

What if I make a kind of importing posts function by my own, how should I approach...?

FYI, I've already tired to input records on...
 - bx_posts_posts
 - bx_timeline_events

... but it doesn't show the new records on the timeline feed.

**What if I want to add a post to the timeline feed, besides adding records on the above 2 tables, what should I do more...?**

Thank you for reading my question.

**Comment by AlexTr** [comment]
I would suggest to do it programmatically, there is service method to call, something like this:
```php
bx_srv('bx_posts', 'entity_add', array($iAuthorProfileId, array('title' => 'Some title', 'cat' => 1, 'text' => 'Post text')));
```
Please post your questions in  forum: 
https://una.io/page/discussions-home

**Comment by KLA6** [comment]
Thank you so much for your answering...! : )

And, I will use the forum from the next time as your guide.
