### ISSUE TITLE
Author Block

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#2918]
Add new block for Profile-type  and Content-type modules, which shows basic profile overview - image, info and action buttons, as well as potentially some extra data from other modules, like Skills, Groups, etc....

This is useful for creating profiles where profile cover can be turned off and only a block is available. Also for posts/products/classes where extended info about the author is useful.

![image](https://user-images.githubusercontent.com/22210428/90620491-e036b280-e255-11ea-987b-708a6ee4c4e8.png)

**Comment by AntonLV** [comment]
Author Block was realized as system service method and can be placed on any view content page. 
The service method is based on 'get profile cover as block' service method which is available in profile modules.
