### ISSUE TITLE
Relationship: inability to side-scroll on relationship page via mobile view

### ISSUE THREAD

**Issue by siremystic** [unacms/UNA#2928]
![Screenshot_20200828-020349_1598576701946](https://user-images.githubusercontent.com/47337635/91510244-7dbf6100-e8aa-11ea-8884-4a6697a1889b.png)

**Comment by siremystic** [comment]
@AlexT-UNA @AlexTr

**Comment by AlexTr** [comment]
Please specify your mobile device type and OS and browser version ?

**Comment by siremystic** [comment]
> Please specify your mobile device type and OS and browser version ?

on android and ios mobile device, old & latest OS and version
