### ISSUE TITLE
Timeline: Can't add links with exclamation mark

### ISSUE THREAD

**Issue by achimwagenknecht** [unacms/UNA#2936]
When you try to add a link with an exclamation mark to the feed, the link will be cut off after the exclamation mark. Example:
https://taz.de/Nach-der-rechten-Demo-in-Berlin/!5706546/
-> https://taz.de/Nach-der-rechten-Demo-in-Berlin/!
This leads to errors. Instead the full link should be preserved.

**Comment by achimwagenknecht** [comment]
Thank you very much!

**Comment by achimwagenknecht** [comment]
Please re-open this.
Now a similar bug occured: I could not add the following link because of the bracket:
https://en.wikipedia.org/wiki/Susu_(informal_loan_club)
-> https://en.wikipedia.org/wiki/Susu_

Can you fix this, too?

**Comment by AlexTr** [comment]
@achimwagenknecht thank you for the report -https://github.com/unaio/una/issues/3276

**Comment by achimwagenknecht** [comment]
Please re-open this.
Now a similar bug occured: I could not add the following link because of the #:
https://pluralistic.net/2021/04/02/innovation-unlocks-markets/#digital-arm-breakers
-> https://pluralistic.net/2021/04/02/innovation-unlocks-markets/#

Can you fix this, too?
