### ISSUE TITLE
Unable to create new Operator accounts

### ISSUE THREAD

**Issue by ChrisCastr0** [unacms/UNA#2981]
I am unable to see the "Create Operator" button that is shown in the instructions

![image](https://user-images.githubusercontent.com/70775232/93542999-48d58580-f90f-11ea-9de8-8dd92cd04fa4.png)

What I am expecting to see:
![image](https://user-images.githubusercontent.com/70775232/93543097-82a68c00-f90f-11ea-9306-a2b73b00f88d.png)

**Comment by AlexTr** [comment]
You can't create new operators, you can give operators permissions using "Make Operator" action to the existing member.
