### ISSUE TITLE
White overlay not disappearing ( Permission denied to access property "apply" )

### ISSUE THREAD

**Issue by licnep** [unacms/UNA#2996]
In Firefox (tested on 72.0.1), on a plain installation of una, no plugins, in several places the semi-transparent white overlay under popups never disappears, making the page unusable. This happens for example in the app store, after clicking on an app to read its description, and then trying to close the popup. Or when creating a new profile, clicking on upload profile picture, and then trying to close the popup. 

There is an error that shows up in the javascript console (this does not show up in chrome, this whole issue doesn't happen in chrome):

```
Error: Permission denied to access property "apply"gzip_loader.php:5:11594
    trigger gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:5
    trigger gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:13
    triggerHandler gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:5
    oOnHide gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:330
    complete gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:6
    i gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:4
    fireWith gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:4
    i gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:6
    tick gzip_loader.php?file=bx_templ_js_7e0a71557ec662578c267e446a693efe.js:6
```

I can help debugging if needed

**Comment by AlexTr** [comment]
I can't reproduce the issue. Please try to clear UNA cache via Studio > Dashboard > Cache, it maybe it'll help.
