### ISSUE TITLE
Menus badges need to be loaded asynchronously via separate AJAX call

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3002]
to not cause delay during page load. 

Use existing live updates engine to load everything in one call.

Also these badges will be updated in real time which is better as well.

**Comment by AntonLV** [comment]
> Also these badges will be updated in real time which is better as well.

**Note**. If menu item's badge is fully integrated with Live Updates, the counter inside the badge is already updated dynamically. For example, it's working this way for Shopping Cart and Notifications menu items in Account Dropdown menu.

**Comment by AlexTr** [comment]
> > Also these badges will be updated in real time which is better as well.
> 
> **Note**. If menu item's badge is fully integrated with Live Updates, the counter inside the badge is already updated dynamically. For example, it's working this way for Shopping Cart and Notifications menu items in Account Dropdown menu.

Ok, great, then we need to make sure that all badges are updated this way and first update should be called just after the page load.
