### ISSUE TITLE
Paginate: Customizable buttons.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#3011]

**Comment by yanivz** [comment]
please add this:
- if the its ajax paginate then scroll up after going to the next page
- add paginate button on top and bottom (optional)

**Comment by AlexTr** [comment]
> please add this:
> 
> * if the its ajax paginate then scroll up after going to the next page
> * add paginate button on top and bottom (optional)

Thank you @yanivz we'll consider it for future versions: https://github.com/unaio/una/issues/3064
