### ISSUE TITLE
Timeline: When multiple pics are uploaded, users should be able to navigate between pics on pop-up view

### ISSUE THREAD

**Issue by siremystic** [unacms/UNA#3043]
it's not user friendly on timeline to always have to click per pic without being able to navigate on pop-up view/layouts....as a user would have to click on each pic to access its pop-up view. Moving forward, there should be a forward & backward navigation in the pop-up view layout. @AlexTr @AlexT-UNA

**Comment by siremystic** [comment]
This is for pics added through "update" on timeline

**Comment by AntonLV** [comment]
Partially done in Ticket #3553
