### ISSUE TITLE
Profile timeline cache issue

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#3044]
m.761675
BxTimelineTemplate.php -> _cacheEvent
instead of
` else if(in_array($aParams['type'], array(BX_BASE_MOD_NTFS_TYPE_OWNER, BX_TIMELINE_TYPE_FEED, BX_TIMELINE_TYPE_CHANNELS, BX_TIMELINE_TYPE_OWNER_AND_CONNECTIONS))){
			 $aParamsSet['context_id'] = $iProfileId;` 

must be something like 
$aParamsSet['context_id'] = $aParams[$CNF['FIELD_OWNER_ID']];

as now context_id always equal profile_id for all viewed profiles

**Comment by AntonLV** [comment]
The issue was fixed in Ticket #3016
