### ISSUE TITLE
High CPU usage in timeline on homepage

### ISSUE THREAD

**Issue by rednaxal** [unacms/UNA#3047]
Sometimes in case there are 20+ items on a timeline the page becomes very slow responsive. Some JS script constantly consumes 100% of a single CPU core. 
The main suspect is plugins_public/jquery.ba-resize.min.js

**Comment by AntonLV** [comment]
Actions menu in Timeline card was updated in Ticket #3026. 
Current menu doesn't have so many recalculations.
