### ISSUE TITLE
"Follow" doesn't appear on Organization's & Event home pages and Organization's & Event profile pages

### ISSUE THREAD

**Issue by Miroslav36** [unacms/UNA#3055]
Hello,

I would like persons to follow an organization (not join). On the organizations home page ( /page/organizations-home ) "Follow" button is not displayed when I activate the "follow" button from Navigation/items/Organizations/snippet meta info (the "join" and "add friend" buttons can be removed or displayed).

I have also noticed that on the Organisation's profile page (/page/view-organization-profile?id) I cannot display the "Follow" button. I can change add/remove other buttons with the Navigation/items/organizations/view actions menu.

In the public feed, the "follow" button appears : a person can follow an organization (it work properly except for the display issue I have reported in a previous message).

-> If I do the same with event's home (/page/events-home) and event's profile page (/page/view-event-profile?id) -> same issues, the "follow" button cannot be added/removed as expected.

If I do the same with person's home (/page/persons-home) and person's profile page (/page/view-persons-profile?id) the "follow" button can be added/removed as expected.

Note :

I have just installed a plain UNA v11.0.3 (debian 10/apache/mariadb) site with no customization.
I've created 2 accounts with 1person profile + 1 organization profile each.
All profiles are on the preinstalled "standard" level.

Could you please help with this issue ?

Thank you

**Comment by AlexTr** [comment]
Thank you for the report, it was already fixed in this ticket:
https://github.com/unaio/una/issues/2982
It will be available in the next version update.
