### ISSUE TITLE
Notifications cache issues

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3061]
- [x] 1. separate cache for `data` and `systems`
- [ ] 2. don't cache if DB cache disabled
- [ ] 3. don't cache transient systems (since it's added dynamically anyway)

**Comment by AntonLV** [comment]
3. Cannot be done because serialized data about handler for transient live update is stored in the cache. It's needed that subsequent dynamic calls on the page can retrieve the data about this transient live update.

**Comment by AntonLV** [comment]
2. Cannot be done because transient live updates stop working. It's essential for them to pass update's data (handler, etc.) through the cache file.

**Comment by AntonLV** [comment]
Systems and Data caches were divided. For now Live Updates can use 3 types of cache files:
1. Systems cache file which is equal for all users on all pages, which don't use Transient Live Updates.
2. Systems cache files which are created for each user separately on pages with Transient Live Updates (pages with comments and Timeline blocks). It's needed to store and pass Transient Live Updates data between dynamic calls while a user stays on this page.
3. Data cache file. Each user has only one data cache file related to his currently active profile.
