### ISSUE TITLE
Make Membership Block Responsive

### ISSUE THREAD

**Issue by achimwagenknecht** [unacms/UNA#3062]
The Membership block is not fully visible on small mobile devices. I could not find the cause in the source code. All "width" arguments are in percent, so it should fit in automatically, but it does not. The block also has a "responsive" wrapper, but obviously this does not the job.

**Comment by achimwagenknecht** [comment]
The block is formatted as a table and the columns are too wide. They should be narrower. Also I wonder if it would be possible to use some other formatting, other than a table, so the fields could be arranged better on narrow screens.

**Comment by AlexTr** [comment]
@achimwagenknecht thank you for the report, could you please provide screenshot of the problem ? and type and screen size of the mobile device you are using ?

**Comment by achimwagenknecht** [comment]
![zubreit](https://user-images.githubusercontent.com/10030555/99231599-1eaa2200-27f1-11eb-9907-b02e3ad1f81e.gif)

**Comment by AlexTr** [comment]
As I see it's working correctly.

**Comment by achimwagenknecht** [comment]
While "working correctly" is technically correct, a significant percentage of customers won't be able to use this ui. This is not about "working correctly" in a technical way. It's about loosing customers. Please reopen as improvement. Using UNA should be as easy as possible for customers. You know, shops in the city usually don't have stairs at the entrance, although stairs would be "working correctly".

**Comment by AlexTr** [comment]
> While "working correctly" is technically correct, a significant percentage of customers won't be able to use this ui. This is not about "working correctly" in a technical way. It's about loosing customers. Please reopen as improvement. Using UNA should be as easy as possible for customers. You know, shops in the city usually don't have stairs at the entrance, although stairs would be "working correctly".

If membership name is a bit longer it will not fit into the page, which will cause more issues, so we used more universal solution which works everywhere. For your case you can run the following query to make this grid non-responsive, considering short membership name in your case it maybe it will fit the page:
```sql
UPDATE `sys_objects_grid` SET `responsive` = '0' WHERE `object` = 'replace with grid name here';
```
Since your grid is from 3rd-party module, then it's better to ask developer to determine grid object name.
