### ISSUE TITLE
Protean: notifications menu popup is white bg while other popups (add content, account) have dark bg

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3080]
![photo_2020-12-11 20 34 59](https://user-images.githubusercontent.com/3324866/101886964-5b024f80-3bf0-11eb-8bec-7bf10ee28615.jpeg)
![photo_2020-12-11 20 34 57](https://user-images.githubusercontent.com/3324866/101886970-5dfd4000-3bf0-11eb-89cc-62e9a9c47528.jpeg)

**Comment by AntonLV** [comment]
The same issue appears with Site Search sliding menu.
