### ISSUE TITLE
Discussions app not installing - wrong version of UNA?

### ISSUE THREAD

**Issue by HerrUU** [unacms/UNA#3172]
Hi, tried to install the Discussions module on my UNA install. However, I get the error message that the module is not compatible with my version of UNA (even though it's the last version : 11.0.4)?

**Comment by AlexTr** [comment]
@HerrUU please upgrade to latest UNA 12 to be able to install it: https://una.io/page/cmts-view?sys=bx_forum&id=6947&cmt_id=31383
