### ISSUE TITLE
Studio navigation bug

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#3201]
Apps with lots of items in side menu will show cut-off menu underlay:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/22210428/108000577-62096c00-703e-11eb-8e3c-27737c6ca8aa.png">

**Comment by AntonLV** [comment]
Looks like the problem can be seen in iOS Safari only.
In Windows Chrome it looks this way:
![изображение](https://user-images.githubusercontent.com/3894360/108041185-43f83780-704f-11eb-9ad0-f97521dfddb6.png)
