### ISSUE TITLE
Communication category isn't showing data in Studio > Apps market >  Categories > Communication

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3202]
![image](https://user-images.githubusercontent.com/3324866/108004024-b580b780-7048-11eb-888e-54e101c006d0.png)

**Comment by Rigal777** [comment]
Tried logging out and back in to see if I could go into communication category to download friends finder module but issue is still there like image above, empty.

**Comment by Rigal777** [comment]
Ruben Ollervides (here)
In Addition 
Froala Stopped working
Yes for some reason Froala stopped working. Not sure what happened if it was a hiccup on the server or what but the newsfeed went down I switched it off and back on that brought it back online but then the post comment Module was asking for Title and Category which wasn't like that prior I played around with it for two hours. The only thing new was someone made the first page on the site so I turned pages off then back on. That got rid of the post asking for title and category but Froala stopped working everywhere. Is there a way I can uninstall it and reinstall???
