### ISSUE TITLE
Lucid + Froala: emoticons problem in Post to Context/Public Feed

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#3206]
The Emoticons seem to have incorrect z-index:
Lucid: ![image](https://user-images.githubusercontent.com/8243165/108108252-96bb0900-70ba-11eb-958c-86d0dd70d953.png)
Protean:
![image](https://user-images.githubusercontent.com/8243165/108108350-b8b48b80-70ba-11eb-8fd7-70fda96c3b79.png)

**Comment by AlexTr** [comment]
https://una.io/page/view-discussion?id=7342
https://una.io/page/view-discussion?id=7362

**Comment by Rigal777** [comment]
Froala is missing in the home page and time line but appears in other areas like pages. Can you please help me fix this issue?

**Comment by Rigal777** [comment]
I am Ruben Ollervides

**Comment by AlexTr** [comment]
> Froala is missing in the home page and time line but appears in other areas like pages. Can you please help me fix this issue?

It's just a setting, it can be changes in Studio > Timeline > Settings > Post > Enable post form editor toolbar.
@Rigal777 Please post questions in forum please next time

**Comment by Rigal777** [comment]
@AlexTr Awesome! It's back🙂Thank you!

**Comment by Rigal777** [comment]
@AlexTr Also people are posting in these areas (see image) 4 places to post link😳 people are getting confused. The best place to post articles & videos is where the ➕ is ( images & videos are great)and you can paste a link in the share icon far right. Is there a way to remove these other places? So there is no confusion? Also if you post on these other areas only the link posts without image or video. The non Froala link icon at the bottom posts image but they are cut off and looks pretty bad.
![Screenshot_20210218-081857_DuckDuckGo](https://user-images.githubusercontent.com/79125000/108402386-6fb02480-71eb-11eb-8be6-b603afd58d2c.jpg)

**Comment by AlexTr** [comment]
@Rigal777 could you please post question in forum - https://una.io/page/discussions-home ? 
thank you
