### ISSUE TITLE
Payments: allow to post links in email fields in payment gateway configurations

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3213]
add `skip_domain_check` param
![unnamed (2)](https://user-images.githubusercontent.com/3324866/108164222-7df73580-7144-11eb-8522-b1db62cffa22.png)

**Comment by AlexTr** [comment]
I think it still not fixed since `skip_domain_check` param isn't applied anywhere

**Comment by AntonLV** [comment]
I used `emailorempty` check function instead. It has the same effect as `skip_domain_check` param. In addition this check function was already used in the other payment providers' settings, like Stripe and ChangeBee, and they haven't reported problem.
In the BxDolForm you can see:
```
static $FUNC_SKIP_DOMAIN_CHECK = array('email' => 1, 'emails' => 1, 'emailexist' => 1, 'emailuniq' => 1, 'emailexistorempty' => 1, 'hostdomain' => 1, 'hostdomainchat' => 1, 'emailorempty' => 1);

...

if (
        !isset(BxDolForm::$FUNC_SKIP_DOMAIN_CHECK[$sCheckerFunc]) && 
        (!isset($a['skip_domain_check']) || false == $a['skip_domain_check']) && 
        isset(BxDolForm::$TYPES_TEXT[$a['type']]) && 
        bx_is_url_in_content($val) && 
        !isAdmin())
{

...

}
```
