### ISSUE TITLE
Accounts: make operator popup looks a bit strange

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3239]
- [x] No way to make master operator, is it intentional ?
- [ ] 'None' option look strange, please discuss with Andrew, maybe use another title
- [ ] 'None' isn't preselected when no operator role is assigned
- [ ] there are checkboxes which are working like radio buttons, maybe switch to radio buttons

**Comment by AntonLV** [comment]
> No way to make master operator

Custom operator with all available actions will be equal to Master operator.
