### ISSUE TITLE
Secret Groups : event titles are visible for non members in event calendar

### ISSUE THREAD

**Issue by Miroslav36** [unacms/UNA#3247]
UNA 12
Secret Groups : event titles are visible for non members in event calendar.
How to reproduce : 
- create an event in a secret group
- when not connected or not member of a secret group : go to the url of the secret group, click on the "events" menu item.
( url : /page/events-context?profile_id=xx )
- in the "events calendar" section you will see the title of the event
see picture attached the title of the event on march 1st should not be visible for non members : 
![image](https://user-images.githubusercontent.com/17055131/109872937-5f795a00-7c6d-11eb-9722-f3c74b6d8c91.png)

expected behavior : the title should not be readable, have "private event" instead

**Comment by AlexTr** [comment]
Thank you for the report, but actually groups based modules (Groups, Events, Spaces, etc) showing it's name in different places even if it's private. It's needed to be able to join the group, space, event, etc, in case if somebody want to make join request.
