### ISSUE TITLE
Timeline: Can't add links with brackets

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3276]
When you try to add a link with an exclamation mark to the feed, the link will be cut off after the exclamation mark. Example:
https://taz.de/Nach-der-rechten-Demo-in-Berlin/!5706546/
-> https://taz.de/Nach-der-rechten-Demo-in-Berlin/!
This leads to errors. Instead the full link should be preserved.

Related ticket in the past - https://github.com/unaio/una/issues/2936

**Comment by achimwagenknecht** [comment]
Thank you!

**Comment by AntonLV** [comment]
You are welcome!
