### ISSUE TITLE
homepage layout bug after facebook login

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#3278]
facebook login redirects to /#_=_
some block sis duplicated

reason: async blocks
![image](https://user-images.githubusercontent.com/12896257/112111193-ed899600-8bc4-11eb-8a55-0f9d9d358287.png)

**Comment by AntonLV** [comment]
The following JS error appears:
```
Uncaught TypeError: Cannot read property 'option' of undefined at new f (eval at <anonymous> (jquery.min.js?rev=766:2)
```

**Comment by AlexTr** [comment]
@AntonLV all is fine, could you please commit to UNA12 branch as well ?

**Comment by AntonLV** [comment]
Done.
