### ISSUE TITLE
New page layouts 

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3281]
- [x] with top and bottom full width area and 3 columns in the middle with the following proportions - 2/6/4
- [ ] with top and bottom full width area and 3 columns in the middle with the following proportions - 2/5/3

**Comment by AntonLV** [comment]
Page layout with 2/6/4 proportions was added in Ticket #3405

**Comment by AntonLV** [comment]
Layout with 2/5/3 proportions is very close to the first one (2/6/4) and isn't so critical.
