### ISSUE TITLE
PHP 8 compatibility issues

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3289]
https://una.io/page/view-discussion?id=7752

- [x] 1. Albums page will give an HTTP ERROR 500 blank page when php is switched to 8.0 v
- [x] 2. Server Audit (in Studio) will not pull any data when php is switched to 8.0 v
- [x] 3. Fix deprecated errors, in the following places:

```
FILE: modules/boonex/intercom/classes/BxIntercomModule.php:298 
FILE: modules/boonex/mailchimp/classes/BxMailchimpModule.php:274
FILE: modules/base/general/classes/BxBaseModGeneralDb.php:194
FILE: plugins/lessphp/Less.php:5485
```

- [x] 4. Activate Skilles in Persons. Edit profile adding some skills and save.

```
Fatal error: Uncaught Error: Unknown named parameter $min in /[path_to_una]/inc/classes/BxDolForm.php on line 1348
```

- [x] 5. 'Depricated' in Messenger.

```
Deprecated: Required parameter $sValue follows optional parameter $sField in /[path_to_una]/modules/boonex/messenger/classes/BxMessengerDb.php on line 980
```

**Comment by AntonLV** [comment]
The problem from Point №1 exists in all content/context modules.

**Comment by AlexeyUna** [comment]
https://github.com/unaio/jot-client-una/issues/144
