### ISSUE TITLE
Timeline: post link problem with hash symbol

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3297]
Please re-open this.
Now a similar bug occured: I could not add the following link because of the #:
https://pluralistic.net/2021/04/02/innovation-unlocks-markets/#digital-arm-breakers
-> https://pluralistic.net/2021/04/02/innovation-unlocks-markets/#

Can you fix this, too?

_Originally posted by @achimwagenknecht in https://github.com/unaio/una/issues/2936#issuecomment-812840773_

**Comment by achimwagenknecht** [comment]
Thank you!
