### ISSUE TITLE
Groups (maybe other group based modules): regular members are shown in Admins block

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3299]
![image](https://user-images.githubusercontent.com/3324866/113692569-0475cf80-9711-11eb-813b-4faedc5b8f25.png)
![image](https://user-images.githubusercontent.com/3324866/113692601-0b044700-9711-11eb-81bc-7a74b6da444e.png)

**Comment by AntonLV** [comment]
1. Group author has admin status by default. But he should receive 'Administrator' role by default too.
2. Administrators block should check member's Role instead of the appearance in 'admins' table.
