### ISSUE TITLE
Unknown column 'bx_events_cmts.cmt_pinned' in 'order clause'

### ISSUE THREAD

**Issue by ghost** [unacms/UNA#3309]
Database error in 
Query:
SELECT `bx_events_cmts`.*, `sys_cmts_ids`.`id` AS `cmt_unique_id` FROM `bx_events_cmts` LEFT JOIN `sys_cmts_ids` ON (`bx_events_cmts`.`cmt_id` = `sys_cmts_ids`.`cmt_id` AND `sys_cmts_ids`.`system_id` = :system_id) WHERE `bx_events_cmts`.`cmt_object_id` = :cmt_object_id AND `bx_events_cmts`.`cmt_vparent_id` = :cmt_vparent_id ORDER BY `bx_events_cmts`.`cmt_pinned` DESC, `bx_events_cmts`.`cmt_time` ASC LIMIT 0, 0

Mysql error:
Unknown column 'bx_events_cmts.cmt_pinned' in 'order clause'

Location:
The error was found in getAll function in the file /home/username/public_html/community/inc/classes/BxDolCmtsQuery.php at line 225.

collation_connection:
utf8mb4_unicode_ci

**Comment by AlexTr** [comment]
Please update your modules to the latest versions
