### ISSUE TITLE
Hide pinned by other users updates in 'Feed' timeline

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#3313]

**Comment by AntonLV** [comment]
Pinned posts are shown as pinned on Profile Timeline only. There is nothing to change her. 
But 'Pinned' icon related to personal Pinned posts is shown in Feed timelines of other usres that isn't correct and should be fixed.
![изображение](https://user-images.githubusercontent.com/3894360/114883424-95356500-9e0d-11eb-9513-f833bc06859c.png)
