### ISSUE TITLE
Can't find file: 'bx_timeline_hot_track' (errno: 2 - No such file or directory)

### ISSUE THREAD

**Issue by ghost** [unacms/UNA#3324]
Database error 

Query:
SELECT `event_id` FROM `bx_timeline_hot_track`

Mysql error:
Can't find file: 'bx_timeline_hot_track' (errno: 2 - No such file or directory)

Location:
The error was found in fromCache function in the file /home/username/public_html/modules/boonex/timeline/classes/BxTimelineDb.php at line 356.

collation_connection:
utf8mb4_unicode_ci

**Comment by AlexTr** [comment]
It maybe you are using some old version of Timeline module, please check if you are using latest version.
