### ISSUE TITLE
Spaces: add 'template' parameter for 'serviceEntityChilds' and 'serviceEntityParent' methods

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3327]
https://una.io/page/view-discussion?id=7914

**Comment by AlexTr** [comment]
@romanlesnikov 
It's actually was implemented incorrectly, we need to pass template for browse unit, not for the whole block, we need to change this paramater:
```php
    private function getBrowseQuick($aProfiles)
    {
        $sRv = '';
        foreach ($aProfiles as $iProfileId) {
            $oProfile = BxDolProfile::getInstance($iProfileId);
            if(!$oProfile)
                continue;
            $sRv .= $oProfile->getUnit(false, array('template' => 'unit_wo_cover')); // <----- we need to pass template here
        }
        return $sRv;
    }
```

**Comment by romanlesnikov** [comment]
Example of usage
`array (
  'module' => 'bx_spaces',
  'method' => 'entity_childs',
  'params' => 
  array (
    0 => '{content_id}',
    1 => 
    array (
      'template' => 'unit_with_cover',
    ),
  ),
)`
