### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by hardik2015** [unacms/UNA#3333]
![image](https://user-images.githubusercontent.com/43150887/116004001-69408d80-a61e-11eb-8d3d-38fad23d91ce.png)
I got erro while installing una onto my server

**Comment by adultdate** [comment]
Hello

What language module were you trying to install when you got this error?

Please provide me login details for the server if you want me to fix this
urgently.

Otherwise, to solve the problem I will need a bit more info and a full
error report.

**Comment by AlexTr** [comment]
Please post question in forum - https://una.io/page/discussions-home  
Thank you
