### ISSUE TITLE
Group based modules: make "set role" popup to look better

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3357]
Now it looks looks this:
<img width="885" alt="Screen Shot 2021-05-06 at 16 28 29" src="https://user-images.githubusercontent.com/3324866/117253605-bb897600-ae8a-11eb-8318-366688c87034.png">
Make it more like this, so add some margins:
![image](https://user-images.githubusercontent.com/3324866/117254020-40748f80-ae8b-11eb-91f2-9af1f9cd7f2d.png)

**Comment by AntonLV** [comment]
Looks like the problem appears in Lucid template. In Protean the Set Role popup looks the same as others:
![изображение](https://user-images.githubusercontent.com/3894360/117763472-89ce3180-b233-11eb-92c1-cda313382bf9.png)
![изображение](https://user-images.githubusercontent.com/3894360/117763517-9fdbf200-b233-11eb-9394-67bc866b3528.png)
