### ISSUE TITLE
Fancybox isn't working for image URLs without extension

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3362]
It could happen for example when remote storage is used. Can be reproduced here - https://una.io/page/view-product?id=120

Possible solution is to add `type: 'image',` to the init params like described here:
https://stackoverflow.com/questions/18547727/fancybox-urls-without-jpg-opens-not-in-box

**Comment by AntonLV** [comment]
The same issue appears in Studio-> MarketApps.
