### ISSUE TITLE
Bug on trying to add product to favorites

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3363]
- [x] 1. https://una.io/page/view-discussion?id=8003
- [ ] 2. Favorites object doesn't count the number of favorites for the favorited item (can be reproduced in any module).

**Comment by AntonLV** [comment]
The following PHP error appers:
```
Fatal error: Uncaught Error: Call to a member function setId() on bool in /[path_to_una]/template/scripts/BxBaseFavorite.php on line 256
```
The same issue appears in the other content related modules too.
