### ISSUE TITLE
Timeline: make homepage feeds have margins as with profile feeds

### ISSUE THREAD

**Issue by siremystic** [unacms/UNA#3370]
Homepage Feeds:
![margin](https://user-images.githubusercontent.com/47337635/118235599-d8551900-b449-11eb-880b-82540b070b30.PNG)
![margin1a](https://user-images.githubusercontent.com/47337635/118235606-d9864600-b449-11eb-8fe0-a1bd49c77af3.PNG)
Profile Feeds:
![marginb](https://user-images.githubusercontent.com/47337635/118235610-dab77300-b449-11eb-8afb-39eaee7b88ef.PNG)
![margin1b](https://user-images.githubusercontent.com/47337635/118235608-da1edc80-b449-11eb-8a81-b1069c2b1854.PNG)

**Comment by AntonLV** [comment]
I cannot reproduce the problem on the Dev version on https://ci.una.io/test
![изображение](https://user-images.githubusercontent.com/3894360/118474767-1ab17b00-b714-11eb-9f2a-b78d46ead77b.png)

**Comment by siremystic** [comment]
See attached screenshot...no margin on una homepage feeds as well.

**Comment by AntonLV** [comment]
> See attached screenshot...no margin on una homepage feeds as well.

It may happen because of some customization on your site (custom app, custom CSS in template, etc.).
We should reproduce a problem on fresh installed UNA script (for example, [https://ci.una.io/test](https://ci.una.io/test)) to be able to fix it.

**Comment by goiwelkin** [comment]
Same is experienced with una....see una.io homepage feeds do I don't think it's got anything to do with my site.
