### ISSUE TITLE
Credits and invoices remarks

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3389]
- [x] Withdraw request popup - add the following info for Message field - `Payment instructions and other notes`
- [x] Withdraw request email - display message from vendor in email (now it isn't displayed anywhere) and add link to page where admin can confirm withdrawal
- [x] Confirm withdrawal popup - profiles autosuggest isn't working correctly (it maybe in Grant popup too) - looks like z-index isn't correct for profiles list
- [x] Invoices: Change translations: 
Commissionaire / Committent -> Payee / Payer
Percentage / Installment -> Percentage / Fixed fee
Add Commission -> Add Monthly Comission
- [x] Invoices: Add settings for 'Issue Date', 'Due date', 'Expiration notification'

**Comment by AntonLV** [comment]
Re 2: Withdraw request email template (bx_credits_withdraw_requested) already has the `message`:
```
{email_header}
<p><a href="{profile_link}">{profile_name}</a> requested to withdraw <b>{amount}</b> credits from his/her balance.</p>
<p>{message}</p>
<p>Current withdraw conversion rate is <b>{rate}</b></p>
{email_footer}
```

**Comment by AntonLV** [comment]
Re 3: Sometimes ago z-index of Modal Popup was increased. So, similar problem should be actual for all popups with auto-suggestion field.
