### ISSUE TITLE
Channels improvements

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3410]
- [x] Remove this settings - "number of items in friends block" - but check first if it's used anywhere
- [x] Comments with hashtags aren't displayed in channels, however comments were integrated into Timeline already
- [x] Add followers block enabled by default
- [x] Add the following description for "add channel auto" action - __Automatically create new channel when new hashtag is mentioned by anyone with this level__

**Comment by AntonLV** [comment]
3f6818a - Related commit for UNA 12.1.0
