### ISSUE TITLE
Group Module: member list page not responsive on mobile view

### ISSUE THREAD

**Issue by siremystic** [unacms/UNA#3412]
Unable to scroll sideways on member list page with paid subscription for group module in mobile view

**Comment by romanlesnikov** [comment]
@siremystic, please, specify direct link to page & issues screenshot

**Comment by siremystic** [comment]
https://goiwelkin.com/page/group-fans?profile_id=171
![Screenshot_20210622-014222](https://user-images.githubusercontent.com/47337635/122845287-43242a80-d2fb-11eb-8977-7ebcad0338d4.png)
