### ISSUE TITLE
Comments: allow authors and groups admins to delete comments

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3421]
- [x] Add admin setting to allow content author (for example photo or post author) to delete any comments (not edit, only delete) posted on their content page (for example post or photo page) - enabled by default
- [x] Add admin setting to allow group admin to delete (not edit, only delete) any comment in group and any comment in content posted into group context - enabled by default

**Comment by siremystic** [comment]
Should apply for all group based module (space, event, courses, organization)

**Comment by romanlesnikov** [comment]
@siremystic, please, specify direct link to page & issues screenshot

**Comment by AntonLV** [comment]
Related commit for v.12: 55f6c79
