### ISSUE TITLE
Unable to get the installation page of unaio

### ISSUE THREAD

**Issue by ali10086** [unacms/UNA#3428]
Team,

I am trying to install unaio on my local CentOS7 Server, For this, I have to download the zip file from the una.io site and extract it into my webserver, and following the instructions, but the issue is when I am hit the IP address into the browser it does not show me the installation required page it shows me the directories of the folders You can also see that in the image, but not show the installation page..

please help me I got now help from anywhere.

![3](https://user-images.githubusercontent.com/48508387/123418829-f8dccb00-d5d2-11eb-83db-de067fdf28f5.jpg)
![1](https://user-images.githubusercontent.com/48508387/123418837-fb3f2500-d5d2-11eb-9b7b-0b19403456bc.jpg)
![2](https://user-images.githubusercontent.com/48508387/123418840-fbd7bb80-d5d2-11eb-86e8-8f7ddfa08f07.jpg)

**Comment by ali10086** [comment]
Does no one have knowledge about this useless software?

**Comment by AlexTr** [comment]
@ali10086 most probably PHP isn't enabled on your local webserver.
Could you please ask question in forum - https://una.io/page/discussions-home thank you

**Comment by ali10086** [comment]
Sir, as per your guide I have installed it successfully on the windows
server with the installation of WAMP but I am not enabled to install it on
Centos 8, LAMP is already installed on this Linux machine.

is this application is made for windows, not for Linux? or its works
equally  Windows and Linux?
