### ISSUE TITLE
Friend requests(and some other) link can direct to incorrect page when both modules Orgs and Persons are used

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3431]
Other links such as Following, Followers, Relationships, Relationships With Me

It happens because of some overlapping checks in persons and org module, can be reproduced by changing order of links and switching to/from org/person profile

![y8xsayhjlyyzymltntapvimkvzetejgx](https://user-images.githubusercontent.com/3324866/123603825-989d9180-d83d-11eb-9490-c2622abb60d4.png)

**Comment by AntonLV** [comment]
Related issue #3408
