### ISSUE TITLE
Page Blocks: Instead of "empty", Make blocks hidden when there are no item(s) listed

### ISSUE THREAD

**Issue by siremystic** [unacms/UNA#3471]
![Screenshot_20210819-230459](https://user-images.githubusercontent.com/47337635/130150814-cc66c068-5f30-472b-8a7a-97dcf31f9878.png)
For some profiles with no followers/friends/items, blocks show empty when nothing is listed. This makes them useless and unnecessary on page view. Hence, they should be hidden when there's no item listed on block.

**Comment by AlexTr** [comment]
There are some blocks which aren't displayed when empty and some display "empty" message. It's made for purpose. However it can be changed by changing service call for the block in most cases, service call can be changed in Developer module.
