### ISSUE TITLE
Install issues via Softaculous

### ISSUE THREAD

**Issue by MerseyHostingHub** [unacms/UNA#3586]
Clients installing from Softaculous are getting an update message. When clicking it, the website gets a maintenance message saying the website is qued to be updated. The website then stays like this permanently.

If you delete the .bx.maintance file the website then produces a 505 error.

![screenshot-lgbtq tbrn org-2021 11 25-15_41_11](https://user-images.githubusercontent.com/95041892/143471514-612aa6b9-3b44-4856-b324-25a8420d8fae.png)

On another note on older installed websites, there is no message to upgrade. The developer app is not installed on the above website, so I believe it is on the stable channel.

![screenshot-www tbrn org-2021 11 25-15_43_18](https://user-images.githubusercontent.com/95041892/143471592-2b263e4d-76a2-43a7-aac5-07d7b2e9b0ed.png)

**Comment by AlexTr** [comment]
For some reason Softaculous installation has update channel set to Beta, it can be changed in Studio > Developer > Update Channel.
If you see 500 error after update, then most probably modules aren't updated, then go to Studio > Apps Market > Updates and apply all available updates.

**Comment by MerseyHostingHub** [comment]
Thank you I will inform my clients not to install via softaculous.

And although you say to upgrade the modules, there is no way to do that while the upgrade has locked the install to the maintenance page. And like I said when deleting the .bx_maintanance file the website is not accessible at all to upgrade the apps.
