### ISSUE TITLE
Showcase cards use low quality images, compared to regular cards

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3616]
It looks like several modules are affected:

**Persons:**
![ekxbgydfrget4mryh2sw7ay2cunbdyzn](https://user-images.githubusercontent.com/3324866/145959598-2ef57a9f-c322-4d4c-baa9-1352de144278.png)

**Events:**
![c8vg7nm4tarnuhd8fvzfwulugctsskcj](https://user-images.githubusercontent.com/3324866/146092913-2802252b-3753-4dd9-a653-e33f86a8e187.png)

**Comment by AntonLV** [comment]
Re: problem in Events
Cannot reproduce the problem in fresh installed UNA. UNA 13 has a counter of participants which is shown in Event card. This counter shows 16*16 icons. Looks like there no some CSS styles in the template or something wasn't completely updated. 

in Artificer:
![изображение](https://user-images.githubusercontent.com/3894360/147196422-55bd9e95-3994-4601-8d99-bf8402433af8.png)

in Pretean:
![изображение](https://user-images.githubusercontent.com/3894360/147196716-bfc91d18-d117-4ded-8350-d0200fd655db.png)
