### ISSUE TITLE
Ability to select multiple membership levels for privacy field.

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3636]
Make it to work similar to "Selected friends..." where in popup user can select multiple values.
https://una.io/page/view-discussion?id=9013

---

Additionally it would be great to allow to select membership levels in privacy field by membership action (like "use membership level as privacy") by default enabled for admins only instead of hardcoding it for admin only.

**Comment by AntonLV** [comment]
> Additionally it would be great to allow to select membership levels in privacy field by membership action (like "use membership level as privacy") by default enabled for admins only instead of hardcoding it for admin only.

Currently available single membership selection is already connected with 'Show membership levels in privacy groups' ACL action. By default it's allowed to Administrators only.
