### ISSUE TITLE
Settings Page - HTTP ERROR 500

### ISSUE THREAD

**Issue by SonicWeekly** [unacms/UNA#3680]
Version: 13.0.0-A2 - currently, when navigating from Studio to Settings page, the page returns an HTTP Error 500 message.  I've used multiple browsers, cleared cache, etc - all tries same result.  I just deployed this Beta version (2-12-22).

**Comment by AlexTr** [comment]
HTTP ERROR 500 usually means some server error please check web-server error log files for the particular error

**Comment by SonicWeekly** [comment]
Thanks...will explore further
