### ISSUE TITLE
New conversations alert counter is incorrect

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3720]
![image](https://user-images.githubusercontent.com/3324866/160059285-0b1e7714-ffe3-47b8-ae27-397fa562d75b.png)

![image](https://user-images.githubusercontent.com/3324866/160059305-1bfdf790-ac30-4bca-a251-a47e24f326ef.png)

**Comment by AntonLV** [comment]
Looks like the problem isn't in Conversations but in Artificer.

1. In Artificer:
![изображение](https://user-images.githubusercontent.com/3894360/160120757-ecd31dc5-93e7-43bf-8636-93d9fd2388c2.png)

2. In Protean:
![изображение](https://user-images.githubusercontent.com/3894360/160120905-1bb02925-fe42-4c55-ba9e-0b0c2d903540.png)

Something doubles the counter in Member Toolbar in Artificer.
