### ISSUE TITLE
Ads icon isn't displayed in Artificer

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3745]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/3324866/163140957-f70f5119-a014-45a0-b0bb-705eecab0789.png">

**Comment by AntonLV** [comment]
Cannot reproduce neither on Demo nor on Dev.
![изображение](https://user-images.githubusercontent.com/3894360/163179038-2217b6b3-676b-412c-b070-a0e9f974ff70.png)
