### ISSUE TITLE
Timeline & Charts: error when deleting events

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#3788]
Query:
INSERT INTO `bx_charts_most_active_profiles` (`object_id`, `profile_module`, `content_module`, `create_count`) SELECT `sys_profiles`.`content_id`, `sys_profiles`.`type`, 'bx_timeline' , COUNT(`bx_timeline_events`.`id`) FROM `bx_timeline_events`

INNER JOIN `sys_profiles` ON `sys_profiles`.`id` = `bx_timeline_events`.`object_owner_id` WHERE sys_profiles.type='bx_organizations' AND `bx_timeline_events`.`added` > 1650675602 GROUP BY `sys_profiles`.`content_id`, `sys_profiles`.`type` ORDER BY COUNT(`bx_timeline_events`.`id`) DESC LIMIT 0,4

Mysql error:
Unknown column 'bx_timeline_events.added' in 'where clause'

Location:
The error was found in query function in the file /var/www/vhosts/mainsite/html/modules/boonex/charts/classes/BxChartsDb.php at line 60.

**Comment by karina09877** [comment]
Is there a solution for this yet?
