### ISSUE TITLE
Unlike not possible for Contexts

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#3856]
Example: you can Like and Unlike Photos or Discussions, but you can only Like Groups or Organizations and cannot Unlike them.

**Comment by AntonLV** [comment]
By default Content modules use Reactions based Voting while Context modules - Like based one. 
By default Unlike is disabled in Like based Voting. It can be enabled via DB.

**Comment by AntonLV** [comment]
Reactions will be integrated in Contexts (Profiles/Groups based modules) in the next major UNA version: Ticket #3873.

**Comment by AntonLV** [comment]
The possibility to do Unlike is controlled with `IsUndo` field in `sys_objects_vote` table.
