### ISSUE TITLE
Artificer: fix design in Favorite folders View: 

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#3865]
Favorite folders View: fix design

**Comment by AntonLV** [comment]
Could you please provide more detailed description of which "Favorite folders" you are talking about. 
Folder are available in Files module but Favorited files are looking fine.

**Comment by kisonik** [comment]
Here is how it currently looks like:
https://us-east-1.linodeobjects.com/una/bx_messenger_photos_resized/f/fm/fmj/fmjjg6wdjl9qp8vpsjnr8aycqywpcei9.png

**Comment by kisonik** [comment]
At least make like in Protean
![image](https://user-images.githubusercontent.com/8243165/172368879-d99c5682-1782-4d03-83c0-8096210ca728.png)
