### ISSUE TITLE
Navigation Builder: implement on-hover field (enhancement)

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#3874]
For example, useful for cards to differ categories from labels

**Comment by AlexTr** [comment]
@kisonik please describe it in more details

**Comment by kisonik** [comment]
Example: 
![изображение](https://user-images.githubusercontent.com/8243165/175861792-42ad5c74-5f5c-4340-b931-c0e49a717d01.png)
When you hover your mouse over this menu item, you would be able to see the full text (Resources).
Also, on cards, if there is a lot of info, you could hover your mouse over each "link" and see what exactly it is: Date of joining, Tags, Membership, etc.

**Comment by AlexTr** [comment]
it should be fixed in https://github.com/unaio/una/issues/3901
