### ISSUE TITLE
disable_functions = mail,dll - FAIL

### ISSUE THREAD

**Issue by takomlii** [unacms/UNA#3880]
I am encountering this error `disable_functions = mail,dll - FAIL `during installation. My hosting is preventing this, how can I get around this in other ways. I need to use the mail system with SMTP.

**Comment by AlexTr** [comment]
That's correct, if you will use SMTP Mailer module, then php `mail` function isn't used, I've just removed this requirement in above commit.

**Comment by takomlii** [comment]
Yes, I see you organize the code. First of all, I have to thank you for this. However, there is another problem. The code is only updated on Github repo. When the source is downloaded from the official website, the same error continues there. Please don't miss this either. I would be glad if you add me as Contributor. Hahaha, it was a joke.

**Comment by AlexTr** [comment]
This fix will be included in the next official update. For a while you can apply this fix manually.
