### ISSUE TITLE
Recurly payment provider: PHP library absent

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#3892]
Warning: require_once(/home/boonclub/public_html/igorl/plugins/recurly/recurly.php): failed to open stream: No such file or directory in /home/boonclub/public_html/igorl/modules/boonex/payment/classes/BxPaymentProviderRecurly.php on line 12

**Comment by AntonLV** [comment]
BitPay, 2Checkout and Recurly integrations are just groundworks and cannot be used.
