### ISSUE TITLE
Events: the "Guest" tab generates some warnings 

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#3965]
like 
Warning: Undefined array key "date_start" in [path_to_UNA]modules/boonex/events/classes/BxEventsMenuViewActionsAll.php on line 30 Call Stack

**Comment by AlexTr** [comment]
Fixed in https://github.com/unaio/una/commit/cd96f5df66999b5cc5067b47a39f00a5a43c39cb
