### ISSUE TITLE
Quill: Right align doesn't work.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4018]
1. In editor
![изображение](https://user-images.githubusercontent.com/3894360/186833080-56129aff-7f43-43b5-bd8d-18ead23bc439.png)

2. On the page
![изображение](https://user-images.githubusercontent.com/3894360/186833171-02db184c-003e-43ed-b948-a0a2a342aa82.png)

Paragraph has 'ql-align-right' class but it doesn't work.

**Comment by romanlesnikov** [comment]
fixed by https://github.com/unaio/una/issues/4020
