### ISSUE TITLE
Payments: Add support for multi-currency

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4090]
- [x] 1. Seller should be able to select the preferred currency which should override the default one selected in Studio -> Payments -> Settings.
- [x] 2. Currency should be saved for each transaction separately. It's essential for making statistical data correct if a seller changes his current currency. 

t.26110418

**Comment by goiwelkin** [comment]
Add field in studio settings to add currency exchange rate against default currency (USD), so when seller changes to another currency (say GBP) then the value will change in default currency (USD) for the buyer according to the set exchange rate in payment cart.

**Comment by AntonLV** [comment]
1. UNA uses a list of currencies which may very depending on the activated payment provider(s). It means that a number of setting will be needed. 
2. From the other hand exchange rate is permanently changing. So, the static setting won't work. 
So, a seller should select necessary currency for himself and create products in accordance with the selected currency.

**Comment by goiwelkin** [comment]
This is fine for regular card payment provider that are able to process payment according to the currency code...but sadly this doesn't work for internal wallet providers like credit or points wallet.
For providers like paying with credit, it doesn't recognize the currency used by the seller other than the default currency. From current test, Say default is in USD and seller changes to GBP, the credit provider ignores the seller currency GBP and still processes it as USD.

So perhaps there's a way to add exchange rate settings for internal wallet providers (credits/points)

**Comment by AntonLV** [comment]
> So perhaps there's a way to add exchange rate settings for internal wallet providers (credits/points)

Here I agree with you. For Creadits module we need to add multi-currency support, that admin may speciafy conversion rates for all currencies. I've updated the ticket #4113. Thanks.
