### ISSUE TITLE
Block from unaio/una-vendor-test isn't listed 

### ISSUE THREAD

**Issue by pavelarts** [unacms/UNA#4124]
Hi. 

I'm running Una 12, and I have downloaded and installed unaio/una-vendor-test module. Then, I disabled caching via studio and created a new page. On the new page, I attempted to add a block from the test module, but I wasn't able to find it in the list of available modules and blocks. I expected to see block 'Test' which would render results from this code here https://github.com/unaio/una-vendor-test/blob/master/test/classes/VndTestModule.php#L20-L24

Please advise what I'm doing wrong and how to create my own block which can be added on pages?

**Comment by AlexTr** [comment]
You need to add 'service' block as described here - https://github.com/unaio/una-vendor-test/wiki/Page-Creation
If you have more questions please add discussion  here - https://una.io/discussions-home
