### ISSUE TITLE
Nginx doesn't support WebRTC

### ISSUE THREAD

**Issue by olariuromeo** [unacms/UNA#4146]
"Streaming section
Server Software - live streaming server, for now only [Nginx](https://github.com/arut/nginx-rtmp-module) and [OvenMediaEngine](https://www.ovenmediaengine.com/ome) are supported. **Nginx doesn't support WebRTC**, so you can't broadcast from the browser, for now only OvenMediaEngine supports WebRTC and streaming from the browser."

Maybe nginx does not support WebRTC although I have seen some implementations available even here on github but openresty can do this very well.  https://github.com/atyenoria/janus-webrtc-gateway-docker 

We can implement something like this for one or we have to pay a license to OvenMediaEngine  for streamining in UNA?

**Comment by AlexTr** [comment]
Thank you, but this is just a docker image for Janus WebRTC server.
