### ISSUE TITLE
Build-in API support

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4148]

**Comment by AntonLV** [comment]
Related commit 954d8fb

**Comment by AlexTr** [comment]
https://github.com/unaio/una/commit/8b05861920b76aeab049425578376bd8feb57af1#diff-6b29b1b2cbb8ac485ba4bb398c56b48bb7f20dc28407125cc2a5181fa8976c8d - implement in system update script

**Comment by AntonLV** [comment]
Related commit 67df987

**Comment by AntonLV** [comment]
Related commit 4e791d5

**Comment by AntonLV** [comment]
The first commits in UNA 13 - RC6 are 6573d83 and 54fd8ae

**Comment by AntonLV** [comment]
Related commits: d534d9f, ee0fb06 - Build-in API support: Browse connections (everywhere).
