### ISSUE TITLE
Ads: Auction mode issue and improvements

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4175]
1. Owner posts a product, Stock 100
2. Buyers can make an offer, with any amount of items AND money, that works well
3. Owner can see the offers in notification/add-offers
4. Owner can accept an offer and if so, the Problems/Bugs start:
5. Problems:

- The '_sys_status_offer' missing key on 'ads-manage/my-ads' page.
- The Product is no longer listed in the shop, even if the stock is filled well
- The Product's stock does not change correctly
- The Counter in the Category shows the wrong number of items.

6. Update 'Shipped' and similar language keys (in action buttons) to say 'Mark as Shipped'.

**Comment by goiwelkin** [comment]
In addition, Say items were 100 items stocked and a buyer makes an offer with certain number of items and amount. When offer was accepted and buyer pays for items accepted......the "accept offer block" continues to be visible for the buyer after payment, allowing the buyer to repurchase items using a previous offer agreement. This is incorrect working (especially when seller price had changed in the future). 

Solution: Accepted offer should be cancelled automatically after buyer's payment and "accept offer block" should be hidden.... allowing buyer to make new offer to seller which is subject to new acceptance of offer.
![Screenshot_20221231-235118](https://user-images.githubusercontent.com/83794437/210157007-58179226-6014-4acd-8b51-1994887bdf37.png)

**Comment by goiwelkin** [comment]
Review: 'Mark as Shipped' and 'Mark as Recieved' button are not dispayed in the actions view button on frontend, even though they are activated in navigation app in studio
