### ISSUE TITLE
Forum: Visualize pinned post in browsing list.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4232]
1. Like this:
![изображение](https://user-images.githubusercontent.com/3894360/220095492-2bb9289b-2787-48cf-b53c-75f4a9df3a5c.png)

3. Do the same for Locked posts.

**Comment by AlexTr** [comment]
No Russian translation
<img width="513" alt="image" src="https://user-images.githubusercontent.com/3324866/220192609-bedd5c2b-be6b-4c83-8719-c82437d9e259.png">

Also second point isn't addressed

**Comment by AntonLV** [comment]
1. There was a mistake in Russian lang key. Fixed.
2. Locked indicator is hidden by default. 
![изображение](https://user-images.githubusercontent.com/3894360/220278536-3f867a61-f94c-4864-b436-220ba524bd8a.png)
