### ISSUE TITLE
Card titles are cut from the beginning if they don't fit

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4259]
https://una.io/cmts-view/1e5epqm?sys=bx_forum&cmt_id=43969

**Comment by AntonLV** [comment]
I cannot reproduce the issue on clean UNA site.
![изображение](https://user-images.githubusercontent.com/3894360/223412441-c67e71dc-7abd-4b6c-93c7-66b534aeca6b.png)

**Comment by AlexTr** [comment]
@AntonLV it can be reproduced in Protean, Decorous and Ocean templates, for example:
https://una.io/events-home?skin=protean&mix=12
