### ISSUE TITLE
Notifications for invites to Closed or Secret Organizations don't get sent

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4280]
https://una.io/d/notifications-for-invites-to-closed-or

**Comment by AntonLV** [comment]
I cannot reproduce the problem neither on CI.UNA.IO nor on my dev site.
![изображение](https://user-images.githubusercontent.com/3894360/228538850-9173c2a2-88b5-4717-9dc7-7c7463308b39.png)
