### ISSUE TITLE
Permissions: the max file size limit doesn't work with the profile pictures upload

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#4316]
The initial thread https://una.io/d/upload-limit-for-profile-pics

The profile pictures from the profile edit area can exceed the maximum size of the uploaded files setup in the Permissions app without any warnings / blocks.

**Comment by AlexTr** [comment]
Can't reproduce, it works, but error message isn't properly shown - https://github.com/unaio/una/issues/4324
