### ISSUE TITLE
Using template Artificer or Lucid fresh instalation 13rc6

### ISSUE THREAD

**Issue by olariuromeo** [unacms/UNA#4327]
Warning: file_get_contents(//post.css): failed to open stream: No such file or directory in /var/www/13rc6./inc/classes/BxDolTemplate.php on line 2468

Notice: Undefined index: dirname in /var/www/13rc6/inc/classes/BxDolTemplate.php on line 2465

Notice: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in /var/www/13rc6/inc/classes/BxDolTemplate.php on line 2468

**Comment by AlexTr** [comment]
Could you please describe how to reproduce this issue ?

**Comment by olariuromeo** [comment]
fresh instalation and after i use dolphin migrate script i get this error
