### ISSUE TITLE
Quill: Image centering issues

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4330]
- [x] Centering isn't saved. To reproduce:
1. Inline image(s) in editor.
2. Use centering feature.
![изображение](https://github.com/unaio/una/assets/3894360/22154692-f4e8-4d31-880a-f045b6e1a10b)
3. Save.
4. Return back to editing.
![изображение](https://github.com/unaio/una/assets/3894360/f96dd4f8-7166-464a-8412-f61ae0800ecd)

- [x] Last image in the list isn't centered at all. 
![изображение](https://github.com/unaio/una/assets/3894360/efc6f346-e13c-4a82-8215-2241969c9d32)
But in the editor all images were centered.

**Comment by AlexTr** [comment]
https://una.io/d/quill-editor-alignment-of-elements-in
