### ISSUE TITLE
Page Cover

### ISSUE THREAD

**Issue by AlexT-UNA** [unacms/UNA#434]
Improvements for Page Covers

- [x] Set to height to 40vh.
- [x] The picture for Page Cover. When we upload one via Designer, it should support retina/@2 resolution and have Cropper in uploader.

**Comment by AlexT-UNA** [comment]
I disagree with this options since they aren't obvious. We should keep it as simple as possible, sometimes it's better to cut the image on user side instead of adding a lot of options. 
We can remove some setting, but we should think twice before adding settings!

**Comment by andreyasko** [comment]
Updated, and removed settings.
