### ISSUE TITLE
Fresh Docker results in "Failed to open stream"

### ISSUE THREAD

**Issue by Eonasdan** [unacms/UNA#4342]
I just pulled the latest master and ran the docker compose. I'm getting this message hitting `http://localhost/install/index.php`

![image](https://github.com/unaio/una/assets/1006516/4b62526d-010f-4cd0-9496-010493f29ae0)

The file does seem to exist

![image](https://github.com/unaio/una/assets/1006516/5e61d2e9-a6da-4d3c-b429-b0a65ef4c9b3)

**Comment by shihab-uddin24** [comment]
i got same issue. are you fixed it?

**Comment by AlexTr** [comment]
In the repository there is dev version, which could contain bugs and incomplete features, also dependences need to be installed with php composer, this is the reason you have missing files.
For production installation please use ready build from Releases section.
