### ISSUE TITLE
UNA GitHub version installation problem in XAMPP

### ISSUE THREAD

**Issue by tasinone** [unacms/UNA#4354]
When I try to install the UNA after downloading it from GitHub on XAMPP, it is showing me the below error in installing page. But the one I have downloaded from the una.io website isn't showing any error. why is it happening?

<a href="https://ibb.co/dLby8wC"><img src="https://i.ibb.co/SdQpF4Y/Screenshot-18.png" alt="Screenshot-18" border="0"></a>

**Comment by tsgarrett** [comment]
I just saw this, so likely you've figured it out, but if not read on.  The plugins directory only contains an .htaccess file in the download from Github. The UNA download has the autoload.php file as well as a composer directory. Sorry if I was too late to be of any help!

**Comment by DFilyushin** [comment]
I confirm problem with file autoload.php. Example from vps and running docker-compose:
![image](https://github.com/user-attachments/assets/d5402219-8739-458b-9326-2af89167158a)

**Comment by DFilyushin** [comment]
Manual resolution for issue is copy directories from `upgrade/files/{version}/files/plugins/*`

**Comment by AlexTr** [comment]
It looks like you are using source code from the repo - code in the repo is work in progress, not upgradable and intended for preview only - please use ready build packages from **Releases** section.
