### ISSUE TITLE
Timeline optimization (speed improvements enhancements)

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#4367]
- [x] 1. remove double query
- [x] 2. remove DAYOFYEAR\
- [x] 3. change LEFT join to INNER join
- [x] 4. remove ISNULL(`sys_profiles`.`status`) OR
- [x] 5. remove distinct in every subquery, use one insead of

**Comment by AntonLV** [comment]
'double query' is used for Live Updates. It's executed during the first loading and cached. Also it's a different query then the main one.
