### ISSUE TITLE
Update file uploader

### ISSUE THREAD

**Issue by AlexT-UNA** [unacms/UNA#437]
Uploader UI is outdated and the script isn't well supported anymore. Update to a new one.

Also old uploader doesn't support uploading files by chunks, as the result it is impossible to upload big files.

https://una.io/page/view-discussion?id=593

Consider to use this ones:
http://www.dropzonejs.com/
https://uppy.io/
https://pqina.nl/filepond/

**Comment by AlexTr** [comment]
https://github.com/unaio/una/issues/1354
