### ISSUE TITLE
Birthday

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#4391]
Currently says it's a compulsory field, but form validates without it.

Also calendar needs theming in dark mode

<img width="535" alt="image" src="https://github.com/unaio/una/assets/22210428/16fa8a76-7d03-4f64-8ec6-95be9319a6fe">

**Comment by andreyasko** [comment]
Also, after reloading the Birthday field looks empty even though value is stored.

**Comment by andreyasko** [comment]
IN fact on each "edit", birthday triggers "required". We should include it as required field in default disto on Join, not just edit.

**Comment by AntonLV** [comment]
> Currently says it's a compulsory field, but form validates without it.
> IN fact on each "edit", birthday triggers "required". We should include it as required field in default disto on Join, not just edit.

If 'birthday' field will be required with validation, "Auto-create Person profile on Join" will stop working because Create account form doesn't have birthday field.

**Comment by AntonLV** [comment]
> Also, after reloading the Birthday field looks empty even though value is stored.

Fixed here: #4658
