### ISSUE TITLE
In Guest=mode - gap above feed

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#4393]
Looks like space reserver for create post form, results in extra padding in guest =mode

<img width="1839" alt="image" src="https://github.com/unaio/una/assets/22210428/e2a3074d-2730-4df1-b35b-5a40438fe80c">

**Comment by AntonLV** [comment]
Issue appears only when Async mode is enabled. It appears because block's placeholder is loaded with initial page loading but afterwords there is nothing to load in the block.
