### ISSUE TITLE
Files: Update placeholder images

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4398]

**Comment by andreyasko** [comment]
for new file images - go to [ph](https://phosphoricons.com) - search for "file" in icon search - it gives various options for different types of files - use duotone style, svg format. 

<img width="1480" alt="image" src="https://github.com/unaio/una/assets/22210428/9851cdf1-1864-41f4-893b-df83319cf515">

**Comment by andreyasko** [comment]
So it would look like this:

<img width="221" alt="image" src="https://github.com/unaio/una/assets/22210428/995df2fb-6308-4cde-97a5-16216a5fb6ff">
