### ISSUE TITLE
Dark mode text and border styling in forms

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#4401]
The text and internal borders in dark mode is not using correct color:

<img width="524" alt="image" src="https://github.com/unaio/una/assets/22210428/eca54ad8-feba-4da7-9d2e-dc0cba6ec04a">

**Comment by AntonLV** [comment]
Issue appears in Join form inlined in Splash page only.
Standalone join form listens for Dark mode correctly.
![изображение](https://github.com/unaio/una/assets/3894360/649e2cdb-893f-4321-bdfd-6f3b821a0457)
