### ISSUE TITLE
Change email templates to simple text with logo.

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#441]
Emails formatted with similar HTML tend to quickly trigger Gmail's filters that put them into "Updates" or "Social" tabs instead of Primary, reducing open rates. Best practice is to send emails that look like normal personal emails as much as possible.

So, we need to remove the html box and formatting, and send a simple email, embedding only the site logo in top left corner (@2 resolution/retina) and using the site font-stack and button style for styling.

Like so:

![image](https://cloud.githubusercontent.com/assets/22210428/19144847/86dd9c70-8bf7-11e6-987b-8b4723a56150.png)

**Comment by AlexTr** [comment]
I think that google make decision based on email content, not the formatting.

I think it's better to not use logo in emails by default, since many email clients still block images in emails by default and all emails will look ugly.

I think our current variant is pretty good.

**Comment by andreyasko** [comment]
Some of the tips on landing email int primary:

"Write Email with HTML Editor Without Using Pre-designed Templates"

"put not more than two links inside your email, and if possible keep only one."

"Try just a plain text or HTML without images. That worked for me."

"keep your emails simple and just like as person-to-person conversation."

SO, yes, I would agree that Logo in email header is a bad idea. But I would also remove our white-box on grey background, as it look much like a template, and will be picked up quickly by google considering how many sites send the same to their users. 

We could use the logo in a small form at the bottom of the email, which would make it look like a signature component, which doesn't see to trigger the filter. 

For example emails like this fall into my primary tab all the time:

![image](https://cloud.githubusercontent.com/assets/22210428/19172175/324f7870-8c6c-11e6-90b6-603f1f41ab53.png)

or this 

![image](https://cloud.githubusercontent.com/assets/22210428/19172209/5971ed34-8c6c-11e6-9942-7f946fced9f1.png)

SO, I suggest, plain text with one link, and the signature like:

**Thank you!**
**Site name**
**logo**

**Comment by AlexTr** [comment]
Ok, let's use simple email without any template and without logo.

**Comment by AlexTr** [comment]
It's better to not use logo even in the footer because:
- it make no sense to remove formatting to not mark email as spam, and then include an image to make more chances to mark as spam again
- some logo is specifically designed for dark background and will not be looking good here, even some logo images are white and will not be seen at all

**Comment by AlexTr** [comment]
I think email header/footer is implemented the wrong ways, actually we don't need to disable it, we need to be able to change it!

I would suggest to store email header/footer as regular language keys. So, to change it, language keys must be edited. When implementing, make sure that the proper parameters are passed there for replacing, including unsubscribe link. By default it should be the current email header/footer.
