### ISSUE TITLE
Search Result pagination issue.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#442]
Category browsing pages generate wrong pagination links. The issue can be seen here: https://una.io/searchKeyword.php?cat=bx_market_cats&keyword=32&section[]=bx_market
On this current page the issue appears because cat=bx_market_cats param isn't attached to pagination URL.

**Comment by AlexTr** [comment]
Иногда кажется что пашет, но прикол в том что он делает обычный поиск по КИВЕРДУ в тексте и находя просто 2 где-то в полях ТАйтл или Текст он думает что нашел то что нужно.

It looks like `cat` parameter isn't passed when you navigate through the pages.
