### ISSUE TITLE
Modify notifications letters

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#4432]
![image](https://github.com/unaio/una/assets/12896257/07aafe6f-0e6c-4824-a30a-a11215c68286)

If entire subject line > 60 characters, cut off to sixty chars (including ellipse (" ..."))
"Weave notification: Paityn P mentioned you in a comment" is 58 chars, so no abbreviation needed
If limit exceeded, would look like "Weave notification: Paityn P mentioned you in a ..."

**Comment by AntonLV** [comment]
Done in this issue https://github.com/unaio/una/issues/4412

**Comment by AlexTr** [comment]
Notification title has html entity code at the end if it's long:
<img width="456" alt="image" src="https://github.com/unaio/una/assets/3324866/6cfb7148-2781-48a6-a633-7846540eb4bb">
<img width="1078" alt="Screen Shot 2023-08-22 at 20 18 14" src="https://github.com/unaio/una/assets/3324866/e72fec28-419d-4c8e-943b-7f0a336afe72">

**Comment by AntonLV** [comment]
Fixed in original ticket  #4412
