### ISSUE TITLE
Remove empty tags from html content 

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#4486]
#4203

in bx_process_output
$s = preg_replace("/(((<\w+>)+[ \n(<br>)]*(<\/\w+>)+)+)|<br>/", '', $s);  

`<p><a href="https://www.psychologytoday.com/ca/blog/all-is-well/202308/what-if-your-doctor-actually-talked-with-you" rel="noopener noreferrer" target="_blank"><strong>Psychology Today<br></strong></a></p><p>In an insurance-driven market, patients and practitioners seldom truly interact.</p>`

**Comment by AntonLV** [comment]
Check cases with `IMG` and `VIDEO` tags.
