### ISSUE TITLE
Forms builder: date field

### ISSUE THREAD

**Issue by AlexT-UNA** [unacms/UNA#449]
For now for date fields unix timestamp field format is used, but don't allow dates earlier than 1 January 1970, so it's not possible to create field for date of birth.
I think we need to add some selector for date field to allow to save it as unix timestamp or as regular date field.

**Comment by AlexTr** [comment]
@AntonLV  There is still problem with displaying such field.

**Comment by AlexTr** [comment]
1. When value is empty this field shouldn't be displayed on profile view:

![screen shot 2017-06-23 at 1 54 32 pm](https://user-images.githubusercontent.com/3324866/27479449-a806c740-581c-11e7-81b5-6e00108dcb73.png)


2. It display some notices when value is empty:
```
Notice: Undefined index: value in /path/una/template/scripts/BxBaseFormView.php on line 320
Notice: Undefined index: value in /path/una/template/scripts/BxBaseFormView.php on line 326
```
3. `sys_format_date` & `sys_format_datetime` params should be used to format the date and datetime
