### ISSUE TITLE
Comments: 'See more' link doesn't show on the forum's comments page

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4506]
when comment is opened on separate page, for example:
https://una.io/cmts-view/3xqt4y?sys=bx_forum&cmt_id=46272

<img width="765" alt="image" src="https://github.com/unaio/una/assets/3324866/3c31310e-34c7-430b-b207-8f1e01f6069a">

**Comment by AntonLV** [comment]
Duplicate for https://github.com/unaio/una/issues/4505
