### ISSUE TITLE
Quill: Issue with text wrapping

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4524]
1. When Bulleted list is used everything is OK.
![изображение](https://github.com/unaio/una/assets/3894360/2a1de0a4-6c48-40c5-973d-d4590d6d9b5f)

2. Issue appears when new line or Numbered list is used.
![изображение](https://github.com/unaio/una/assets/3894360/d12d1908-b1bd-4da0-8e14-2b81169a0ded)
![изображение](https://github.com/unaio/una/assets/3894360/16faba27-5c7b-471a-9356-003451e176e5)

**Comment by romanlesnikov** [comment]
already fixed in another
