### ISSUE TITLE
Quill: Hashtag selector issues.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4525]
1. Limit the number of displayed hashtags.
![изображение](https://github.com/unaio/una/assets/3894360/ee278264-62ee-44b5-bbaf-54cd05ca6885)
2. If there is a lot of hashtags then they should be scrollable in the popup (_AlexT - I think NO scroll is needed here, just limit max number of hashtags to 10-20 items, if particular tag is needed then more letters can be typed to get shorter list of suggestions_)
3. It's better to use popup below the text.
![изображение](https://github.com/unaio/una/assets/3894360/eee08bc1-208f-456c-a62d-9ce7bdf5da89)

m. 913920

**Comment by romanlesnikov** [comment]
depend on sys_profiles_search_limit, like mentions
