### ISSUE TITLE
Subscriptions/Billing Management 

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#456]
"Subscriptions" should have their own management page. Similar to "Shopping Cart" page.
Submenu shows 3 pages:

Manage Plans / Payment History / Billing Information

**Manage Plans**
Grid list with columns:

Plan |  Price | Period | Next Billing |  [edit column]
Business | $800 | Monthly | 12.09.2916 | [@]

The edit button should show menu with options:

- Switch to another plan
- Change payment method
- Change billing period
- View payment history
- Request cancellation

**Payment History**
Grid list with columns:

Dropdown with "All plans / Plan A , Plan B, etc"

Plan | Amount | Date
Business | $800 | 12.09.2916

**Billing Information**
Grid list with columns:

Status | Payment Method |   [edit-column]

(0  ) |  Visa (via Stripe) |  [@]

(  0) |  PayPal |  [@]

**Comment by AntonLV** [comment]
Need to realize Subscription Change for Stripe integration.
