### ISSUE TITLE
ACL: wrong sql queries data returned from getContentByLevelAsSQLPart

### ISSUE THREAD

**Issue by AlexeyUna** [unacms/UNA#4564]
function **getContentByLevelAsSQLPart($sContentTable, $sContentField, $mixedLevelId)**

If to pass last parameter $mixedLevelId as array with only **Standard** level like - [3] it returns sql parts to build query:

```SELECT `sys_profiles`.`id` FROM `sys_profiles` LEFT JOIN `sys_acl_levels_members` AS `tlm` ON `sys_profiles`.`id`=`tlm`.`IDMember` INNER JOIN `sys_profiles` AS `cblasp_p` ON (`sys_profiles`.`id`=`cblasp_p`.`id`) INNER JOIN `sys_accounts` AS `cblasp_a` ON (`cblasp_a`.`id`=`cblasp_p`.`account_id`) LEFT JOIN `bx_persons_data` as `pd` ON `pd`.`id` = `sys_profiles`.`content_id` AND `sys_profiles`.`type` = 'bx_persons' WHERE 1 AND (`tlm`.`DateStarts` IS NULL OR `tlm`.`DateStarts` <= NOW()) AND (`tlm`.`DateExpires` IS NULL OR `tlm`.`DateExpires` > NOW()) AND `tlm`.`IDMember` IS NULL AND `cblasp_a`.`email_confirmed` != 0```

this query returns 98 records.

If to pass array [3, 8] function returns queries parts to build query:

```SELECT `sys_profiles`.`id` FROM `sys_profiles` INNER JOIN `sys_acl_levels_members` AS `tlm` ON `sys_profiles`.`id`=`tlm`.`IDMember` INNER JOIN `sys_profiles` AS `cblasp_p` ON (`sys_profiles`.`id`=`cblasp_p`.`id`) INNER JOIN `sys_accounts` AS `cblasp_a` ON (`cblasp_a`.`id`=`cblasp_p`.`account_id`) LEFT JOIN `bx_persons_data` as `pd` ON `pd`.`id` = `sys_profiles`.`content_id` AND `sys_profiles`.`type` = 'bx_persons' WHERE 1 AND `tlm`.`IDLevel` IN (3,8) AND (`tlm`.`DateStarts` IS NULL OR `tlm`.`DateStarts` <= NOW()) AND (`tlm`.`DateExpires` IS NULL OR `tlm`.`DateExpires` > NOW()) AND `cblasp_a`.`email_confirmed` != 0``` 

which returns only 2 records, but there are should be more then 98, because it contains first query data also.

**Comment by AlexTr** [comment]
@AlexeyUna 
Standard membership is special default membership when user don't have any membership levels attached, for some reason this function returns all confirmed profiles when level id is specified as single value. 
It's not very correct behaviour, but let it stay as it is for now, since it maybe some code which rely on this functionality.
