### ISSUE TITLE
Search is not work (ex https://una.io/searchKeyword.php)

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#4568]

**Comment by AntonLV** [comment]
I cannot reproduce the problem.
1. Site search popup.
![изображение](https://github.com/unaio/una/assets/3894360/e8e62723-b89e-43f8-a60b-28d8f54ce5e9)

2. Search by Keyword page.
![изображение](https://github.com/unaio/una/assets/3894360/e757a00f-89e6-40ca-940f-e443ec967ae2)
