### ISSUE TITLE
Comments: change order in replies to ASC for all cases 

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#4569]
m.916383

**Comment by AntonLV** [comment]
By default we already have Oldest first for replies, the same as for root comments.
![изображение](https://github.com/unaio/una/assets/3894360/803c3a18-8264-45e8-ac82-f38d783ec221)
'Oldest/Newest' switcher just changes the disaplying frame without changing the order itself.
![изображение](https://github.com/unaio/una/assets/3894360/2a132de7-0379-4460-ad80-270ff842d5b9)
