### ISSUE TITLE
Forms: errors (and maybe info) for fields aren't displaying HTML properly

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4585]
<img width="531" alt="image3" src="https://github.com/unaio/una/assets/3324866/cdf302da-bc8c-4305-bc74-22331c051ec7">

**Comment by AntonLV** [comment]
Info is OK.
![изображение](https://github.com/unaio/una/assets/3894360/7ca4fde7-9f33-4497-a5f4-a05e383545b7)

**Comment by AntonLV** [comment]
Error is OK too.
![изображение](https://github.com/unaio/una/assets/3894360/6a1dea39-4be4-40b6-8cb6-a0e822054078)
