### ISSUE TITLE
Notification unread label inconsistency 

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4600]
https://una.io/d/the-blue-dot-in-una-notification

It's really strange behaviour, usually 'blue dot' should indicate unread state, then when notification is read/clicked/etc blue dot should not be shown. Or should be some other indication.

Also it maybe unread state should correlate with notifications counter.

**Comment by AntonLV** [comment]
1. Currently **unread** notifications are highlighted like below:
![изображение](https://github.com/unacms/una/assets/3894360/16bbfb30-db27-4e55-a87c-7220ee1fb009)

2. Blue Dot is a 'clicked' indicator. This feature is enabled via Studio -> Notifications -> Settings and it disabled by default.
![изображение](https://github.com/unacms/una/assets/3894360/1705a116-76fa-4769-ae87-e742adf96170)
![изображение](https://github.com/unacms/una/assets/3894360/7b898e47-0dad-4fa2-8acb-bf36031b8c6b)
May be we need to change the icon to checkmark or so.
