### ISSUE TITLE
Calendar picket dark mode not switching

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#4613]
CAlendar picker needs to switch to dark theme with dark mode on

<img width="449" alt="image" src="https://github.com/unacms/una/assets/22210428/dea03163-b153-44d7-8618-96c4eee44ad8">

ideally, replace with https://flowbite.com/docs/plugins/datepicker/ - we have al license.

**Comment by AntonLV** [comment]
Dark mode for calendar was add in ticket #4391

**Comment by AntonLV** [comment]
Dark mode for calendar was add in ticket #4391
