### ISSUE TITLE
Use HTMX to load page content without genaral page structure

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4641]
https://htmx.org/reference/

Also:

- [x] 1. Try to attach this to links in submenus - https://htmx.org/extensions/preload/
- [ ] 2. Use for tabs - https://htmx.org/examples/tabs-javascript/

Issues:

- [x] 1. More menu. It doesn't close when selecting from inside the popup menu.
- [x] 2. Manage grids: '_sys_grid_confirmation' key isn't translated.
- [x] 3. Manage grids (may be others): Some filters with dropdowns always return empty results.
- [x] 4. Issue with comment posting in Timeline on View Profile page. More info [here](https://github.com/unacms/una/issues/4641#issuecomment-2114022364).
- [ ] 5. Account settings. Any form that has content will popup the message about leaving the page will lose the data, HTMX fires before you press yes or no, so it always loads. **Note**. This issue can be addressed later. Because for now HTMX is a part of Artificer template while form checking is in core.
- [x] 6. Mobile hamburger: Issue with subpage loading. More info [here](https://unacms.com/cmts-view/i2d575?sys=bx_forum&cmt_id=48700).

**Comment by AntonLV** [comment]
Bugs and suggestions: https://unacms.com/d/htmx-14-0-0-b1-bugs-improvements

**Comment by AntonLV** [comment]
Comment cannot be posted on View Profile page (any event in Timeline) when 'Enable cache for HTML files' is enabled and the page was just loaded. For example, using Profile link in Account popup: https://unacms.com/d/timeline-comments-14-0-0-b1
```
quill Cannot import modules/imageUploader. Are you sure it was registered? [logger.js:6:4]
quill Cannot load imageUploader module. Are you sure you registered it? [logger.js:6:4]
quill Cannot import modules/imageUploader. Are you sure it was registered? [logger.js:6:4]
Uncaught TypeError: e is not a constructor
```

**Comment by 272development** [comment]
Hope to see some progress with HTMX, it makes UNA much more mobile friendly, an reduces page load by nearly 70% on mobile.

Hope to see it integrated/fixed soon.

**Comment by 272development** [comment]
Header text bug:
[https://unacms.com/cmts-view/i2d575?sys=bx_forum&cmt_id=49980](https://unacms.com/cmts-view/i2d575?sys=bx_forum&cmt_id=49980)

Solution is simple, $(class/id).text(page title) -- for example, not correct 😁

**Comment by 272development** [comment]
Found another bug...

If Groups page has Messenger block, it works if directly going to URL.  If you go to a different tab (example: Info) then back to Groups, messenger block shows, but it does not activate properly. The input message box stays compact and you can not write anything.

Hope I explained well. -- Wise
