### ISSUE TITLE
Alert Box Update

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#465]
Current Alert box is too faint, barely visible and unredable for long texts. With short texts it looks too insiginificant and hard to notice.

![image](https://cloud.githubusercontent.com/assets/22210428/19506063/c9aca30e-9613-11e6-9e7f-c56fbe2c159b.png)

Update it to a look like this, with normal text and support for header and buttons when needed. Also ability to close it.

![image](https://cloud.githubusercontent.com/assets/22210428/19506194/1c82546a-9615-11e6-9a37-8476bdc4a3d2.png)

**Comment by AlexTr** [comment]
Current MsgBox supports text only and has no title or close functionality. So we can implement text only.
