### ISSUE TITLE
Polls: not compatible image width is used for wide screen devices on browsing page

### ISSUE THREAD

**Issue by AlexeyUna** [unacms/UNA#4665]
The image, originally 500px wide, has been stretched to 1054px.
![image](https://github.com/unacms/una/assets/22319431/bc46a894-6264-4234-b4b5-cb04f56cb9b9)

**Comment by AntonLV** [comment]
It's recommended to use bigger images as Cover image. Cover image transcoder has 1200px as max width, which means that very big images will be resized to this size.

**Comment by AlexeyUna** [comment]
On view pages such as Latest Popular and blocks like Featured, the Gallery transcoder filter is used to convert images to a width of 500px. However, as shown in the attached screen image, the placeholder size is 1054px. This causes the image to stretch to double its original size, resulting in poor appearance. Perhaps using a cover image for view pages could solve this issue.

Furthermore, the minimum height of the view images is set to 300px in main.css, which may cause narrow images to stretch as well.
