### ISSUE TITLE
Missing link to member

### ISSUE THREAD

**Issue by newton27** [unacms/UNA#467]
Not sure if this is supposed to link to the members page but it looks like it should.
On this page,
/page/notifications-view
see the images.
![empty-link](https://cloud.githubusercontent.com/assets/4349640/19507164/0ba96032-959f-11e6-9606-21e75e9c7306.JPG)
![empty-link2](https://cloud.githubusercontent.com/assets/4349640/19507165/0ba9f718-959f-11e6-974b-2a68915e4e3f.jpg)

**Comment by AlexTr** [comment]
I suspect that this is just an account, which has no profiles created.

**Comment by newton27** [comment]
No, all these names are profiles and not accounts.

**Comment by AlexTr** [comment]
Could you describe this event in more details? which type of profile ? subscribed to what ? what is the type of logged-in account ? is logged in account subscribed to CentricCHS profile ?

**Comment by newton27** [comment]
![no profiles](https://cloud.githubusercontent.com/assets/4349640/19574935/5af85c10-96da-11e6-93b9-668eb15dab4c.JPG)
OK, turns out it is a account. This does not make sense as well.
Why would "accounts" not be active, anywhere?
When new members sign up and fail to make profile there is no way to access them except me manually contacting them via the email provided. When this happens they can explore the site and I cannot stop them, just delete the account seems the only way.

**Comment by AlexTr** [comment]
If account has no profiles created, the special message is displayed on every page and asks to create profile.
By default account without profile can't perform any actions on the site, you can also set what account do on your site in Studio > Permissions > Account > Actions
