### ISSUE TITLE
Covers don't work correctly on Android devices

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4707]
https://unacms.com/cmts-view/1tl8eyo?sys=bx_forum&cmt_id=48643

https://unacms.com/cmts-view/1tl8eyo?sys=bx_forum&cmt_id=48596

Check on iOS devices as well.

**Comment by 272development** [comment]
Would be nice to see some movement on this issue. It is a long term UNA issue.  It affects iOS as well as Android - any touch device.

Please provide a fix.
