### ISSUE TITLE
"Favorite List" block isn't working correctly

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#4721]
- [x] 1. make Favorite List block tro be not copyable
- [x] 2. fix favourite lists in Discussions

**Comment by AlexTr** [comment]
https://unacms.com/cmts-view/14adl5r?sys=bx_forum&cmt_id=48816

**Comment by AntonLV** [comment]
1. "Favorite List" block shouldn't be copyable in Pages builder because it's a specific block which depends on the pages' parameters.
It's used on View Favorite List page, like `page/posts-favorites?profile_id=3&list_id=1`

**Comment by AntonLV** [comment]
2. Discussions: Favorite doesn't work.
