### ISSUE TITLE
bash: README.md: command not found when trying to start the cron

### ISSUE THREAD

**Issue by akshitsingla** [unacms/UNA#4740]
I am getting this error when I'm trying to setup the cron job post installation:
bash: README.md: command not found

Here is how I am deploying the app:
https://github.com/assldev/unacms-tutorial

I also want to know what cron jobs are being run anyway?

**Comment by AlexTr** [comment]
it may be that path to php binary is incorrect, also it would be great if you post your question in [official UNA support forum](https://unacms.com/discussions-home) providing some more details, at least what is the command you are running before receiving this error
