### ISSUE TITLE
Pages don't reload after logging in or posting content

### ISSUE THREAD

**Issue by pletchman** [unacms/UNA#4768]
We've seen this issue through several versions of the UNA site. When we log in to site it returns to home page still showing generic 

https://github.com/user-attachments/assets/65207ca4-693a-4efb-9050-d1475c39a971

We've tried several different browsers and operating systems. Also tried it on clean installs and even removing any third-party apps just to see if it helps. We are running latest version as well

**Comment by AlexTr** [comment]
It looks like you turn on CloudFlare cache, and it's not configured properly, I would suggest to try to disable CloudFlare cache to see if it helps
