### ISSUE TITLE
Update Posts snippets and cards views layout

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#478]
Update according to https://app.moqups.com/ab@una.io/ePosWLrcQQ/edit/page/a79999dde

![image](https://cloud.githubusercontent.com/assets/22210428/19643879/640c165a-9a38-11e6-83ef-6099d5514147.png)

**Comment by AlexTr** [comment]
@antaratma could you upload bigger image please ? the link isn't working either

**Comment by AntonLV** [comment]
Timeline cards were updated.
