### ISSUE TITLE
Application mode: Manage cover buttons overlay top menu

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#4808]
![изображение](https://github.com/user-attachments/assets/547a1a57-7d72-4ecb-8a38-34f222e98c50)

**Comment by AlexTr** [comment]
It still overlaps left menu when on small screen left menu is expanded:
<img width="716" alt="image" src="https://github.com/user-attachments/assets/0d774acb-24e5-4822-9d65-6dfd5b42379d">

**Comment by AlexTr** [comment]
It still overlaps "Apps" popup menu
<img width="252" alt="image" src="https://github.com/user-attachments/assets/200e5cee-9258-4b8e-acde-46026f50b59d">
