### ISSUE TITLE
Forum: draft saving problem

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#501]
It looks like when Forum title is cleared and draft is saved, it starting to create many drafts with empty title or title with [Object]:

![screen shot 2016-11-27 at 10 06 08 am](https://cloud.githubusercontent.com/assets/3324866/20644508/74461eaa-b48a-11e6-96cc-f09fe7f986b2.png)

**Comment by AntonLV** [comment]
Cannot reproduce.
