### ISSUE TITLE
Content manage/administration has no link to particular content

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#551]
For example in Groups (and maybe some other modules too):

![screen shot 2016-12-31 at 10 07 18 am](https://cloud.githubusercontent.com/assets/3324866/21575742/1b918c5a-cf41-11e6-9866-b20f3ffc92a0.png)

**Comment by AntonLV** [comment]
Done for Groups and Events modules.

**Comment by AlexTr** [comment]
I've noticed the same issue in Orgs module.

Also Groups and Events modules display incorrect information for "Created" field in manage own entries - it's the same for all Groups/Events, it looks like it displays creation date of owning account or something like this.
