### ISSUE TITLE
Polls module.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#562]

**Comment by andreyasko** [comment]
- [x] Implement http://www.chartjs.org/ to show horizontal result bars under each response option. Draw on the first load and redraw with animation after a vote was casted. 

- [x] Put description/question block first, before the answers/results block.

- [x] Add two options in posting form: **Anonymous vote** (checkbox) and Hide results until voted (checkbox). Implement accordingly.

**Comment by newton27** [comment]
Are there options for members only?
As of now, anyone can vote on the polls if set to public. If so that is an issue.

**Comment by AlexTr** [comment]
@newton27 https://github.com/unaio/una/issues/579
