### ISSUE TITLE
Database selection with minus

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#577]
Couldn't update timeline module because of the database name (minus).
I changed it from **una-de** to **una_de** and everything went fine.

![maxthonsnap20170213204205](https://cloud.githubusercontent.com/assets/13453103/22899951/f43bbaa4-f22c-11e6-9d3e-bd563b859a81.png)

**Comment by AlexTr** [comment]
@AntonLV  It looks like database name in SHOW TABLES query is not properly escaped.
