### ISSUE TITLE
Protean: Spaces in same fields result into a plain website

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#578]
Example: I want to set a border-radius for each single corner. So I enter "0 20px 20px 0". But because of the spaces the website can't return any content (plain page). This bug is in some more fields, but not in all (border size can handle spaces).

**Comment by AlexTr** [comment]
> Я установку радиуса делаю через нашу стандартную ЛИСС функцияю
> .radius(@val)
> а она не хавает входные данные в виде строки с отдельными значениями, для каждого угла.
