### ISSUE TITLE
ACL: allow to add zero price level, so members can switch for free

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#583]
Now membership level can't be changed by user, allow to create zero price level period by studio operator so users can switch to it if such option created by operator.

Please comment if you have any other suggestion.

**Comment by AlexTr** [comment]
@AntonLV I've chosen free Premium level for 7 days, but got it forever:

![screen shot 2017-03-18 at 5 06 54 pm](https://cloud.githubusercontent.com/assets/3324866/24071495/7f237730-0bfd-11e7-8dc4-ec83ff815dba.png)
![screen shot 2017-03-18 at 5 06 46 pm](https://cloud.githubusercontent.com/assets/3324866/24071496/7f263880-0bfd-11e7-81cb-7ab50e86f621.png)

**Comment by AntonLV** [comment]
Fixed here
https://github.com/unaio/una/commit/95867a6e05406d9d03f952d18e7ca6a893663d50
