### ISSUE TITLE
Social login: Compact view

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#592]
Maybe add an option in studio, to display social login buttons in a more compact design.
The current full-width buttons take a lot of space.
![maxthonsnap20170214183144](https://cloud.githubusercontent.com/assets/13453103/22940999/17515f64-f2e4-11e6-830c-70979f83f398.png)

**Comment by AlexTr** [comment]
1) Buttons should show title upon onhover effect.
2) Add social login buttons to join form
