### ISSUE TITLE
Module download: PHP memory_limit?

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#593]
I tried to download your files module, but I got the following error:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 81801216 bytes) in /inc/utils.inc.php on line 845

I added **ini_set('memory_limit', '-1');** before the given line and could finally install it.

**Comment by AlexTr** [comment]
What is the module it's happening with ?

**Comment by ZHENYAio** [comment]
Files-Module. Tested it with other modules and they worked fine.
