### ISSUE TITLE
Stop applying Protean mix in studio

### ISSUE THREAD

**Issue by ZHENYAio** [unacms/UNA#594]
It's kinda odd :/
![maxthonsnap20170214193931](https://cloud.githubusercontent.com/assets/13453103/22943366/9aa1c6c0-f2ed-11e6-8ee1-9cd7ac793b8f.png)
![maxthonsnap20170214194015](https://cloud.githubusercontent.com/assets/13453103/22943365/9a9e013e-f2ed-11e6-8c24-5b565384f585.png)

**Comment by AlexTr** [comment]
Maybe you've modified it, Protean template has white background by default. Try to disable then uninstall Protean module, then install it again to reset to the default styles, you will need to set another template as default - for example Ocean to do it.

**Comment by ZHENYAio** [comment]
No modifications made. It's also on another site, which I installed just some weeks ago (B3).

Ok. Installed Ocean, disabled and uninstalled Protean, installed it again... But it's always there.
![maxthonsnap20170215143810](https://cloud.githubusercontent.com/assets/13453103/22976812/8f43deb8-f38c-11e6-8a18-4c544a4496f2.png)

Maybe because of the cache? (screenshot taken before reinstalling the module)
![maxthonsnap20170215143144](https://cloud.githubusercontent.com/assets/13453103/22976822/9dbc5678-f38c-11e6-9ace-1cfd9caf0ee5.png)

**Comment by AlexTr** [comment]
@AntonLV it looks like some of Protean styles are applied to Studio
