### ISSUE TITLE
Payments: Show All Subscriptions list to admin/operator.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#620]

**Comment by AlexTr** [comment]
1. It looks like search in subscribers is working for Persons only. Please check why it isn't searching by Org, Event and Group name.

2. In Dashboard, rename link from "X subscribed me" -> "X subscribers"

3. When clicking on "Subscribers" it should scroll to the block with subscribers, the same is for "Subscriptions" (just in case if it's moved down the page)

**Comment by AlexTr** [comment]
4. Use "rss" icon for Subscribers & Subscriptions on dash page
