### ISSUE TITLE
Subscriptions management pages.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#622]
1. Display who is subscribed to your profile. Allow to make this list public or private.
2. Display whom are you subscribed to (allow to unsubscribe from one place)

**Comment by AlexTr** [comment]
1. It looks like search in subscribers is working for Persons only. Please check why it isn't searching by Org, Event and Group name.

2. In Dashboard, rename link from "X subscribed me" -> "X subscribers"

3. When clicking on "Subscribers" it should scroll to the block with subscribers, the same is for "Subscriptions" (just in case if it's moved down the page)

4. Use "rss" icon for Subscribers & Subscriptions on dash page

5. Rename blocks "My Subscribers" & "My Subscriptions" to "Subscribers" & "Subscriptions", so it will work when the list is public. 

6. "Public subscriptions list" & "Public subscribers list" settings should be in module's setting in Studio.

**Comment by AntonLV** [comment]
№1 Works as it should.
№2 - №6. Done.
