### ISSUE TITLE
Don't allow to delete operator profile by themselves

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#635]
- in delete own account form
- in accounts administration grid

**Comment by AntonLV** [comment]
RE in accounts administration grid:
There is no possibility to delete your own profile from Accounts module -> Manage grid. Single 'Delete' actions aren't available. Bulk 'Delete' actions return error message 'Cannot delete the selected account(s)'.

**Comment by AntonLV** [comment]
RE in delete own account form:
Fixed.
