### ISSUE TITLE
Licences: Don't show notification badge or be able to clear notification

### ISSUE THREAD

**Issue by ghost** [unacms/UNA#649]
If the user has a license, a notification badge with the number of license shows in their account menu, and also in the header. This doesn't seem to clear, so it always shows for the user.

It would be better to either move this notification to the Notifications section so it can be cleared, or otherwise not show the notification once the user views their Licenses screen.

**Comment by AlexTr** [comment]
Please could you clarify it in more details ? with the screenshots if possible

**Comment by ghost** [comment]
Bah, I'm sorry. This was a customized install and I blanked on the default term. Purchases = Licenses. It's the Licenses entry in the account menu. Here's a screenshot:
<img width="1008" alt="screen shot 2017-05-02 at 9 12 33 am" src="https://cloud.githubusercontent.com/assets/14158409/25619086/95a3e4c6-2f17-11e7-9d00-46b5296cd317.png">

**Comment by AlexTr** [comment]
Actually this notification is gone as soon as license is registered. However not all products can be registered (for example services), so we'll consider some another another way to clear this notification.

**Comment by AlexTr** [comment]
I think to "not show the notification once the user views their Licenses screen" is the way to go.
