### ISSUE TITLE
Storefront UNA Account Login Error

### ISSUE THREAD

**Issue by dansdionne** [unacms/UNA#672]
From Studio, I press + and it brings me to the Store.php storefront. It says I need to login to my UNA account to get data.   
`YOU NEED TO TO LOGIN INTO YOUR UNA ACCOUNT TO GET DATA. CLICK HERE TO LOGIN.`   
   
When I press the link, it says:   
`THE REDIRECT URI PROVIDED IS MISSING OR DOES NOT MATCH`   
At the link:   
`https://una.io/m/oauth2/auth?response_type=code&client_id=sbj4x6hnar&redirect_uri=http://example.com/una/studio/store.php?page=goodies&scope=market&state=y6rBYgP2NijAEn5r79Qx`   
   
To me, it appears that `redirect_uri` should be `redirect_url`, so I tried it out and it brings me to a site that asks: `Choose profile to use on "testKey" site:`   
   
When I select my profile it says: `METHOD(ACTIONWWW.EXAMPLE.COM) WAS NOT FOUND IN MODULE(OAUTH2)`
   
Is this a bug?

**Comment by AlexTr** [comment]
Could you please provide you UNA.io key ? or your site domain ?

**Comment by dansdionne** [comment]
Hi Alex. I was not sure if I should keep my UNA.io key private or not. Is it good practice to keep it private, or does it not matter? My site domain is `www.keywebspace.com/una`. It is just an experimental area where I am testing out the software.

**Comment by dansdionne** [comment]
Hi Alex. This is unrelated to the original question, but I am wondering if I should create issues for questions and bugs here? I am not an official developer. I just started using the software. Can anyone become a developer? I found another problem. When I go to the New Post page, at the bottom of the Text box there is a letter p. If I click the letter p, it selects some content in the text box. I don't think the p should be there. I can create another issue for this if you think I should.

**Comment by AlexTr** [comment]
> I was not sure if I should keep my UNA.io key private or not.

UNA.io "key" can be public, UNA.io secret - must be keep private.

> if I should create issues for questions and bugs here?

it's better to report bugs in [una.io](https://una.io/page/discussions-home) forum, then if it's confirmed someone from UNA team can create an issue.

> When I go to the New Post page, at the bottom of the Text box there is a letter p. If I click the letter p

It's ok, it just shows that you are currently typing text in <P> HTML tag.
