### ISSUE TITLE
Profile based modules snippets: make them responsive on mobile screens

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#680]
When profile based module snippet is displayed on mobile screen - display them with full width, so it will not be empty spaces on the right.

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/3324866/26575464/0637b312-452e-11e7-97b1-0af28806c701.jpg)

**Comment by AntonLV** [comment]
Already fixed by using centering.
