### ISSUE TITLE
Getting Started / Requirements - PHP 5.4 has dropped register_globals and safe_mode

### ISSUE THREAD

**Issue by eddiegeorge** [unacms/UNA#690]
At: https://github.com/unaio/una/wiki/Requirements
**register_globals** must be off
**safe_mode** must be off
Both parameters have been dropped from PHP 5.4

p.s. I'm just getting started with UNA so wasn't sure whether your team would prefer me to edit the documentation directly?

**Comment by AlexTr** [comment]
thank you, corrected
