### ISSUE TITLE
Forms: multiple select must support up to 63 values on 64bit systems

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#693]
1) Default value select shown only 31 items

**Comment by AntonLV** [comment]
If you use 64x system on your server then it's recommended to change the value of `BX_DOL_INT_MAX` constant in **inc/params.inc.php** file from 2147483647 to `PHP_INT_MAX`. So, you'll have 
```php
define('BX_DOL_INT_MAX', PHP_INT_MAX);
```
instead of
```php
define('BX_DOL_INT_MAX', 2147483647);
```
