### ISSUE TITLE
Notifications Cards

### ISSUE THREAD

**Issue by andreyasko** [unacms/UNA#711]
Update the notification popup design (currently a black full-screen popup over the header) for both Studio and frontend. Use floating cards in bottom-left corner. 360px max width. Border #000 0.2, Shadow 1px offset with 5px blur, #000 0.2.

Use it for all notifications created by modules, studio notifications and alerts. Timeout and disappear after 10seconds, or use cross icon to close immediately.

![image](https://user-images.githubusercontent.com/22210428/27210257-7a9d6954-5294-11e7-826f-70e9a4113988.png)

**Comment by AlexTr** [comment]
@antaratma maybe show it in top-right corner ?

**Comment by andreyasko** [comment]
@AlexTr top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.

**Comment by andreyasko** [comment]
top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write top right may not be the best choice anymore due to desktop/browser notifications popping up at the same time in top right, which would frequently create overlaps.
 @antaratma
  
            
 
Write 
            
 
Write
