### ISSUE TITLE
Upload files and image

### ISSUE THREAD

**Issue by FabioCammisa** [unacms/UNA#722]
Hi, i have installed una on my website www.fanzone.it but do not work upload of files and images. How resolve? Thanks

**Comment by newton27** [comment]
You would be better to post your "site" problems on the proper support site. 
https://una.io/page/discussions-home
I looked and joined your site. You should probably turn off all your caches, when I joined with Facbook my photo was uploaded and shown. I then changed it and the cover photo but that didn't work.

**Comment by FabioCammisa** [comment]
Ok thanks, i put this problem on the support site

**Comment by AlexTr** [comment]
https://una.io/page/view-discussion?id=205
