### ISSUE TITLE
Typos, Missed translations, etc

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#737]
`Проверить хэш модуля:` rename to `Проверка хэш модуля:`

**Comment by AntonLV** [comment]
Previously listed were fixed.

**Comment by AntonLV** [comment]
Feel free to post more in comments to avoid new similar tickets creation.

**Comment by AntonLV** [comment]
_sys_txt_empty in Russian should be 'Пусто' instead of 'Очистить'

**Comment by AlexTr** [comment]
@AntonLV 

Dashboard -> Subscriptions -> Click on Gear Icon -> Request Cancellation   
(BTW Cancellation is spelled wrong in the drop down option, is currently: Cancelation and should be Cancellation)   
https://una.io/cmts.php?sys=bx_forum&id=450&cmt_id=1164

**Comment by AntonLV** [comment]
Missing key in Groups in Russian language.
_bx_groups_form_profile_input_allow_view_to_desc

**Comment by AntonLV** [comment]
Wrong translation for _bx_groups_alert_action_join_request key
`запрос на присоединение к событию`
it should be 
`запрос на присоединение к группе`
