### ISSUE TITLE
Add option to set default page to redirect user to after login

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#747]
Now it always redirects to `account-profile-switcher`

**Comment by Dream16webdesign** [comment]
Hi Alex,
Thanks for the collaboration on this. It seems that the bit of code at the end of members.php:
bx_require_authentication();

header('Location: ' . BX_DOL_URL_ROOT . BxDolPermalinks::getInstance()->permalink('page.php?i=account-profile-switcher'));

Could be tweeked to send wherever. a varible could pretty easily be assigned to rediect wherever. the question is the best way to implement this. Please let me know your thoughts on this. I'd be happy to contribute.

**Comment by AlexTr** [comment]
@Dream16webdesign 
Thank you, yes, you can change this, but it isn't recommended since it maybe problems with the upgrade after custom modifications.

**Comment by AntonLV** [comment]
By default UNA auto-detects referrer page URL and redirects on that page after login automatically. Redirect to Account Switcher appears only when somebody login directly from member.php page. It means that a user should type URL like the following http://www.domain.com/member.php directly in his browser to get on Account Switcher page. It happens not so often and therefore the setting is not needed. However we decided to change the default redirect to Dashboard page.

**Comment by Dream16webdesign** [comment]
Well thanks for getting back to me on this. The original issue stems from the splash page nav menu link going to the login page which then logs in through member.php which redirects to this page. how do we redirect to a different page or any fix for this annoying problem. The login on the bottom of the splash page goes one place and the login at the top of the splash page goes somewhere else

**Comment by AlexTr** [comment]
@Dream16webdesign login form almost always redirects to the page where account link in top right corner was pressed. Only when there is no referrer page, then member is redirected to default page:
- when user fills-in login form on splash page
- when user comes to login form without referrer, or from another site

In all other cases user is always redirected back to the page where he/she clicked on account link in top-right corner.
