### ISSUE TITLE
Notifications: new messages bubble not always is cleared up

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#751]
I suspect that this is happening after we introduced privacy for the notifications. So it looks like we need to check privacy for all notifications which are displayed in notifications bubble to filter out notifications which user can't see.

https://una.io/page/view-discussion?id=245
https://una.io/page/view-discussion?id=290
https://una.io/page/view-discussion?id=328
https://una.io/page/view-discussion?id=349

**Comment by AntonLV** [comment]
The issue appeared because of the "Auto Subscribe profiles on Friendship" feature. Both events "Friendship" and "Subscription" have equal dates and it affected the events ordering during new events section.
