### ISSUE TITLE
Albums: actions cut-off in Media Snippet in thin column

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#758]
I think Outline should fit into thin column by default.

https://una.io/page/view-discussion?id=242
https://una.io/page/view-discussion?id=364

![actions cut off](https://user-images.githubusercontent.com/3324866/28350562-6e93f862-6c52-11e7-8986-4f7bed1103b8.JPG)

**Comment by andreyasko** [comment]
First, we can make them looks same as in timeline - icons only, no buttons. Then, make them shift to the second line if one isn't enough. In most cases outline/timeline should be used in wider blocks anyway.

**Comment by AntonLV** [comment]
I cannot reproduce the issue in Timeline module, Outline block using Ocean template. Actions in Outline item are already auto wrapped when there is no enough space.
When I checked the site I found out that the problem appears in Albums module -> Featured Photo's by Author block.
