### ISSUE TITLE
Notifications: sometimes one notifications overwrites another notifications

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#800]
Description of the problem:
https://una.io/cmts.php?sys=bx_forum&id=355&cmt_id=863

**Comment by AlexTr** [comment]
Something wrong in Groups module:

> Там какие-то странные данные передаются Нотификейшнс модулю при возникновении событий. Например, постинг в таймлай, жоин группы и тп.
> 
> 
> Например, Жоин Группы. передает object_id = ИД профиля группы, а object_owner_id = ИД жойнящегося. Хотя это должен быть ИД владельца объекта.
> 
> 
> Потом при первом просмотре в object_owner_id уже передается Контент ИД Группы. И происходит обновление.
> 
> Поэтому при втором входе сообщение исчезает.
> 
> Тк первоначально оно типа пренадлежит Прижойнившемуся а потом переходит к Группе (Как и должно быть изначально).
> 
> И после всего этого если зажойнившийся сделает Фоллоу группы, то все месаги ему становятся видны - как и должно быть. Тк Нотификейшнс показывает Подписки и Свой контент.
> 
> А ГРуппа не является своим контентом.
> 
> Она есть отдельный профиль.
> 
> Просто прижойнись в группу и посмотри тиблицу bx_notifications_events потом зайти на страницу Нотификейшенов и опять посмотри bx_notifications_events

**Comment by AlexTr** [comment]
It looks like it's happening again:
https://una.io/cmts.php?sys=bx_forum&id=349&cmt_id=1226

**Comment by AntonLV** [comment]
1. Take a look at the following code in BxBaseModProfileAlertsResponse::response method. 

> // re-translate timeline alert for timeline in this module for posts made by other profiles
>         if ('bx_timeline' == $oAlert->sUnit && 'post_common' == $oAlert->sAction && ($oGroupProfile = BxDolProfile::getInstance($oAlert->aExtras['object_author_id'])) && $oGroupProfile->getModule() == $this->_oModule->getName() && $oGroupProfile->id() != $oAlert->iSender) {            
>             $aContentInfo = $this->_oModule->serviceGetContentInfoById($oGroupProfile->getContentId());
>             bx_alert($this->_oModule->getName(), 'timeline_post_common', $aContentInfo[$CNF['FIELD_ID']], $oGroupProfile->id(), array('content' => $aContentInfo, 'group_profile' => $oGroupProfile->id(), 'profile' => $oAlert->iSender, 'notification_subobject_id' => $oAlert->iSender, 'object_author_id' => $aContentInfo[$CNF['FIELD_AUTHOR']]));
>         }

Especially at `'object_author_id' => $aContentInfo[$CNF['FIELD_AUTHOR']]` The initial creator of the group is sent as Group's Owner. 
Now take a look at the following code in BxBaseModGeneralModule::_serviceGetNotification method. 

> return array(
> 			'entry_sample' => $CNF['T']['txt_sample_single'],
> 			'entry_url' => $oGroupProfile->getUrl(),
> 			'entry_caption' => $oGroupProfile->getDisplayName(),
> 			'entry_author' => $oGroupProfile->id(),
> 			'subentry_sample' => $oProfile->getDisplayName(),
> 			'subentry_url' => $oProfile->getUrl(),
> 			'lang_key' => $sLangKey,
> 		);

Especially at `'entry_author' => $oGroupProfile->id()` The group's profile ID is sent as entry owner and I think it correct. Note, the updated info is automatically saved in the Notifications module's DB.
So, we have group Creator Profile ID at the beginning and Group Profile ID just after the first display of related Notification. Therefore the event disappears from timeline post owner's notifications if he didn't subscribe the group yet.
2. Is there any reason why `$oAlert->iSender` is sent as **notification_subobject_id**. By default, subobject was added for situations when comment was posted in some content. Content is object with **object_id**, **object_owner_id** and **object_privacy_view**, in the same time comment is subobject with **subobject_id** only.

**Comment by AntonLV** [comment]
The issue was fixed in Ticket #940
