### ISSUE TITLE
Iframely BUG

### ISSUE THREAD

**Issue by ZsgsDesign** [unacms/UNA#817]
I'm using SSL on my website and find that Iframely doesn't work. It just link to http:// and then chrome will report Mixed Content.
At first I think this problem is caused by  Iframely's CDN. Then I contact the support team,HERE is the reply:

> 
> That won't work. Embed.js is the client library and needs to be added to the page by the browser. See it here: https://iframely.com/docs/embedjs
> I don't see embed.js in the source code of your page, and neither in the network timeline of the debug tools. Looks like you run that code on the server, and in that case you won't get the right results.
> The mixed content problem you see in that case is caused by this. Our script tries to get the api key from the src of the file, and since it can't find it in server environment, it falls back to "open" demo endpoint. That demo endpoint does not indeed work with HTTPS. 
> 
> Please take a read of the doc and move the integration into the browser. If you need it on the server, you can just as well start making API calls to our /api/oembed or /api/iframely API endpoints, and simply get HTML field from the API response, then add it to your page (but be sure to cache the html in your server)

**Comment by AlexTr** [comment]
Actually we add embed.js, but since it's cached, this file is part of big JS file which contains all JS files on the page. You can disable JS cache and then it will be visible.
