### ISSUE TITLE
Antispam: Errors.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#824]
- [x] 1. Installation error:
DELETE FROM `bx_antispam_disposable_email_domains` WHERE `list ` = ?
Mysql error: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined

- [x] 2. Create account (join) error:
SELECT `id` FROM `bx_antispam_disposable_email_domains` WHERE `list` = ? AND `domain` = ?
SQLSTATE[HY093]: Invalid parameter number: parameter was not defined

**Comment by AlexTr** [comment]
https://github.com/unaio/una/commit/95bfd2c137491933d0e183ced3581729dd30e1e2
