### ISSUE TITLE
Persons: profile creation error.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#825]
Mysql error:
Unknown column 'gender' in 'field list'
Looks like 'bx_persons_data' table wasn't updated in install.sql file. I cannot see 'birthday' field there too.

**Comment by herry2016** [comment]
I get this error
![untitled](https://user-images.githubusercontent.com/25043044/30344801-635bf9e6-9820-11e7-8d0c-aff79edbe02e.png)
