### ISSUE TITLE
Add Location field as search criteria

### ISSUE THREAD

**Issue by kisonik** [unacms/UNA#866]
The "Location" field is based on Google Maps.
If we add it as a search criteria, it should also be based on Google Maps but in this case it will be used to populate data from the database rather than inserting it.
If possible, this field should be part of the elastic search.

**Comment by AlexTr** [comment]
Error when nothing is entered in search form:
```
Query:
SELECT `bx_persons_data`.`id` FROM `bx_persons_data` INNER JOIN `bx_persons_meta_locations` AS `tl` ON `bx_persons_data`.`id`=`tl`.`object_id` WHERE 1 AND (1 AND ) ORDER BY `bx_persons_data`.`added` ASC

Mysql error:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY `bx_persons_data`.`added` ASC' at line 1
```
