### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by herry2016** [unacms/UNA#868]
![untitled](https://user-images.githubusercontent.com/25043044/30344883-a59ab02c-9820-11e7-92b9-011a797cab0a.png)

**Comment by AlexTr** [comment]
Please set to true the following define in inc/header.inc.php:
```
define('BX_DB_FULL_DEBUG_MODE', true);
```
then try to generate an error again, you will get the full error details which will help tp know the cause of the problem.
