### ISSUE TITLE
Designer: issue with simultaneous covers uploading.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#879]
The issue appears when both covers (for common pages and for profile unit) are uploaded and saved at the same time. An image for the first one (common pages cover) was uploaded but doesn't exist after saving. Therefore all further changes with this cover are resulting with "Cannot remove current cover image". 

https://una.io/page/view-discussion?id=462

**Comment by kreativmind** [comment]
@AntonLV Please check the forum again https://una.io/page/view-discussion?id=462
I have updated the post with new information and an image. Thanks.
