### ISSUE TITLE
Comments: don't show error when nothing is changed during post edit

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#884]
I would suggest to use `res` DB function instead of `query`. One returns false on error, while another returns number of affected rows. Another option is to use `query` but with the following check:

```
false ===
```

**Comment by AntonLV** [comment]
Thank you for the suggestion. The feature uses standard BxDolForms::update method with call to BxDolDb::query inside. Therefore I cannot use **res** DB function and will stay with **query**.
