### ISSUE TITLE
Account profile usability

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#890]
- [x] 1. When I have an account, and don’t create a profile, I can still see “profile” link in member menu, which doesn’t work, but still there. We should not show it for “Account” only.

- [x] 2. Text in notification should be edited a litte to say:
`Please _create a profile_ to start using the site.`
instead of: 
`You have no profiles created, so you can’t perform any actions on the site, please create profile.`

- [x] 3. Don’t show Feed/Timeline on Account dash at all.

- [x] 4. Don’t show the profile links block on account Dash as well.

- [x] 5. Don't allow to buy anything under Account

- [ ] 6. ~~Update this `you don’t have any profiles` notification to be like a modal pop-over, that covers everything and only offers you to create a profile? with “close” icon, so that if they close it, they can continue using the site as account, but as soon as action assumes need to profile, the popup shows again~~

**Comment by AntonLV** [comment]
Points №1 - №5 were done.

**Comment by AlexTr** [comment]
Point 6 was done using another approach in https://github.com/unaio/una/issues/986
