### ISSUE TITLE
Timeline: post on separate page has the same title and no meta tags

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#904]
Post on separate page should have:

- [x] 1. title which depends on content, I think it can be something like "Admin added a shop item"
- [x] 2. add social meta tags like twitter:title, twitter:description, etc as well as usual meta tags like title and description

**Comment by AlexTr** [comment]
@AntonLV when timeline post is opened on separate page title is "Admin added ", without specifying what exactly was added

**Comment by AntonLV** [comment]
Yes, you are right such title appears for old items because they have <i> HTML tag in the title which is not displayed. It was fixed too.
