### ISSUE TITLE
Page's scroll doesn't jump to HTML anchor on page loading.

### ISSUE THREAD

**Issue by AntonLV** [unacms/UNA#922]
Issue appears because of modernizr.js (version 3.3.1) plug-in. 
Update up to version 3.5.0 should solve the issue.

**Comment by AlexTr** [comment]
After updating modernizr problem still has place

**Comment by AntonLV** [comment]
The issue appears because of enabled 'CSS Hyphens' feature (https://modernizr.com/download). It you build modernizr without it, the HTML anchor becomes to work. The issue appears because this feature tries to test find functionality making searches for different test elements.
