### ISSUE TITLE
navigation issue

### ISSUE THREAD

**Issue by herry2016** [unacms/UNA#963]
I am disabled the home page menu from my admin dashboard's. Navigation plugin

But it still display the menu on homepage
![screenshot_20171113-001229_01_01](https://user-images.githubusercontent.com/25043044/32727115-5bb8f00c-c8a1-11e7-9927-ffc6d896f663.png)
![screenshot_20171113-001108_01_01](https://user-images.githubusercontent.com/25043044/32727164-8b9c2992-c8a1-11e7-8549-c470f3f08ce7.png)

**Comment by AlexTr** [comment]
This problem is already reported in another issue: https://github.com/unaio/una/issues/934
