### ISSUE TITLE
Text based modules: add 2 new settings 

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#967]
These two settings are needed to optionally display additional info in browse unit/cards.

1) To display Nothing, Category, Tags (first 3 tags), Number of Comments or custom field (specified in separate setting

2) To display Nothing, Rating or Favorite actions

**Comment by andreyasko** [comment]
It looks like it is almost always impossible to create a universal approach to show meta info. Some people would require it in one place and some in the other. Can we only just define which info to show at all, without allowing to change the order or set where to show it exactly. We then implement it as suitable in the default templates, and then anyone can redefine positioning through templates.

**Comment by AntonLV** [comment]
Related commit: https://github.com/unaio/una/commit/bcc9fad977a973f973d37c08c52bab0d2fe45e18

**Comment by AntonLV** [comment]
Enhancement was realized using Menus engine instead of a number of settings. 'Snippet Meta Info' menu was added in all Text based modules, which allows to enable/disable, reorder and add new items in snippet meta info section.
