### ISSUE TITLE
Change help URLs from feed.boonex.com to feed.una.io

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#969]
In all modules install/config.php file, make related changed in DB when upgrade script is run, if value is stored in the DB.

**Comment by AntonLV** [comment]
Use MySQL query like the following:
> UPDATE `sys_modules` SET `help_url` = 'http://feed.una.io/?section={module_name}' WHERE `name` = 'bx_en' LIMIT 1;

**Comment by AntonLV** [comment]
Modules which are needed to be updated in the next release(s):
- [x] Antispam
- [x] Chat Plus
- [x] DataFox
- [x] Dolphin Connect
- [x] Facebook Connect
- [x] Google Connect
- [x] Intercom
- [x] LinkedIn Connect
- [x] Mailchimp
- [x] OAuth2
- [x] Profiler
- [x] SMTPMailer
- [x] Twitter Connect
- [x] UNA Connect
