### ISSUE TITLE
Get rid of "Empty" blocks where possible

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#995]
Do not show blocks with "empty" message when there is no content. Make sure that layout isn't damaged, since sometimes block with "empty" message is needed to not collapse page layout.

https://una.io/page/view-discussion?id=630

**Comment by AntonLV** [comment]
"Empty" blocks were hidden from Home and Profile pages.

**Comment by AntonLV** [comment]
"Featured" and "Favourite" blocks with "Empty" message were hidden.

**Comment by olariuromeo** [comment]
In drupal, the most advanced CMS, there is a module called vievs.

For example, there can be categories that can be generated in the taxonomy.

These categories can be used to generate menus, which contain pages, or pages can be generated that are attached to a node.

For example, a profile can have a menu called blog, if that user does not have any blog, then the visitor does not make sense to see that menu that opens a page devoid of content in which it is written that that user does not have any blog.

A site can have many apps, dozens or even more. It seems senseless to me to attach a menu to a profile that opens a page with no content. If that user does not create content in that application: blog, photos or something else, those pages and the menus to them must be invisible, or the empty page block in the page.

There must be a condition, if there is no content not to display anything. Neither page nor empty blocks.

Each user has his preferences to use one water or another. If the site has 30 apps, what sense does it make to display 30 menus that lead to empty pages on the user's profile page that has no content or public content in that app?

After so many years of development, the boonex team must also have a little practical sense, to provide clients with a script capable of displaying real content on a screen. Especially in this era of speed and small phone screens. I don't see the point of browsing some links without content. I think Google SEO has a robot there that penalizes sites with pages without content.

And BOONEX or UNA as you want to call yourself generates millions of useless pages on the internet, by providing this script that wastes people's time and electricity and other resources on servers to dispaly emty page.

5 years have passed but nothing has been done to improve the user experience in this regard. Each menu from each user must be activated or deactivated depending on the condition if it has content or not, also html blocks. When a user adds content to the respective app, the pages menu is automatically activated together with the html block in which the content is displayed. Also depending on the permissions the user has to view that menu or page or page block or content, become visible or not.

**Comment by olariuromeo** [comment]
![Screenshot_20230504-040046_Chrome](https://user-images.githubusercontent.com/2572824/236104166-299ce068-1472-43b9-a7a5-49b0d64e58d1.jpg)

**Comment by olariuromeo** [comment]
How many more years will it take to solve this problem? I would like to know when I should plan to launch an online website with UNA, in the current conditions even the turkeys would laugh of site

> "Empty" blocks were hidden from Home and Profile pages.



> "Empty" blocks were hidden from Home and Profile pages.

I don't see them hidden, do you see them hidden?
